### PR TITLE
added teensy36 pin configuration

### PR DESCRIPTION
**Pull request by teoman002**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @teoman002 you might want to take a look at https://github.com/tinygo-org/tinygo/wiki/Adding-a-new-board for some information on how to add support for new boards to TinyGo.

**Comment by deadprogram** [comment]
In the case of the Teensy 3.6 it uses an NXP Kinetis K66 processor:
https://www.pjrc.com/teensy/K66P144M180SF5V2.pdf

There are not yet any NXP based boards, so you will need to add support for this family/chip.

**Comment by teoman002** [comment]
I can also provide a K66 family svd file with default configuration. But I don't have enough knowledge what to do with them. Is it useful to upload it here?

**Comment by deadprogram** [comment]
Probably the first thing, would be to submit a PR to the https://github.com/posborne/cmsis-svd repo, which is where we are obtaining our SVD files.

Then we can look into adding the needed support for generating NXP-based TinyGo device wrappers. I think there are a couple of other people with similar interests.

In the meantime, I am going to close the PR. Please open a new PR once the SVD file is available in the cmsis-svd repo, using the guidelines in https://github.com/tinygo-org/tinygo/wiki/Adding-a-new-board

Thank you!

**Comment by firelizzard18** [comment]
I've submitted posborne/cmsis-svd#93 to add the SVD for the MK66FX1M0VMD18

**Comment by firelizzard18** [comment]
I'm working on this in #863 and I would love help

**Pull request closed without merging**
