### PR TITLE
all: pretend to be linux/arm in baremetal targets

### PR DESCRIPTION
**Pull request by aykevl**
So far, we've pretended to be js/wasm in baremetal targets to make the stdlib happy. Unfortunately, this has various problems because syscall/js (a dependency of many stdlib packages) thinks it can do JS calls, and emulating them gets quite hard with all changes to the syscall/js packages in Go 1.12.

This commit does a few things:
  * It lets baremetal targets pretend to be linux/arm instead of js/wasm.
  * It lets the loader only select particular packages from the src overlay, instead of inserting them just before GOROOT. This makes it possible to pick which packages to overlay for a given target. It also allows more fine-grained overlaying, like overlaying os or net without overlaying os/exec or net/http.
  * It adds a baremetal-only syscall package that stubs out almost all syscalls.

This should help with Go 1.12 support, see #211.

### CODE REVIEW

**Comment by aykevl** [comment]
Tested examples/blinky1 and examples/echo on Arduino Uno and PCA10040.

**Comment by deadprogram** [comment]
Tested a few examples from the `drivers` repo on the microbit and itsybitsy-m0. Looking good.

Did you happen to have a chance to try to build something for actual linux arm like on the raspberry pi?

**Comment by aykevl** [comment]
Rebased on top of dev.

> Did you happen to have a chance to try to build something for actual linux arm like on the raspberry pi?

In theory that should have been tested with qemu in CircleCI, but just to be sure I built a few examples on my amd64 laptop, copied them over to my rpi3 and ran them there. They all worked perfectly.

**Comment by aykevl** [comment]
Also note that I copied a few files over from the Go project, but as I left the copyright note in the header intact I think that should be fine.

**Comment by deadprogram** [comment]
Merging.

**Pull request merged**
