### PR TITLE
Better Digispark board support

### PR DESCRIPTION
**Pull request by erazemk**
This pull request intends to add better support for the Digispark board, based on the ATTiny85. The related issue is #1700.

TODO:
* [x] Add analog pins
* [ ] Add UART
* [ ] Add PWM

### CODE REVIEW

**Comment by BryanSouza91** [comment]
What happened with this? Is there any chance ADC, PWM and UART will be implemented? @erazemk did you get a reason that this was not merged?

**Comment by deadprogram** [comment]
I think the author of this PR is who closed it. Also, it does add pin numbers but not the code needed to actually read the ADC. So there is still a fair bit of work to implement it.

**Comment by BryanSouza91** [comment]
Thanks for the info! I'll keep exploring TinyGo to see if I can get it working.  Actually, I have a couple of generic Digispark boards I'd like to use with TinyGo. While I assume it's similar to the ATtiny85 port, is the bootloader a potential hurdle I'm missing?

**Comment by deadprogram** [comment]
> is the bootloader a potential hurdle I'm missing?

I don't think so. What is needed is really a matter of expanding the attiny85 implementation to include ADC etc.

**Comment by BryanSouza91** [comment]
Okay, I'll dive in. No promises but I'll see what I can figure out.

**Comment by erazemk** [comment]
No idea what happened at the time, I probably didn't have time to continue implementing the support and later on I forgot. I might try to add actual support, but for now it's fine that it was closed.

**Comment by BryanSouza91** [comment]
What needs to be worked on? I have read the [Adding a new board wiki](https://github.com/tinygo-org/tinygo/wiki/Adding-a-new-board) but I am a little unsure about the next steps. It seems to me that a lot of the avr definitions are the same for the ATtiny85 so that should make it easier, however the inheritance part is confusing me. I am not sure what gets inherited and what doesn't.
I also read through [issue #1598 related to support for Teensy 4.1](https://github.com/tinygo-org/tinygo/issues/1598) (which I am also interested in) which breaks down the requirements pretty well.

**Comment by deadprogram** [comment]
@BryanSouza91 there is already board definition for digispark https://github.com/tinygo-org/tinygo/blob/dev/src/machine/board_digispark.go

Also see https://github.com/tinygo-org/tinygo/blob/dev/src/machine/machine_attiny85.go
and
https://github.com/tinygo-org/tinygo/blob/dev/src/machine/machine_avrtiny.go

In short, the current implementation needs to be enhanced, not that a new board needs to be added. Hopefully that help clarify a little.

**Comment by BryanSouza91** [comment]
@deadprogram I understand that board_digispark.go needs to be expanded for ADC, UART, etc. 

I am unsure about the difference between machine_avr.go, machine_avrtiny.go and machine_attiny85.go. The reason is because if I add the ADC pin definitions to the board_digispark.go file then build the examples/adc program there are no errors however I assume it may not actual work since ADC is not implemented for the attiny85. So to further explore what needs to be done I appended the entire machine_avr.go file into the machine_attiny85.go file and tried to build examples/pwm and got errors about variables and methods already declared in machine_attiny85.go and machine_avr.go. That tells me that the tinygo compiler is using the machine_avr.go file for the attiny85. It also makes me think the ADC could actually work, I will try to test the ADC program to figure out if it works. So how do I trace the inheritance? What actually needs to be enhanced avrtiny or attiny85 or avr?

**Comment by BryanSouza91** [comment]
I tried the examples/adc with a simple NTC thermistor circuit and no surprise it did not work. It compiles fine with 
`tinygo flash -target digispark -size short examples/adc`
and
`tinygo flash -target digispark -tags avr -size short examples/adc`
however this happens with `-tags avrtiny`
```
$ tinygo flash -target digispark -size short -tags avrtiny examples/adc
# machine
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:25:8: port.DIRSET undefined (type *volatile.Register8 has no field or method DIRSET)
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:33:19: undefined: avr.PORT_PIN0CTRL_PULLUPEN
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:36:72: port.PIN0CTRL undefined (type *volatile.Register8 has no field or method PIN0CTRL)
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:40:8: port.DIRCLR undefined (type *volatile.Register8 has no field or method DIRCLR)
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:51:15: port.IN undefined (type *volatile.Register8 has no field or method IN)
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:58:8: port.OUTSET undefined (type *volatile.Register8 has no field or method OUTSET)
/home/bryansouza/Repos/tinygo/src/machine/machine_avrtiny.go:60:8: port.OUTCLR undefined (type *volatile.Register8 has no field or method OUTCLR)
```
Does this make sense? Is avrtiny a separate definition? Is it part of the inheritance scope for the digispark or attiny85?

**Comment by aykevl** [comment]
If you want to see which files are included, you can use `tinygo list -json -target=digispark machine`

It outputs a JSON file, which includes:

```json
        "GoFiles": [
                "adc.go",
                "board_digispark.go",
                "buffer.go",
                "buffer_generic.go",
                "machine.go",
                "machine_attiny85.go",
                "machine_avr.go",
                "pdm.go",
                "pwm.go",
                "runtime.go",
                "serial-none.go",
                "serial.go"
        ],
```

**Comment by BryanSouza91** [comment]
> If you want to see which files are included, you can use `tinygo list -json -target=digispark machine`
> 
> It outputs a JSON file, which includes:
> 
> ```json
>         "GoFiles": [
>                 "adc.go",
>                 "board_digispark.go",
>                 "buffer.go",
>                 "buffer_generic.go",
>                 "machine.go",
>                 "machine_attiny85.go",
>                 "machine_avr.go",
>                 "pdm.go",
>                 "pwm.go",
>                 "runtime.go",
>                 "serial-none.go",
>                 "serial.go"
>         ],
> ```

That's very helpful! Thanks

**Pull request closed without merging**
