### PR TITLE
machine/usb: Fix encoding of signed short values in descriptor and small improvements

### PR DESCRIPTION
**Pull request by Unrud**
**machine/usb/descriptor:**
* Fixed values 0xFF and 0xFFFF for HIDLogicalMinimum & HIDLogicalMaximum & HIDPhysicalMinimum & HIDPhysicalMaximum being encoded as -1.
* Added additional HIDUsagePage & HIDUsage & HIDCollection & HIDInput & HIDOutput helper functions

**machine/usb/joystick:**
* Initialize `HatSwitches` with `HatCenter` instead of the default `HatUp`.
* Support arbitrary number of `HatSwitches` instead of only 0-2
* Descriptor:
  * Replace unused second hat with padding
  * Reset HIDPhysicalMinimum & HIDPhysicalMaximum & HIDUnit for axis (was still set from hat)

### CODE REVIEW

**Comment by deadprogram** [comment]
@sago35 just wanted to verify that this PR does not break anything in tinygo-keyboard before merge, if you can please take a look. Thanks!

**Comment by sago35** [comment]
I will check tomorrow.

**Review by sago35 — APPROVED** [review]
LGTM
Thank you @Unrud 
I think the code has been improved nicely.
examples/hid-joystick works and tinygo-keyboard works fine.

**Comment by deadprogram** [comment]
Thank you very much for the additions @Unrud and to @sago35 for review/testing. Now merging.

**Pull request merged**
