### PR TITLE
Add -j option to smoketest

### PR DESCRIPTION
**Pull request by sago35**
#1330 

I created a PR to make it easier to check the CI results.
There is no plan to merge it for now.

### CODE REVIEW

**Comment by sago35** [comment]
before : c810628 loader: rewrite/refactor much of the code to use go list directly 

* linux : 1m46s
    * https://app.circleci.com/pipelines/github/tinygo-org/tinygo/3529/workflows/49b98cfa-5404-4c36-9ea8-7228b93de709/jobs/17606
* macos : 2m52s
    * https://app.circleci.com/pipelines/github/tinygo-org/tinygo/3529/workflows/49b98cfa-5404-4c36-9ea8-7228b93de709/jobs/17606
* windows : 3m29s
    * https://dev.azure.com/tinygo/tinygo/_build/results?buildId=2063&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=632617cc-49d1-5f82-37d2-600ea5832b67

**Comment by sago35** [comment]
after: 5da7119 

* linux : 41s
    * https://app.circleci.com/pipelines/github/tinygo-org/tinygo/3538/workflows/2ba0a518-1161-4572-8eb0-98ab1ec11325/jobs/17680
* macos : 59s
    * https://app.circleci.com/pipelines/github/tinygo-org/tinygo/3538/workflows/2ba0a518-1161-4572-8eb0-98ab1ec11325/jobs/17675
* windows : 1m42s
    * https://dev.azure.com/tinygo/tinygo/_build/results?buildId=2070&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=632617cc-49d1-5f82-37d2-600ea5832b67

**Comment by sago35** [comment]
The order of the output log is not guaranteed by `make -j`.
Also, the lack of the `--output-sync` option on macos makes the log output more difficult to read.

However, the processing time is much shorter.

| os | before | after |
|-----|------------|----------|
| linux | 106 s | 41 s |
| macos | 172 s | 59 s |
| windows | 389 s | 102 s |

**Comment by QuLogic** [comment]
This could be extended to allow any `-j` to make, but would require saving to different file names. But that really should be done anyway because right now any of the separate processes could read/write to the same file at a time.

**Comment by sago35** [comment]
It's not a good idea to write to the same file.
I think it needs to be fixed.

However, I think #1355 is probably a better way to do it, so I'll leave this PR unmodified until I need it.

**Comment by deadprogram** [comment]
Closing due to age. Thanks to everyone!

**Pull request closed without merging**
