### PR TITLE
builder: add support for -size= flag for WebAssembly

### PR DESCRIPTION
**Pull request by aykevl**
Look at that! A breakdown of binary file usage per package! For WebAssembly! :grinning: 

```
$ tinygo build -o test.wasm -size=full ./testdata/json.go
   code  rodata    data     bss |   flash     ram | package
------------------------------- | --------------- | -------
  10435       0   15168  103481 |   25603  118649 | (unknown)
   1887       0       0       0 |    1887       0 | bytes
    185       0       0       0 |     185       0 | encoding/base64
  37790       0     256      32 |   38046     288 | encoding/json
     49       0       0       0 |      49       0 | errors
  20926       0       8       0 |   20934       8 | fmt
    463       0       0       0 |     463       0 | internal/bytealg
   2264       0       0       0 |    2264       0 | internal/fmtsort
     25       0       0       0 |      25       0 | internal/reflectlite
    569       0       0       0 |     569       0 | internal/task
   1494       0       0       0 |    1494       0 | main
     65       0       0       0 |      65       0 | math
    348       0      64       0 |     412      64 | math/bits
  14162       0       0       0 |   14162       0 | reflect
  13285       0      12     147 |   13297     159 | runtime
   4780       0       0       0 |    4780       0 | sort
  18676       0   11320       0 |   29996   11320 | strconv
    461       0       0       0 |     461       0 | strings
   2745       0       0       0 |    2745       0 | sync
   9661       0       0      40 |    9661      40 | syscall/js
    900       0     256       0 |    1156     256 | unicode
   2433       0     288       0 |    2721     288 | unicode/utf8
------------------------------- | --------------- | -------
 143603       0   27372  103700 |  170975  131072 | whole program
```

The output still needs some cosmetic changes (like replacing "flash" with something else) but the idea should be clear.

I've forked https://github.com/akupila/go-wasm to fix a bug and add some features that were useful. I can move it over to tinygo-org if that's better.

This PR is still in draft until #2212 is merged.

### CODE REVIEW

**Comment by deadprogram** [comment]
#2212 has now been merged, so this PR should now be unblocked.

**Comment by aykevl** [comment]
This PR needed rather extensive modifications because #2212 was modified quite a bit.

**Review by dgryski — APPROVED** [review]
LGTM and seems to work in testing.

**Comment by deadprogram** [comment]
Thanks @aykevl for adding this and to @dgryski for review/testing.

Now merging.

**Pull request merged**
