### PR TITLE
nix: use LLVM 18 instead of LLVM 17

### PR DESCRIPTION
**Pull request by aykevl**
This should hopefully fix some CI issues we're currently having: https://github.com/tinygo-org/tinygo/issues/4515

### CODE REVIEW

**Review by leongross — COMMENTED** [review]
I do not know a lot about Nix, but if we do changes in the flake, don't we also have to update the [`flake.lock`](https://github.com/tinygo-org/tinygo/blob/release/flake.lock#L32)?

**Comment by aykevl** [comment]
Yes, apparently! I ran `nix develop` locally and it automatically updated flake.lock.

**Comment by aykevl** [comment]
It's still failing, and I don't know why because it works fine on my system:

```
/home/runner/go/bin/tinygo: symbol lookup error: /home/runner/go/bin/tinygo: undefined symbol: LLVMInitializeXtensaTarget, version LLVM_18.1
```

**Comment by leongross** [comment]
Here also the linux wasm tests seem to fail, this has been observed in many recent PRs.

**Comment by deadprogram** [comment]
```
/home/runner/go/bin/tinygo: symbol lookup error: /home/runner/go/bin/tinygo: undefined symbol: LLVMInitializeXtensaTarget, version LLVM_18.1
```

Any nix experts able to help out, please?

**Comment by sylv-io** [comment]
I have tried your PR and have not been able to reproduce the symbol lookup error in the workflow either locally or with [act -w nix-test](https://github.com/nektos/act). Can you re-run the workflow and see if the error persists?

**Comment by deadprogram** [comment]
I just retried the workflow and same error @sylv-io

**Comment by leongross** [comment]
@katexochen do you know what is going on here?

**Comment by sylv-io** [comment]
A rather strange bug indeed. I was able to reproduce this bug and access the binary by [forking tinygo and modifying the workflow](https://github.com/9elements/tinygo/actions/runs/11353913986).

Comparing the resulting binary with ghidra and ghidriff shows that the binary built by nix within the github runner adds support for two additional LLVM targets: M68k and Xtensa.

Here is a decompiler diff:
```diff
 void _cgo_ec38bf0848b9_Cfunc_LLVMInitializeAllTargets(void)
 
 {
   LLVMInitializeAArch64Target();
   LLVMInitializeAMDGPUTarget();
   LLVMInitializeARMTarget();
   LLVMInitializeAVRTarget();
   LLVMInitializeBPFTarget();
   LLVMInitializeHexagonTarget();
   LLVMInitializeLanaiTarget();
   LLVMInitializeLoongArchTarget();
   LLVMInitializeMipsTarget();
   LLVMInitializeMSP430Target();
   LLVMInitializeNVPTXTarget();
   LLVMInitializePowerPCTarget();
   LLVMInitializeRISCVTarget();
   LLVMInitializeSparcTarget();
   LLVMInitializeSystemZTarget();
   LLVMInitializeVETarget();
   LLVMInitializeWebAssemblyTarget();
   LLVMInitializeX86Target();
   LLVMInitializeXCoreTarget();
+  LLVMInitializeM68kTarget();
+  LLVMInitializeXtensaTarget();
   return;
 }
```

IIUC the Xtensa target is not supported by default in libLLVM, causing the runtime symbol lookup error. I cannot explain why this only happens in the GitHub runner, but perhaps this information can help you further.

Here is the full ghidriff report: 
[tinygo.local-tinygo.github.ghidriff.md](https://github.com/user-attachments/files/17385126/tinygo.local-tinygo.github.ghidriff.md)

**Comment by sylv-io** [comment]
@aykevl:

Okay, I understand the problem. tinygo is built using the system llvm headers, but links to the dynamic library provided by nix.

diff /nix/store/8bbp6b9wb0lc4kiv7a6qrljsp8mbp4lf-llvm-18.1.8-dev/include/llvm/Config/Targets.def /usr/include/llvm-18/llvm/Config/Targets.def
```
44a45,46
> LLVM_TARGET(M68k)
> LLVM_TARGET(Xtensa)
```

Removing the llvm system packages fixes the workflow, but this behavior is unintended and we should probably find out why the build is not using the nix header instead. 

Here the workaround:
Commit: https://github.com/9elements/tinygo/commit/531178741120e542eaba2da835b133e660246453
Workflow: https://github.com/9elements/tinygo/actions/runs/11363440497

**Comment by sylv-io** [comment]
In other words, we should fix the flake to use/prioritize the nix header instead. :+1:

**Comment by sylv-io** [comment]
By patching Target.def with an error macro, we can see that [go-llvm](https://github.com/tinygo-org/go-llvm) is accessing the system headers: https://github.com/9elements/tinygo/actions/runs/11364600184/job/31610962741

I assume this is due to the hardcoded cgo flags in `llvm_config_linux_llvm18.go`: https://github.com/tinygo-org/go-llvm/blob/master/llvm_config_linux_llvm18.go#L5

**Comment by aykevl** [comment]
@sylv-io thank you! That is indeed a workaround (CI passes now!)

I'm not sure how this should ideally be fixed: ideally we'd want to keep `go install` working without any special flags. One option would be to use `-idirafter` to add the include directory after all the other directories, so that the Nix LLVM headers get searched first (hopefully!).

**Comment by sylv-io** [comment]
> @sylv-io thank you! That is indeed a workaround (CI passes now!)

np :grin: 

> I'm not sure how this should ideally be fixed: ideally we'd want to keep `go install` working without any special flags. One option would be to use `-idirafter` to add the include directory after all the other directories, so that the Nix LLVM headers get searched first (hopefully!).

Yes, it looks like a difficult problem that probably needs to be addressed in `go-llvm`. Even if we define the correct CGO_CPPFLAGS in the flake shellHooks, the cgo flag CPPFLAGS in `llvm_config_linux_llvm18.go` seems to take precedence...

e.g.
```
export CGO_CPPFLAGS="-I${llvmPackages_18.llvm.dev}/include"
```

[go build -x -a -v output:](https://github.com/9elements/tinygo/actions/runs/11365754126/job/31614621446)
```
[...]
TERM='dumb' CGO_LDFLAGS='"-O2" "-g" "-L/usr/lib/llvm-18/lib" "-lLLVM-18"' /nix/store/j9hk9x78z301jqldfyvw72z24vb992qi-go-1.22.6/share/go/pkg/tool/linux_amd64/cgo -objdir $WORK/b099/ -importpath tinygo.org/x/go-llvm -- -I/nix/store/8bbp6b9wb0lc4kiv7a6qrljsp8mbp4lf-llvm-18.1.8-dev/include -I/usr/include/llvm-18 -I/usr/include/llvm-c-18 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I $WORK/b099/ -O2 -g ./analysis.go ./bitreader.go ./bitwriter.go ./dibuilder.go ./executionengine.go ./ir.go ./irreader.go ./linker.go ./llvm_config_linux_llvm18.go ./passes.go ./support.go ./target.go ./version.go
# tinygo.org/x/go-llvm
In file included from /usr/include/llvm-c-18/llvm-c/Target.h:43,
                 from /usr/include/llvm-c-18/llvm-c/ExecutionEngine.h:23,
                 from ../../../go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20240627184919-3b50c76783a8/executionengine.go:17:
/usr/include/llvm-18/llvm/Config/Targets.def:1:2: error: #error ("nope")
    1 | #error("nope")
      |  ^~~~~
In file included from /usr/include/llvm-c-18/llvm-c/Target.h:47:
/usr/include/llvm-18/llvm/Config/Targets.def:1:2: error: #error ("nope")
    1 | #error("nope")
      |  ^~~~~
In file included from /usr/include/llvm-c-18/llvm-c/Target.h:52:
/usr/include/llvm-18/llvm/Config/Targets.def:1:2: error: #error ("nope")
    1 | #error("nope")
      |  ^~~~~
In file included from /usr/include/llvm-c-18/llvm-c/Target.h:78:
/usr/include/llvm-18/llvm/Config/Targets.def:1:2: error: #error ("nope")
    1 | #error("nope")
      |  ^~~~~
In file included from /usr/include/llvm-c-18/llvm-c/Target.h:87:
/usr/include/llvm-18/llvm/Config/Targets.def:1:2: error: #error ("nope")
    1 | #error("nope")
      |  ^~~~~
In file included from /usr/include/llvm-c-18/llvm-c/Target.h:96:
/usr/include/llvm-18/llvm/Config/Targets.def:1:2: error: #error ("nope")
    1 | #error("nope")
      |  ^~~~~
[...]
```

IIUC: To fix this properly, the cgo flags in `go-llvm` must be generated dynamically, which currently only works with [pkg-config](https://pkg.go.dev/cmd/cgo). Unfortunately, [llvm does not support pkg-config](https://github.com/llvm/llvm-project/issues/9777) and has its own tool for this, `llvm-config --cflags` and `llvm-config --ldflags`, and I don't see a way to integrate it automatically. Apart from using `go generate`, but ["(that) is intended for use by the author of the go package, not its clients."](https://go.dev/blog/generate)

So I'm out of ideas. :/

**Comment by deadprogram** [comment]
This PR at least gets the CI back to passing while the more complete solution is considered.

Now merging, thank you @aykevl and @sylv-io

**Pull request merged**
