### PR TITLE
add rp2040, pico

### PR DESCRIPTION
**Pull request by rythmkraze**
- Adds support for the new Raspberry Pi `Pico` board along with the onboard `rp2040` mcu.
- Contains minimal implementation, only enough to get `examples/blinky1` working
- All of the mcu peripheral setup code is based on the well structured and well documented Raspberry Pi [pico-sdk](https://github.com/raspberrypi/pico-sdk), with little changes to make it idiomatic Go.
- Instead of having all peripheral code in a single package `machine`, I have attempted to split each peripheral into its own package. We can move them all into package `machine` if it doesn't fit well with the current style of organization.

I am not well versed in assembly and linker scripts and not a regular coder either :) Please guide me through the review/correction process. 

Additional Resources:
- [RP2040 Getting Started Page](https://www.raspberrypi.org/documentation/rp2040/getting-started/)
- [Pico Board Datasheet](https://datasheets.raspberrypi.org/pico/pico-datasheet.pdf)
- [RP2040 MCU Datasheet](https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf)

### CODE REVIEW

**Comment by deadprogram** [comment]
> Instead of having all peripheral code in a single package machine, I have attempted to split each peripheral into its own package. We can move them all into package machine if it doesn't fit well with the current style of organization.

I appreciate the sentiment, but perhaps it would be better to just concentrate on the rp2040 itself in this PR, and leave any restructuring for a future PR.

**Comment by deadprogram** [comment]
The file `bs2_default_padded_checksummed.S` should be located under `/targets`. Also perhaps it can be renamed something shorter and more indicative of it being specific to the raspi pico.

**Comment by deadprogram** [comment]
> I am not well versed in assembly and linker scripts and not a regular coder either :)

That makes this contribution even more impressive then!

**Comment by rythmkraze** [comment]
Hi @deadprogram. Just watched your latest streaming episode wherein you referred to this pull request. Thank you for reviewing the code and explaining why we need to adhere to the current style. I will go ahead and restructure/unpackage the files into package `machine`. 

Is it ok if each peripheral got their own file in package `machine`, like `machine_rp2040_clocks.go`, `machine_rp2040_timer.go` etc, or do they all need to go into a single `machine_rp2040.go` file?

FYI: Although it looks like I've done a lot of work, note that almost all of the code/comments for peripherals are directly taken from the pico-sdk. And thanks to @jeffmhastings for his initial work that allowed me to kick start the process and continue from where he left off.

**Comment by rythmkraze** [comment]
Meanwhile can we update our repo https://github.com/tinygo-org/cmsis-svd to include the `rp2040.svd` file from upstream 
https://github.com/posborne/cmsis-svd/commit/f21f49ca0a7ceef61240b40f509cfd3171a6953f and point the `lib/cmsis-svd` submodule to the updated repo? Atleast the CI tests will pass until I fix the folder structure :)

**Comment by deadprogram** [comment]
Hi @rythmkraze 

First of all, thanks for watching! :tv: :smile_cat: 

As far as naming the files `machine_rp2040_clocks.go` etc. we do have some files already named in that way for the stm32 implementation. In this case it is because of code shared between different flavors of stm32. Anyhow, that style of organization seems cool to me.

I have updated the https://github.com/tinygo-org/cmsis-svd fork to be in sync with the upstream repo now, so you should be all good to proceed.

**Comment by deadprogram** [comment]
Note you will need https://github.com/tinygo-org/tinygo/pull/189 in order to get the latest cmsis-svd update.

**Comment by rythmkraze** [comment]
> Note you will need #189 in order to get the latest cmsis-svd update.

Done. Also all peripheral code have been moved to package `machine`

**Comment by deadprogram** [comment]
@rythmkraze this branch needs to be rebased against `dev` now that #1899 has been merged, please. Probably would be good to squash the commits as well. Once that is done I think we should merge, and continue further work from there with additional PRs in the `dev` branch.

**Comment by rythmkraze** [comment]
> @rythmkraze this branch needs to be rebased against `dev` now that #1899 has been merged, please. Probably would be good to squash the commits as well. Once that is done I think we should merge, and continue further work from there with additional PRs in the `dev` branch.

@deadprogram  Done. Rebased against dev and squashed all commits.

**Comment by ysoldak** [comment]
Verified, works for my Pico and Blink.
GJ!

**Comment by deadprogram** [comment]
Tested and appears to work as promised! Thank you @rythmkraze for getting it ready to merge, and thank you @jeffmhastings for gettint so much done to get it started!

Now merging.

**Pull request merged**
