### PR TITLE
cgo: Fix naming of nested anonymous unions

### PR DESCRIPTION
**Pull request by QuLogic**

### CODE REVIEW

**Comment by deadprogram** [comment]
@QuLogic can you please rebase this PR against the latest `llvm16` branch?

@aykevl can you verify that this PR addresses the current build issues on the latest `llvm16` branch so we can look at getting it merged?

Thank you!

**Comment by deadprogram** [comment]
@QuLogic looks like something is failing CI https://github.com/tinygo-org/tinygo/actions/runs/6141079992/job/16660858123?pr=3869#step:17:21

**Comment by QuLogic** [comment]
That's something new that was added to the `llvm16` branch on its last rebase: https://github.com/tinygo-org/tinygo/actions/runs/5931803266/job/16084408715?pr=3741#step:17:21 The CGo error is fixed though.

**Comment by deadprogram** [comment]
@QuLogic this PR is now included in https://github.com/tinygo-org/tinygo/pull/3741 so it can be closed. Thank you very much!!!

**Comment by aykevl** [comment]
@QuLogic thanks a lot for this fix! It saved me quite a bit of digging.

**Pull request closed without merging**
