### PR TITLE
LLVM 17 support

### PR DESCRIPTION
**Pull request by aykevl**
I started working on LLVM 17 support. This is nowhere near close to finished: it looks like we need to switch to the new pass manager API.

### CODE REVIEW

**Comment by deadprogram** [comment]
@aykevl ready for rebase against `dev` please.

**Comment by aykevl** [comment]
Rebased and fixed the merge conflicts.

**Comment by deadprogram** [comment]
Looks like small actual error here https://app.circleci.com/pipelines/github/tinygo-org/tinygo/10049/workflows/17f345fb-36e7-4d80-a264-9256810f016c/jobs/41329?invite=true#step-118-49_123

**Comment by deadprogram** [comment]
@aykevl please see above error.

**Comment by aykevl** [comment]
I'm going to assume it was a stale cache, so I've updated the cache key. Let's see whether it works now.

**Comment by deadprogram** [comment]
Looking good so now merging. Thanks everyone!

**Pull request merged**
