### PR TITLE
Test w/ LLVM assertions in CI

### PR DESCRIPTION
**Pull request by jadr2ddude**

### CODE REVIEW

**Comment by jadr2ddude** [comment]
Alright, this seems to correctly fail.

**Comment by aykevl** [comment]
@jadr2ddude can you rebase on top of the dev branch to make sure it will succeed then?

**Comment by jadr2ddude** [comment]
Ok, CI passes. I think this should be good for now.

**Comment by deadprogram** [comment]
Now that this passes CI for all supported Go versions I am going to merge into `dev`. Thank you @jadr2ddude for another useful contribution!

**Pull request merged**
