### PR TITLE
os/user.Lookup

### PR DESCRIPTION
**Pull request by leongross**
Add support for User lookup via `os/user.Lookup()`

### CODE REVIEW

**Comment by leongross** [comment]
@deadprogram any thoughts on this?

**Comment by leongross** [comment]
@deadprogram do you have any recommendations on what to improve or does this look good to you?

**Comment by leongross** [comment]
@aykevl maybe you can have a short look at this?

**Comment by 10000TB** [comment]
ping for review

**Comment by deadprogram** [comment]
Just waiting for #4027 to land before any more changes to this part of the code.

**Comment by leongross** [comment]
for some reason smoke test `test-llvm15-go118` fails again

**Comment by aykevl** [comment]
> for some reason smoke test `test-llvm15-go118` fails again

That's https://github.com/tinygo-org/tinygo/issues/4206

**Review by aykevl — COMMENTED** [review]
I guess this was mostly copied from upstream Go, correct?
The code looks reasonable, though I would prefer if the test was actually being run (you can add it to GNUmakefile, see `TEST_PACKAGES_FAST` and related variables). Also, what about MacOS/Windows/baremetal support? Does it just fail to compile? I'm worried we might be breaking some existing programs that currently work.

**Comment by leongross** [comment]
Not quite sure why the windows build fails here: `ld.lld: error: undefined symbol: notARealFunction`

**Comment by leongross** [comment]
commit 7b7601d77c681a3c2ce53ce3f89dbdfc35eec492 added stubs, but we should still get this functionality in  @deadprogram

**Comment by leongross** [comment]
@deadprogram

**Comment by leongross** [comment]
Since I did not touch the `rp2040` specific code, it looks like yet another [CI error](https://app.circleci.com/pipelines/github/tinygo-org/tinygo/10922/workflows/0935fd58-de58-4a95-a708-f53b9a8cea68/jobs/43240?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-118-73)

> /go/bin/tinygo build -size short -o test.hex -target=nano-rp2040         examples/rtcinterrupt
unexpected fault address 0x27cc
fatal error: fault
[signal SIGSEGV: segmentation violation code=0xfffffffffffffffa addr=0x27cc pc=0x6e9d62]

**Comment by leongross** [comment]
@deadprogram @aykevl the CI race again, ready to merge?

**Comment by leongross** [comment]
@aykevl @deadprogram @dgryski @10000TB

**Comment by 10000TB** [comment]
anyone with approval power care to approve ?

**Comment by deadprogram** [comment]
@leongross can you please rebase this PR against the latest `dev`? Thanks!

**Comment by leongross** [comment]
@deadprogram rebase done

**Comment by leongross** [comment]
@aykevl

**Comment by 10000TB** [comment]
Looking for an approval ! TY

**Comment by leongross** [comment]
@deadprogram @aykevl

**Review by deadprogram — APPROVED** [review]
Thanks for making the requested changes @leongross I will squash/merge very soon.

**Comment by aykevl** [comment]
Oh sorry I totally forgot about this PR!
@leongross what do you think about #4324? It defers to the Go stdlib for the os/user package by setting the osusergo build tag, which means we have less to maintain in TinyGo.

**Comment by leongross** [comment]
If the `usergo` tag works as I would suspect this should resolve this PR and any further implementations, looks really promising!

**Comment by deadprogram** [comment]
@leongross @aykevl so that means #4324 would replace this PR, correct?

**Comment by deadprogram** [comment]
> @leongross @aykevl so that means https://github.com/tinygo-org/tinygo/pull/4324 would replace this PR, correct?

Just wondering... :smile_cat:

**Comment by leongross** [comment]
> > @leongross @aykevl so that means #4324 would replace this PR, correct?
> 
> Just wondering... 😸

I hope so :) This would be a good generic solution, I cannot think of any use case atm where the implementation covered in this PR would make a difference.

**Comment by leongross** [comment]
#4324 is successfully merged so this can be closed.

**Pull request closed without merging**
