### PR TITLE
nrf: use SPIM peripheral instead of the legacy SPI peripheral

### PR DESCRIPTION
**Pull request by aykevl**
This newer peripheral supports DMA (through EasyDMA) and should generally be faster and more reliable (especially at high speeds). Importantly for some operations: interrupts (within 255 byte buffers) will not interfere with the SPI transfer.

The motivation for this was to be able to control WS2812 LED strips using SPI. Unfortunately it's not possible to fully disable interrupts while the SoftDevice is in use, so WS2812 LEDs would flicker under heavy BLE traffic. The new WS2812-over-SPI code depends on https://github.com/tinygo-org/drivers/pull/208 so will have to wait a bit, but it's able to control 8 LEDs (up to 16, untested) without flickering and without disabling interrupts, which can be useful in some cases.

The nrf51 code is unchanged, only moved around. The nrf52 configuration code has been slightly changed, the main change is the `Transfer` and `Tx` methods.

### CODE REVIEW

**Comment by aykevl** [comment]
@deadprogram it appears that two devices are stuck in TinyHCI.

**Comment by deadprogram** [comment]
TinyHCI fixed.

**Comment by aykevl** [comment]
Thank you!

**Comment by deadprogram** [comment]
Tested on itsybitsy-nrf52840 and works as expected. Thanks @aykevl now merging.

**Pull request merged**
