### PR TITLE
Cgo add cbytes implementation (rebased version of #3318)

### PR DESCRIPTION
**Pull request by leongross**
This PR is a rebased version of PR #3318. It was mentioned in issue [#4284](https://github.com/tinygo-org/tinygo/issues/4284). Rebased seems to have worked flawlessly, all tests/CI passed.

### CODE REVIEW

**Comment by leongross** [comment]
@deadprogram @hectorchu

**Comment by deadprogram** [comment]
@leongross thank you very much for bringing this PR back to life. Thank you @waj334 for originally working on it. Also, thanks @aykevl for the additional help.

**Comment by deadprogram** [comment]
Should we squash commits on this PR, or just rebase it in as separate commits?

**Comment by leongross** [comment]
Since this are quite a lot of commits for such a small change I propose to squash it.

**Comment by deadprogram** [comment]
Thanks everyone! Now squash/merging.

**Pull request merged**
