### PR TITLE
main: Added supporting custom TargetSpec json file via -target flag.

### PR DESCRIPTION
**Pull request by m-chichikalov**
Ok, first PR is always terrible. Any criticism really appreciated. 

Wanted to write unit tests for target.go as well but have questions:
where target_test.go should be put? in root?

### CODE REVIEW

**Comment by justinclift** [comment]
Typo in the PR title? "suctom" :wink:

**Comment by justinclift** [comment]
This seems useful, as it would allow people to use their own custom targets stored separately. :smile:

**Comment by m-chichikalov** [comment]
> This seems useful, as it would allow people to use their own custom targets (still in JSON format) stored separately. 😄

In yaml format would be better, I agree. 😄

**Comment by aykevl** [comment]
Actually, I have been thinking about switching to another format. The main reason I originally chose JSON is that it is included in the standard library, not for any _good_ reasons. YAML is certainly a candidate, but [it also has problems](https://github.com/golang/go/issues/23966#issuecomment-377997161). Maybe ini format or toml?

We could merge this PR (after conflict resolution) - the PR itself looks fine - but remember that we may want to reconsider the format choice. Thus far it has been an internal thing to the compiler, but exporting the format means that people may depend on the specific format and thus we may break people's build when it changes.

**Comment by deadprogram** [comment]
I personally do not think the format matters that much, and JSON is "standard enough". 

The feature in this PR, on the other hand, is for sure needed! :)

Please resolve the conflicts, @m-chichikalov and I will merge.

**Comment by m-chichikalov** [comment]
I will

**Comment by deadprogram** [comment]
Thanks for adding this useful feature @m-chichikalov now merging.

**Pull request merged**
