### PR TITLE
machine/atsamd51: add support for atsamd51 processor/Adafruit ItsyBitsy-M4

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds support for atsamd51 processor using Adafruit ItsyBitsy M4 board.

Before it can be merged, both PR #542 as well as #543 must be merged first, as this PR requires this functionality..

### CODE REVIEW

**Comment by deadprogram** [comment]
#535 needs to land first, that is correct. Now resolving merge conflict...

**Comment by aykevl** [comment]
Can you rebase on dev again?

**Comment by deadprogram** [comment]
OK rebased and tests have now passed.

**Comment by aykevl** [comment]
Great! :tada:

**Pull request merged**
