### PR TITLE
nrf: add SoftDevice support for the Circuit Playground Bluefruit

### PR DESCRIPTION
**Pull request by aykevl**
Untested, therefore this is a draft.

### CODE REVIEW

**Comment by bgould** [comment]
I have a couple of these boards so I'm happy to test it out

**Comment by aykevl** [comment]
Tested and works (after fixing some issues). This is now ready for review.

**Comment by deadprogram** [comment]
Worked as expected, we probably should make the same change for all the Adafruit nRF52840 based boards, since they also should support this.

**Comment by aykevl** [comment]
I added support for the other three boards, of which I was only able to test the ItsyBits nRF52840. It appears that the Bluefruit is the exception here with a bare chip and all other boards use an existing BLE module (and appear to have a low-frequency crystal).

**Comment by deadprogram** [comment]
Thanks, @aykevl very awesome! Now merging.

**Pull request merged**
