### PR TITLE
macos: display SHA256 values used for homebrew packaging

### PR DESCRIPTION
**Pull request by deadprogram**
This PR helps prepare a release of TinyGo for distribution using Homebrew, in two ways:

- Display the SHA256 value that match the release package created as build artifact by CircleCI in the build log.
- create a `make homebrew` task that creates a release build, and then also displays the SHA256 value needed to create the Homebrew brew.

### CODE REVIEW

**Comment by deadprogram** [comment]
Once this PR is merged, on our next release we can include that data in this homebrew formula: https://github.com/tinygo-org/homebrew-tools/blob/feature/tinygo/tinygo.rb making it possible for people to easily install release build on macOS.

**Comment by aykevl** [comment]
We cannot use CircleCI artifacts directly, we have to store them somewhere else (example: GitHub releases). That means we have to download them anyway. And then we can trivially get a sha256sum manually.
In other words, I don't really see how this PR makes packaging easier? We can always add this when it really is easier - I'm just trying to avoid bloat in the Makefile (and there is already a lot of it).

**Comment by deadprogram** [comment]
We should consider removing a few extra tasks. The purpose of this is in part to not have to remember the procedure for releasing a new update to homebrew. If you think not needed, let's close this PR.

**Comment by deadprogram** [comment]
I will instead just update the README in the https://github.com/tinygo-org/homebrew-tools repo to describe how to update the Homebrew formula on release. Seems like a better place.

Closing.

**Pull request closed without merging**
