### PR TITLE
builder: use flock to avoid double-compiles

### PR DESCRIPTION
**Pull request by niaow**
This change uses flock (when available) to acquire locks for build operations.
This allows multiple tinygo processes to run concurrently without building the same thing twice.

### CODE REVIEW

**Comment by niaow** [comment]
This implements #2392

**Comment by deadprogram** [comment]
Looking good to me @niaow 

@aykevl any feedback before I merge?

**Review by sago35 — APPROVED** [review]
Looks good to me.
This change also makes #1355 work correctly.

**Comment by deadprogram** [comment]
Thanks for the improvement @niaow and for the review @sago35 now merging.

**Pull request merged**
