### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by aykevl**

### CODE REVIEW

**Comment by aykevl** [comment]
If you want to test, at least the following is needed:

* LLVM 8, from http://releases.llvm.org/download.html#8.0.1
* Go for Windows, probably 1.12 but 1.13 might also work. Needs to be in your PATH variable.

**Comment by deadprogram** [comment]
I was able to install the `tinygo` executable by downloading/installing Go1.13.1 and LLVM. Both were added to my PATH. I also added the path to the `bin` directory with the `tinygo.exe` file.

I was able to run `tinygo version`.

I then tried to run:

```
tinygo build -o test.uf2 -target circuitplay-express examples/blinky1
```

And received the following output:

```
# unicode/utf8
..\..\..\..\Go\src\unicode\utf8\utf8.go:28:8: expected ';', found b00000000 (and 10 more errors)
```

```

**Comment by aykevl** [comment]
Yes, that is because TinyGo was built with Go 1.12. You could try installing Go 1.12 instead. Building with Go 1.13 might not be difficult but will likely increase CI time (which is already quite long).

**Comment by deadprogram** [comment]
OK that totally worked! 

I was able to build Blinky1 `uf2` file, and then was able to flash it to a Circuit Playground express by dragging/dropping the file using File Explorer.

:shipit:

**Comment by deadprogram** [comment]
Also confirmed does not affect other OS builds, so now merging. A giant leap forward!

**Pull request merged**
