### PR TITLE
tinygo: set cmd.Dir even when running emulators

### LINKED ISSUE #2367: tinygo test -target wasi compress/flate fails because it needs access to multiple directories
With today's dev:

```
$ tinygo test compress/bzip2
ok  	compress/bzip2	0.533s
$ tinygo test -target wasi compress/bzip2
panic: open testdata/e.txt.bz2: file not found
```
Here's the source line that fails:

https://github.com/golang/go/blob/8ff254e30ba9d9c13747fe42213c3f54b47c58e7/src/compress/bzip2/bzip2_test.go#L216

### PR DESCRIPTION
**Pull request by dgryski**
This allows compress/bzip2 to pass with -target=wasi

Fixes #2367

### CODE REVIEW

**Comment by dkegel-fastly** [comment]
LGTM.  Rescues GOOS=windows tinygo test debug/macho , too!

**Comment by niaow** [comment]
Huh. . .  I actually seem to still get an access error:
```
panic: open testdata/e.txt.bz2: errno 2
```

**Comment by niaow** [comment]
This also seems to prevent wasm (js wasm) from even starting at all, since it seems to use a relative path:
```
Error: Cannot find module '/usr/lib/go/src/compress/bzip2/targets/wasm_exec.js'
```

**Comment by dgryski** [comment]
Hmm.. can we use `os.ExpandEnv` to handle constructing the path here?

**Review by aykevl — APPROVED** [review]

**Review by aykevl — DISMISSED** [review]
> This also seems to prevent wasm (js wasm) from even starting at all, since it seems to use a relative path:
> 
> ```
> Error: Cannot find module '/usr/lib/go/src/compress/bzip2/targets/wasm_exec.js'
> ```

You are correct, this is a regression.
The easiest solution may be to use the same `{root}` pattern as is used in CFlags. See for example:
https://github.com/tinygo-org/tinygo/blob/06df31944c6af706d6cb8b30a2e92d19060436d2/targets/nrf51.json#L4-L8

**Comment by dgryski** [comment]
Looks like `{root}` isn't expanded everywhere:

```
Error: Cannot find module '/Users/dgryski/go/src/go.googlesource.com/go/src/compress/bzip2/{root}/targets/wasm_exec.js'
```

Where would be the best place to handle that substitution?

**Comment by niaow** [comment]
It looks like we handle it for `CFLAGS` in `compileopts/config.go` when transforming the config values. It might make sense to put it there as well?

**Comment by dgryski** [comment]
I was starting to look at `compileopts.LoadTarget` where we already do a bit of munging (for the asyncify extra files, for example).  So `{root}` would get replaced at load time.  We might even be able to have that replacement run *only* at Load time and not have to do it individually for the CFlags and LDFlags.

**Comment by dgryski** [comment]
`tinygo test -target=wasm compress/bzip2` seems to be failing because the file stuff seems to be unimplemented.  I've added a patch to replace `{root}` in the emulator line so the test at least runs now (even if it doesn't pass.)

**Comment by dgryski** [comment]
This is ready for review now.

**Review by niaow — APPROVED** [review]

**Comment by aykevl** [comment]
> I was starting to look at `compileopts.LoadTarget` where we already do a bit of munging (for the asyncify extra files, for example). So `{root}` would get replaced at load time. We might even be able to have that replacement run _only_ at Load time and not have to do it individually for the CFlags and LDFlags.

Actually, I was thinking we should do it the other way round. I don't think I wrote this down anywhere, but the way I see it is that `compileopts.Target` is a read-only version of the combined JSON files. We do modify it in `defaultTarget` but that's essentially generating a similar target struct, just without an underlying JSON file (and is not modified after creation).
So:
- `compileopts.Options`: command line options and some related things
- `compileopts.Target`: JSON file, or inferred from the current system (read-only)
- `compileopts.Config`: combines the two and provides the "true" values in methods, see for example `Config.Scheduler()` that prefers the command line option, then the one specified in the target JSON file, and falls back to the coroutines scheduler (sidenote: that one should probably be updated).

Anyway, that is the design as I have it in my mind.

**Comment by dgryski** [comment]
So, should the logic in this PR be moved to `compileopts.Config.Emulator()` ?

**Comment by aykevl** [comment]
That would be most consistent with the rest of the code.

**Pull request merged**
