### PR TITLE
crypto/x509/internal/macos: add package stub to build crypto/x509 on macOS

### PR DESCRIPTION
**Pull request by eliasnaur**
A better solution would be to support linking to the CoreFoundation and Security frameworks, but that was too deep of a rabbit hole for me.

### CODE REVIEW

**Comment by dgryski** [comment]
Does this allow any new packages to pass tests or just build?

**Comment by eliasnaur** [comment]
The `crypto/x509` tests fail to build:

```sh
$ tinygo test crypto/x509
FAIL	crypto/x509	0.000s
# crypto/x509_test
/nix/store/nvaay1c4banbccyvv6ba1gzyqpypjmfq-go-1.23.1/share/go/src/crypto/x509/hybrid_pool_test.go:63:17: c.ConnectionState undefined (type *net.TLSConn has no field or method ConnectionState)
```

**Comment by dgryski** [comment]
This PR allows `crypto/ecdsa` to pass on Mac.

```
~/go/src/github.com/tinygo-org/tinygo $ tinygo test crypto/ecdsa
ok  	crypto/ecdsa	1.890s
~/go/src/github.com/tinygo-org/tinygo $ git checkout dev
M	lib/wasi-libc
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
~/go/src/github.com/tinygo-org/tinygo $ ./build.sh
+ go build -tags=llvm18 -o ./build/tinygo
# github.com/tinygo-org/tinygo
ld: warning: reexported library with install name '/usr/local/opt/llvm@18/lib/libunwind.1.dylib' found at '/usr/local/Cellar/llvm@18/18.1.8/lib/libunwind.1.0.dylib' couldn't be matched with any parent library and will be linked directly
~/go/src/github.com/tinygo-org/tinygo $ tinygo test crypto/ecdsa
FAIL	crypto/ecdsa	0.000s
ld.lld: error: undefined symbol: _crypto/x509/internal/macos.x509_CFStringCreateWithBytes_trampoline
>>> referenced by /<unknown>
>>>               /tmp/lto.tmp:(symbol _crypto/x509/internal/macos$pack.6+0x8)
/Users/dgryski/go/src/go.googlesource.com/go/src/crypto/x509/internal/macos/corefoundation.go:77: linker could not find symbol _crypto/x509/internal/macos.syscall
/Users/dgryski/go/src/go.googlesource.com/go/src/crypto/x509/internal/macos/corefoundation.go:77: linker could not find symbol _internal/abi.FuncPCABI0
```

The `crypto/rsa` and `encoding/pem` packages now build on Mac, but since their tests rely on `testing/quick` the tests fail due to `(reflect.Type).NumOut()` not being supported yet.

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by eliasnaur** [comment]
Thanks, I added `crypto/ecdsa` to the test packages.

**Comment by deadprogram** [comment]
Thanks for the addition @eliasnaur and to @dgryski for review. Now merging.

**Pull request merged**
