### PR TITLE
compiler: avoid zero-sized alloca in channel operations

### PR DESCRIPTION
**Pull request by aykevl**
This works around a bug in LLVM (https://bugs.llvm.org/show_bug.cgi?id=49916) but seems like a good change in general.

Fixes https://github.com/tinygo-org/tinygo/issues/2041.

### CODE REVIEW

**Comment by dgryski** [comment]
Are there any other places that zero-byte structs will be affected with a similar problem?

**Comment by deadprogram** [comment]
@aykevl not sure if you noticed that all of the CI builds are failing: https://app.circleci.com/pipelines/github/tinygo-org/tinygo/5375/workflows/4ce07cea-c635-4dee-8075-6546395e080c/jobs/31173?invite=true#step-117-660

**Comment by aykevl** [comment]
> @aykevl not sure if you noticed that all of the CI builds are failing

Oops, yeah I just read the message from CircleCI. It should e fixed now.

**Comment by aykevl** [comment]
> Are there any other places that zero-byte structs will be affected with a similar problem?

Yes. Some places have a zero sized alloca. This might be the last one remaining:

https://github.com/tinygo-org/tinygo/blob/485a9284e74ea9ff8f0f37f2402ae80448b33f10/compiler/compiler.go#L1533-L1537

If you want to catch them, you can build LLVM using `ASSERTS=1` on the `make` command line (something like `make llvm-build ASSERTS=1`) and then build TinyGo using it.
I'm not sure I'm going to bother fixing this, unless it results in actual bugs: it will be fixed when we upgrade to LLVM 12 anyway. So I'd rather focus now on getting LLVM 12 to work properly (and after that, LLVM 13).

**Comment by deadprogram** [comment]
:no_entry_sign:  :zero: 

Thanks @aykevl now merging.

**Pull request merged**
