### PR TITLE
reflect: move indirect values into interface when setting interfaces

### LINKED ISSUE #4040: reflect: setting an interface value
I have encountered an issue and was able to create a small example to reproduce it. 
When running the code with standard Go, it prints out the value '13', however, with TinyGo, it prints out '35008' instead.

**Env:** `tinygo version 0.30.0 darwin/amd64 (using go version go1.21.0 and LLVM version 16.0.1`

`tinygo run -target=wasi main.go`

```go
package main

import (
	"reflect"
)

func main() {
	var value interface{} = uint16(0)

	// get the pointer to the interface value
	inPtr := reflect.ValueOf(&value)

	// dereference to get the actual value (an interface)
	inElem := inPtr.Elem()

	// create a new value of the same concrete type
	uint16Type := reflect.TypeOf(uint16(0))
	newUint16Value := reflect.New(uint16Type).Elem()
	newUint16Value.Set(reflect.ValueOf(uint16(13)))

	// set the new value to the interface
	inElem.Set(newUint16Value)

	println(value.(uint16))
}
```

### PR DESCRIPTION
**Pull request by dgryski**
Fixes #4040

### CODE REVIEW

**Comment by dgryski** [comment]
Annoying CI failure during `brew install`:
```
==> Pouring python@3.12--3.12.1.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.12
Target /usr/local/bin/2to3-3.12
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.12'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.12

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.12

Possible conflicting files are:
/usr/local/bin/2to3-3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3-3.12
/usr/local/bin/idle3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/idle3.12
/usr/local/bin/pydoc3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/pydoc3.12
/usr/local/bin/python3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12
/usr/local/bin/python3.12-config -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12-config

```

**Comment by dgryski** [comment]
CI issue with `brew` seems to have resolved itself.

**Comment by deadprogram** [comment]
@dgryski please see https://github.com/tinygo-org/tinygo/pull/4046 for my most recent attempt to correct the spurious CI errors on macos.

**Comment by deadprogram** [comment]
@aykevl PTAL

**Review by soypat — APPROVED** [review]
Basing myself on `isIndirect` and `runtime.memcpy` documentation, this change looks correct.

**Comment by deadprogram** [comment]
Thanks for the improvement @dgryski and to @soypat for review. Now merging.

**Pull request merged**
