### PR TITLE
Full Go "net" package port

### PR DESCRIPTION
**Pull request by scottfeldman**
This PR is **WIP** to port the full Go "net" package to TinyGo.

With this PR, I can compile the examples/net examples.  

```
tinygo build -target nano-rp2040 -tags netgo ./examples/net/http-get/
(compiles but doesn't link, see issue #2)
```

(examples/net/http-get imports "net", "net/http", and "crypto/tls", so it's a good test to try and hit everything).

### Notes:

- This PR uses Go's full "net", "net/http", and "crypto/tls" packages, unmodified.
- Need to compile with -tags netgo to pick Go's DNS resolver.
- Can compile all examples/net examples, but ran into a linker issue (see issues below).
- We no longer need the repo/submodule tinygo-org/net.
- None of the network drivers are hooked up; we'll need to redefine the network driver interfaces at the syscall level.
- I've copied in the stock Go src/syscall/ files for linux,arm.  This defines all of the syscall types and data structures for linux,arm.  We can copy in other arch files as needed.  I'm only testing with nano-rp2040.
- There are new files in sys/syscall:
  - src/syscall/env_tinygo.go
  - src/syscall/exec_tinygo.go       // can go away if issue \# 1 is addressed
  - src/syscall/netlink_tinygo.go    // can go away if issue \# 1 is addressed
  - src/syscall/syscall_tinygo.go
- syscall_tinygo.go has the stubbed out syscalls.  These all println("not implemented") and return EOPNOTSUPP.

The idea is this: with the netdev work in the last release, we truncated the "net", "net/http", and "crypto/tls" packages and inserted our own stubs to call into the network wifi drivers.  With this PR, we use the full Go packages, but this time the insertion point is at the syscall level.  Syscall is now where we define the interfaces to the network stack, and the network stack calls into the network drivers.  It makes sense...if we were a full OS, syscall is where we'd have our OS-specific code.

#### Issue \# 1

Import cycle with "sync" package.  Unfortunately, syscall package imports "sync" in some places, which causes an import cycle:

```
package tinygo.org/x/drivers/examples/net/http-get
       imports bytes
       imports io
       imports sync
       imports internal/task
       imports runtime/interrupt
       imports device/arm
       imports syscall
       imports sync: import cycle not allowed
```

(See src/syscall/netlink_linux.go for an example).

I've worked around this issue by stubbing out any imports of "sync", but that's not a workable solution in the long term.  We'll need "sync" in the implementation of the stubbed out syscalls for the network stack and drivers.  So we'll need to revisit "sync" so as to not import "syscall".  Is it possible?

#### Issue \# 2

I can compile examples/net/http-get, but I'm getting a linker failure (I assume):

```
$ tinygo build -target nano-rp2040 -tags netgo -size short ./examples/net/http-get/
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: warning: inline asm clobber list contains reserved registers: R6
Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
ld.lld-17: error: undefined symbol: internal/poll.runtime_pollReset
>>> referenced by fd_poll_runtime.go:68 (/usr/local/go/src/internal/poll/fd_poll_runtime.go:68)
>>>               /home/sfeldma/.cache/tinygo/thinlto/llvmcache-5B61504F573BE00C9410FC761320C8294FA942D7:((*internal/poll.pollDesc).prepare)

ld.lld-17: error: undefined symbol: internal/poll.runtime_pollWait
>>> referenced by fd_poll_runtime.go:84 (/usr/local/go/src/internal/poll/fd_poll_runtime.go:84)
>>>               /home/sfeldma/.cache/tinygo/thinlto/llvmcache-5B61504F573BE00C9410FC761320C8294FA942D7:((*internal/poll.pollDesc).wait)

ld.lld-17: error: undefined symbol: internal/poll.runtime_pollSetDeadline
>>> referenced by fd_poll_runtime.go:161 (/usr/local/go/src/internal/poll/fd_poll_runtime.go:161)
>>>               /home/sfeldma/.cache/tinygo/thinlto/llvmcache-5B61504F573BE00C9410FC761320C8294FA942D7:(internal/poll.setDeadlineImpl)

ld.lld-17: error: undefined symbol: net.useNetdev
>>> referenced by wifinina.go:30 (/home/sfeldma/work/drivers/netlink/probe/wifinina.go:30)
>>>               /home/sfeldma/.cache/tinygo/thinlto/llvmcache-5B61504F573BE00C9410FC761320C8294FA942D7:(main.main)
error: failed to link /tmp/tinygo3877565959/main: exit status 1
```

### CODE REVIEW

**Comment by aykevl** [comment]
I believe the original motivation to not use the full net and net/http packages was because of memory constraints. Has anything changed in that regard?

**Comment by scottfeldman** [comment]
No, I think the concern is still there, and I'm nervous about the final answer.  I'd really like to get the output of -size full for what I have in this PR to see how big the whole enchiladas is.  Pico-W support is the goal, which needs full crypto/tls (no mbedTLS) and builds on top of Patricio's seqs tcp/ip stack, so we kind of need to know the full stack answer.  Will it fit, with enough space left for the app?  It seems targets for networking have >= 2MB flash and >= 256KB SRAM.

**Comment by scottfeldman** [comment]
Will for sure lose networking support for Arduino Nano IoT 33, with only 256KB Flash and 32Kb SRAM.  But even with the current netdev solution, it can only run a few of the examples.

**Comment by scottfeldman** [comment]
I got it...stubbed out some //go:linkname symbols in runtime/netpoll.go and got a full compile with -size full output.

So not too bad...around 1M flash and 60K ram, so that will fit on Pico-W with 2MB flash, 264K ram.

@soypat Now how big is seqs?  The cyw43 driver will add a bit, but not much.

```
$ time tinygo build -target nano-rp2040 -tags netgo -size full ./examples/net/http-get/
   code  rodata    data     bss |   flash     ram | package
------------------------------- | --------------- | -------
      0     507       7      12 |     514      19 | (padding)
  44459       0     552     197 |   45011     749 | (unknown)
    412       0       0       0 |     412       0 | /home/sfeldma/.cache/tinygo/goroot-890902dbc64ed7ad9d2aa4e16b16f7c6fee47c4fbfce9d0aecda1aa4273d5a0b/src/device/arm
      4       0       0       0 |       4       0 | /home/sfeldma/.cache/tinygo/goroot-890902dbc64ed7ad9d2aa4e16b16f7c6fee47c4fbfce9d0aecda1aa4273d5a0b/src/internal/task
    240       0       0       0 |     240       0 | /home/sfeldma/work/tinygo/targets
    420     141       0       0 |     561       0 | /usr/local/go/src/crypto
    106      27       0       0 |     133       0 | /usr/local/go/src/crypto/internal/boring
  44946    2924     100     160 |   47970     260 | /usr/local/go/src/net/http
   5296       0       0       0 |    5296       0 | C compiler-rt
      0     168       0       0 |     168       0 | C interrupt vector
   1232    4256       0       0 |    5488       0 | C picolibc
      0       0       0    2048 |       0    2048 | C stack
   7298       0       0       0 |    7298       0 | Go interface assert
  21654       0       0       0 |   21654       0 | Go interface method
      0   33916       0       0 |   33916       0 | Go types
   2696     225      32       0 |    2953      32 | bufio
   3610     553      16       0 |    4179      16 | bytes
     64       0       0       0 |      64       0 | cmp
   2830     164       0    2088 |    2994    2088 | compress/flate
   1374      42      16       0 |    1432      16 | compress/gzip
    142       0       0       0 |     142       0 | container/list
   3444     222      40       8 |    3706      48 | context
      0     306       0       0 |     306       0 | crypto
   2182    8872       0       0 |   11054       0 | crypto/aes
   3018     562       8       0 |    3588       8 | crypto/cipher
   1856     680     136    2060 |    2672    2196 | crypto/des
   2646     582     238       0 |    3466     238 | crypto/ecdh
   4726     130       8      64 |    4864      72 | crypto/ecdsa
    750      86       0       0 |     836       0 | crypto/ed25519
   6558    2215      48      12 |    8821      60 | crypto/elliptic
    942      76       0       0 |    1018       0 | crypto/hmac
    208       0       0       0 |     208       0 | crypto/internal/alias
   3140     186       0       0 |    3326       0 | crypto/internal/bigmod
      0       8       0       0 |       8       0 | crypto/internal/boring
  20238     273     184    7696 |   20695    7880 | crypto/internal/edwards25519
   4830      46      40      40 |    4916      80 | crypto/internal/edwards25519/field
  13558     526       0     144 |   14084     144 | crypto/internal/nistec
  29368     112       0       0 |   29480       0 | crypto/internal/nistec/fiat
    132       0       0      16 |     132      16 | crypto/internal/randutil
   2672      80       0       0 |    2752       0 | crypto/md5
     16      14       0       0 |      30       0 | crypto/rand
    294      71       0       0 |     365       0 | crypto/rc4
   1556     315     483       0 |    2354     483 | crypto/rsa
   2260      82       0       0 |    2342       0 | crypto/sha1
   2360     363       0       0 |    2723       0 | crypto/sha256
   3288     774       0       0 |    4062       0 | crypto/sha512
    324      38       0       0 |     362       0 | crypto/subtle
  54646    7041    2424     268 |   64111    2692 | crypto/tls
  21184    6464    1408      28 |   29056    1436 | crypto/x509
   2958     105     464       0 |    3527     464 | crypto/x509/pkix
     12       0       0       0 |      12       0 | device/arm
     44       0       0       0 |      44       0 | device/rp
  13076    1666      22       0 |   14764      22 | encoding/asn1
   1030     362       0       0 |    1392       0 | encoding/base64
   1018       0       0       0 |    1018       0 | encoding/binary
    108       0       0       0 |     108       0 | encoding/hex
    818       0      28       0 |     846      28 | encoding/pem
    656     129       8       0 |     793       8 | errors
  10232     224      20       0 |   10476      20 | fmt
    458       0       0      16 |     458      16 | hash/crc32
    870      30       0       0 |     900       0 | internal/bytealg
   1342      21       0       0 |    1363       0 | internal/fmtsort
    384     125       0      24 |     509      24 | internal/godebug
     82     377     864       0 |    1323     864 | internal/godebugs
    592      12      64     120 |     668     184 | internal/intern
    132       1       0       0 |     133       0 | internal/itoa
      0      55      24       0 |      79      24 | internal/oserror
   4840     279      36      12 |    5155      48 | internal/poll
    708       0       0       0 |     708       0 | internal/singleflight
    626       0       0       0 |     626       0 | internal/syscall/unix
    402      48     104       4 |     554     108 | internal/task
   2320      91      60       0 |    2471      60 | io
     70       0       0       0 |      70       0 | io/fs
   1818       3      20      36 |    1841      56 | log
   2234     121       4     322 |    2359     326 | machine
    772      20       8       7 |     800      15 | machine/usb/cdc
      0       0      93       0 |      93      93 | machine/usb/descriptor
    514     114       0       0 |     628       0 | main
    158       0       0       0 |     158       0 | math
  14078     274      20    1308 |   14372    1328 | math/big
  86632       0       0       0 |   86632       0 | math/bits
    568    4868      24       4 |    5460      28 | math/rand
    796       0       0       0 |     796       0 | mime/multipart
    796     136       4       0 |     936       4 | mime/quotedprintable
 102756    1683    1404     745 |  105843    2149 | net
  48126    7542    3006     140 |   58674    3146 | net/http
     40       0       0       0 |      40       0 | net/http/httptrace
   1384     184       9       0 |    1577       9 | net/http/internal
    160       0       0       0 |     160       0 | net/http/internal/ascii
   4464     724       0      24 |    5188      24 | net/netip
   2988     429       2      16 |    3419      18 | net/textproto
   4944     260       0       0 |    5204       0 | net/url
   1462      99      72       0 |    1633      72 | os
  10856    1282      48       0 |   12186      48 | reflect
  11470    1173      24     744 |   12667     768 | runtime
    800       0       0       0 |     800       0 | runtime/volatile
   3858       0       0       0 |    3858       0 | slices
   3422       0       0       0 |    3422       0 | sort
   9458   16054    1354       0 |   26866    1354 | strconv
   4812     296       0       0 |    5108       0 | strings
   1972     299       0       0 |    2271       0 | sync
    966     117       0       1 |    1083       1 | sync/atomic
   1062     346       0       0 |    1408       0 | syscall
  21726    1229     400      88 |   23355     488 | time
      0       0       0       0 |       0       0 | tinygo.org/x/drivers/netdev
      0      65      32       0 |      97      32 | tinygo.org/x/drivers/netlink
     60       0       0       0 |      60       0 | tinygo.org/x/drivers/netlink/probe
   3486     730       0       0 |    4216       0 | tinygo.org/x/drivers/wifinina
    364    7210       0       0 |    7574       0 | unicode
    184       0       0       0 |     184       0 | unicode/utf16
   1822     288       0       0 |    2110       0 | unicode/utf8
   1596     236       0       0 |    1832       0 | vendor/golang.org/x/crypto/chacha20
    704     172       8       0 |     884       8 | vendor/golang.org/x/crypto/chacha20poly1305
   4068     405      20       0 |    4493      20 | vendor/golang.org/x/crypto/cryptobyte
    402      27       0       0 |     429       0 | vendor/golang.org/x/crypto/hkdf
     62       0       0       0 |      62       0 | vendor/golang.org/x/crypto/internal/alias
   1208      87       0       0 |    1295       0 | vendor/golang.org/x/crypto/internal/poly1305
  28624     830     260       0 |   29714     260 | vendor/golang.org/x/net/dns/dnsmessage
    618     383       0       0 |    1001       0 | vendor/golang.org/x/net/http/httpguts
   1236     211     180       0 |    1627     180 | vendor/golang.org/x/net/http/httpproxy
   6390    2115    5088    2256 |   13593    7344 | vendor/golang.org/x/net/http2/hpack
   4332   46835      36      36 |   51203      72 | vendor/golang.org/x/net/idna
    282     304       0       0 |     586       0 | vendor/golang.org/x/text/secure/bidirule
    344   19968       0       0 |   20312       0 | vendor/golang.org/x/text/unicode/bidi
   6122   18380   19450      16 |   43952   19466 | vendor/golang.org/x/text/unicode/norm
------------------------------- | --------------- | -------
 772753  212071   39000   20760 | 1023824   59760 | total

real    1m2.509s
user    1m5.601s
```

**Comment by scottfeldman** [comment]
Here's flash/ram sizes for full port vs. current netdev.  I scaled the flash for pico-W 2MB.  The ram is scaled to 100KB, but pico-w has 264KB.

chart

**Comment by aykevl** [comment]
Oof that's a very large increase!
Maybe a long shot, but perhaps we can investigate what's causing so much flash/RAM bloat and improve things in upstream Go? They don't really care if net/http takes 1MB, but we do. There might be some low hanging fruit.

> Will for sure lose networking support for Arduino Nano IoT 33, with only 256KB Flash and 32Kb SRAM.

Oof that would be unfortunate.

(Personally I'm all for using standard library packages instead of using custom/modified ones, but it would be very unfortunate to lose support for smaller chips).

**Comment by scottfeldman** [comment]
Here's a comparison of net.Dial() vs. tls.Dial() to dig deeper into TLS.  Sorry for the huge charts...will need a big screen to view...See tabs for Flash/RAM charts.

https://docs.google.com/spreadsheets/d/1ACUxfs_MlubyDmhNq2ltNLNv6GBy4OzbSYm05dIRMaQ/edit?usp=sharing

**Comment by scottfeldman** [comment]
Not showing the full chart, but I see 8KB addition for ed25519.

Screenshot 2024-03-13 7 05 37 PM

**Comment by deadprogram** [comment]
@scottfeldman do you want to open a new PR on this or something? Seems like worth putting some more effort into, no? :signal_strength:

**Comment by scottfeldman** [comment]
@deadprogram Yes, minimally, I'll open another PR to preserve the work so far.  I have the code changes backed up.  Made a dumb mistake and deleted the fork this RP was attached to.  Oops.

I would like to see this work thru, but not finding the time.  Will tag-team with anyone interested...  

The direction I was going was: try some of the drivers/examples/net examples to discover which syscalls are actually called by "net" and "crypto/tls" and let that inform the stack/driver interfaces.  This PR terminates all syscalls with a printf, so it should be easy to identify which ones are used.  Once the stack/driver interfaces are defined, we could move the existing netdev drivers work over and also bring in @soypat's seqs/cyw43 stack/driver for Pico W.  That's just kind of how I've been thinking about this, with Pico W support being the ultimate end goal.  There might be other approaches?

I need to invest time in my project (that depends on tinygo 0.32) for a bit longer but then switch back to continue this effort.

**Comment by soypat** [comment]
Heya peeps- small update on the CYW43439+seqs progress. I'm currently trying to reach a standard-library-like API for using the `net` package with an ethernet(link layer) interface. This means getting ARP, DNS, DHCP all working harmoniously- a networking kernel so to say. I've been blessed by being able to work on this at work recently and am getting closer to something usable, to the point it is the only thing I've been doing at work this last week since I need it to get a product up and running. I suspect maybe in the coming weeks I could reach a solid kernel starting point, the current kernel status is at [netif.Engine](https://github.com/soypat/netif/blob/main/engine.go) and is still quite unreliable. 

Worth noting the [httpx](https://github.com/soypat/seqs/tree/main/httpx) library is only 10kB, so probably room for improvement on Go's side. Below are a couple size=full results for the Pico W. All examples seem to be just under 500kB in flash and around 20kB in RAM. Do note that  235kB of flash is a firmware binary for the CYW43439. `seqs` by itself weighs in at ~20kB flash.

<details>

```
pato@qtpi:~/Documents/src/tg/cyw43439$ tinygo build -target=pico -size=full ./examples/http-server/
go: downloading github.com/soypat/seqs v0.0.0-20240509190925-a6350cee83a7
   code  rodata    data     bss |   flash     ram | package
------------------------------- | --------------- | -------
      0     199       5       4 |     204       9 | (padding)
  12902       0      34      28 |   12936      62 | (unknown)
    128       0       0       0 |     128       0 | /home/pato/.cache/tinygo/goroot-7b4e653c98964594b5a4f90248065b822aa0d24caa8e652a285369d6ea0d464f/src/device/arm
      4       0       0       0 |       4       0 | /home/pato/.cache/tinygo/goroot-7b4e653c98964594b5a4f90248065b822aa0d24caa8e652a285369d6ea0d464f/src/internal/task
      0  235073       0       0 |  235073       0 | /home/pato/Documents/src/tg/cyw43439/firmware
    240       0       0       0 |     240       0 | /home/pato/Documents/src/tg/tinygo/targets
   5022       0       0       0 |    5022       0 | C compiler-rt
      0     168       0       0 |     168       0 | C interrupt vector
     80       0       0       0 |      80       0 | C picolibc
      0       0       0    2048 |       0    2048 | C stack
   1576       0       0       0 |    1576       0 | Go interface assert
   3238       0       0       0 |    3238       0 | Go interface method
      0    9780       0       0 |    9780       0 | Go types
    952     126      24       0 |    1102      24 | bufio
    898      69       8       0 |     975       8 | bytes
      0      18       0       0 |      18       0 | context
     12       0       0       0 |      12       0 | device/arm
     36       0       0       0 |      36       0 | device/rp
    328     328       0       0 |     656       0 | encoding/base64
    538      56       0       0 |     594       0 | encoding/binary
     96       0       0       0 |      96       0 | encoding/hex
  15260    1277      20      44 |   16557      64 | encoding/json
     18       0       0       0 |      18       0 | errors
   9844     208      20       0 |   10072      20 | fmt
  13210    2308      96       0 |   15614      96 | github.com/soypat/cyw43439
   1778     392       0       0 |    2170       0 | github.com/soypat/cyw43439/examples/common
   1150    2556     628       0 |    4334     628 | github.com/soypat/cyw43439/whd
   4194     640     291       0 |    5125     291 | github.com/soypat/seqs
   1800     450     868       0 |    3118     868 | github.com/soypat/seqs/eth
    290    1275       0       0 |    1565       0 | github.com/soypat/seqs/eth/dhcp
   7622    1502      64       0 |    9188      64 | github.com/soypat/seqs/httpx
    216      30       0       0 |     246       0 | github.com/soypat/seqs/internal
   9786    1432     176       0 |   11394     176 | github.com/soypat/seqs/stacks
    926     113      28       0 |    1067      28 | github.com/tinygo-org/pio/rp2-pio
   1832     144      24       2 |    2000      26 | github.com/tinygo-org/pio/rp2-pio/piolib
    382       0       0       0 |     382       0 | internal/bytealg
   1380      21       0       0 |    1401       0 | internal/fmtsort
    248      51       0      24 |     299      24 | internal/godebug
     88     468     864       0 |    1420     864 | internal/godebugs
     26      12      24       4 |      62      28 | internal/intern
    132       1       0       0 |     133       0 | internal/itoa
      0      19       8       0 |      27       8 | internal/oserror
    378      48       8       4 |     434      12 | internal/task
      0      87      32       0 |     119      32 | io
     38       0       0       0 |      38       0 | io/fs
    208       0       0      36 |     208      36 | log
  11186     523      20       0 |   11729      20 | log/slog
    286       0      20       0 |     306      20 | log/slog/internal/buffer
   1444     111       0     322 |    1555     322 | machine
    708       0       0       7 |     708       7 | machine/usb/cdc
      0       0      93       0 |      93      93 | machine/usb/descriptor
    896     192    1105       5 |    2193    1110 | main
    494       0       0       0 |     494       0 | math/bits
    790      73       0       0 |     863       0 | net
      0     968       0       0 |     968       0 | net/http
   2462     120       0      24 |    2582      24 | net/netip
    484      54      32       0 |     570      32 | os
   7762     920      48       0 |    8730      48 | reflect
   8250     730      16     736 |    8996     752 | runtime
    928       0       0       0 |     928       0 | runtime/volatile
   5394      18       0       0 |    5412       0 | slices
   3212       0       0       0 |    3212       0 | sort
   9110   16004    1338       0 |   26452    1338 | strconv
    626      64       0       0 |     690       0 | strings
   1378     120       0       0 |    1498       0 | sync
     24       0       0       0 |      24       0 | sync/atomic
    124       6       0       0 |     130       0 | syscall
  14926     842      72      76 |   15840     148 | time
    758    7444   12778       0 |   20980   12778 | unicode
   1410     288       0       0 |    1698       0 | unicode/utf8
------------------------------- | --------------- | -------
 169508  287328   18744    3364 |  475580   22108 | total
pato@qtpi:~/Documents/src/tg/cyw43439$ tinygo build -target=pico -size=full ./examples/http-client/
   code  rodata    data     bss |   flash     ram | package
------------------------------- | --------------- | -------
      0     181       5       4 |     186       9 | (padding)
  13936       0      31      28 |   13967      59 | (unknown)
    138       0       0       0 |     138       0 | /home/pato/.cache/tinygo/goroot-7b4e653c98964594b5a4f90248065b822aa0d24caa8e652a285369d6ea0d464f/src/device/arm
      4       0       0       0 |       4       0 | /home/pato/.cache/tinygo/goroot-7b4e653c98964594b5a4f90248065b822aa0d24caa8e652a285369d6ea0d464f/src/internal/task
      0  235073       0       0 |  235073       0 | /home/pato/Documents/src/tg/cyw43439/firmware
    240       0       0       0 |     240       0 | /home/pato/Documents/src/tg/tinygo/targets
   5022       0       0       0 |    5022       0 | C compiler-rt
      0     168       0       0 |     168       0 | C interrupt vector
     80       0       0       0 |      80       0 | C picolibc
      0       0       0    2048 |       0    2048 | C stack
   1520       0       0       0 |    1520       0 | Go interface assert
   2768       0       0       0 |    2768       0 | Go interface method
      0    9628       0       0 |    9628       0 | Go types
    774      64       8       0 |     846       8 | bytes
      0      18       0       0 |      18       0 | context
     14       0       0       0 |      14       0 | device/arm
     50       0       0       0 |      50       0 | device/rp
    328     328       0       0 |     656       0 | encoding/base64
    528      56       0       0 |     584       0 | encoding/binary
     96       0       0       0 |      96       0 | encoding/hex
  15222    1143      20      44 |   16385      64 | encoding/json
     18       0       0       0 |      18       0 | errors
   9836     222      20       0 |   10078      20 | fmt
  12878    2289      96       0 |   15263      96 | github.com/soypat/cyw43439
   1830     412       0       0 |    2242       0 | github.com/soypat/cyw43439/examples/common
   1150    2556     628       0 |    4334     628 | github.com/soypat/cyw43439/whd
   2368     640     291       0 |    3299     291 | github.com/soypat/seqs
   1784     451     868       0 |    3103     868 | github.com/soypat/seqs/eth
    288    1274       0       0 |    1562       0 | github.com/soypat/seqs/eth/dhcp
    830     107       0       0 |     937       0 | github.com/soypat/seqs/httpx
    156      30       0       0 |     186       0 | github.com/soypat/seqs/internal
   9370    1367     168       0 |   10905     168 | github.com/soypat/seqs/stacks
    978     113      28       0 |    1119      28 | github.com/tinygo-org/pio/rp2-pio
   1750     144      24       2 |    1918      26 | github.com/tinygo-org/pio/rp2-pio/piolib
    336       0       0       0 |     336       0 | internal/bytealg
   1380      21       0       0 |    1401       0 | internal/fmtsort
    428      51       0      24 |     479      24 | internal/godebug
     88     468     864       0 |    1420     864 | internal/godebugs
    602      12      64     120 |     678     184 | internal/intern
    132       0       0       0 |     132       0 | internal/itoa
      0      19       8       0 |      27       8 | internal/oserror
    378      48       8       4 |     434      12 | internal/task
      0      44      24       0 |      68      24 | io
     28       0       0       0 |      28       0 | io/fs
   1576       3      20      36 |    1599      56 | log
  11208     604      40      76 |   11852     116 | log/slog
    316       0      20       0 |     336      20 | log/slog/internal/buffer
   1644     111       0     322 |    1755     322 | machine
    536       0       0       7 |     536       7 | machine/usb/cdc
      0       0      93       0 |      93      93 | machine/usb/descriptor
   1088     275       0       0 |    1363       0 | main
    508       0       0       0 |     508       0 | math/bits
    450    4856       0       0 |    5306       0 | math/rand
    816      72       0       0 |     888       0 | net
   3946     864       0      24 |    4810      24 | net/netip
    214      50      32       0 |     296      32 | os
   7756     915      48       0 |    8719      48 | reflect
   8232     728      16     737 |    8976     753 | runtime
   1042       0       0       0 |    1042       0 | runtime/volatile
   5394      18       0       0 |    5412       0 | slices
   3212       0       0       0 |    3212       0 | sort
   9294   16048    1354       0 |   26696    1354 | strconv
    536      64       0       0 |     600       0 | strings
   1378     120       0       0 |    1498       0 | sync
    108       0       0       0 |     108       0 | sync/atomic
     26       6       0       0 |      32       0 | syscall
  15208     879      72      76 |   16159     148 | time
    758    7444   12778       0 |   20980   12778 | unicode
   1410     288       0       0 |    1698       0 | unicode/utf8
------------------------------- | --------------- | -------
 163984  290272   17628    3552 |  471884   21180 | total       
pato@qtpi:~/Documents/src/tg/cyw43439$ tinygo build -target=pico -size=full ./examples/mqtt/
   code  rodata    data     bss |   flash     ram | package
------------------------------- | --------------- | -------
      0     195       7       4 |     202      11 | (padding)
  14725       0      30      29 |   14755      59 | (unknown)
    128       0       0       0 |     128       0 | /home/pato/.cache/tinygo/goroot-7b4e653c98964594b5a4f90248065b822aa0d24caa8e652a285369d6ea0d464f/src/device/arm
      4       0       0       0 |       4       0 | /home/pato/.cache/tinygo/goroot-7b4e653c98964594b5a4f90248065b822aa0d24caa8e652a285369d6ea0d464f/src/internal/task
      0  235073       0       0 |  235073       0 | /home/pato/Documents/src/tg/cyw43439/firmware
    240       0       0       0 |     240       0 | /home/pato/Documents/src/tg/tinygo/targets
   5022       0       0       0 |    5022       0 | C compiler-rt
      0     168       0       0 |     168       0 | C interrupt vector
     80       0       0       0 |      80       0 | C picolibc
      0       0       0    2048 |       0    2048 | C stack
   1576       0       0       0 |    1576       0 | Go interface assert
   3404       0       0       0 |    3404       0 | Go interface method
      0    9796       0       0 |    9796       0 | Go types
   1218     167      16       0 |    1401      16 | bytes
      0      18       0       0 |      18       0 | context
     12       0       0       0 |      12       0 | device/arm
     36       0       0       0 |      36       0 | device/rp
    328     328       0       0 |     656       0 | encoding/base64
    486      56       0       0 |     542       0 | encoding/binary
     96       0       0       0 |      96       0 | encoding/hex
  15266    1159      20      44 |   16445      64 | encoding/json
    264       0       0       0 |     264       0 | errors
   9856     225      20       0 |   10101      20 | fmt
  12850    2276      96       0 |   15222      96 | github.com/soypat/cyw43439
   1876     412       0       0 |    2288       0 | github.com/soypat/cyw43439/examples/common
   1150    2559     628       0 |    4337     628 | github.com/soypat/cyw43439/whd
   9920    1339      40       0 |   11299      40 | github.com/soypat/natiu-mqtt
   2292     641     291       0 |    3224     291 | github.com/soypat/seqs
   1796     451     868       0 |    3115     868 | github.com/soypat/seqs/eth
    288    1275       0       0 |    1563       0 | github.com/soypat/seqs/eth/dhcp
    216      30       0       0 |     246       0 | github.com/soypat/seqs/internal
   9058    1385     168       0 |   10611     168 | github.com/soypat/seqs/stacks
    958     113      28       0 |    1099      28 | github.com/tinygo-org/pio/rp2-pio
   1820     144      24       2 |    1988      26 | github.com/tinygo-org/pio/rp2-pio/piolib
    336       0       0       0 |     336       0 | internal/bytealg
   1380      21       0       0 |    1401       0 | internal/fmtsort
    248      51       0      24 |     299      24 | internal/godebug
     88     468     864       0 |    1420     864 | internal/godebugs
    564      12      64     120 |     640     184 | internal/intern
    132       1       0       0 |     133       0 | internal/itoa
      0      19       8       0 |      27       8 | internal/oserror
    378      48       8       4 |     434      12 | internal/task
    872      75      60       0 |    1007      60 | io
     28       0       0       0 |      28       0 | io/fs
   1572       3      20      36 |    1595      56 | log
  11236     654      40      76 |   11930     116 | log/slog
    316       0      20       0 |     336      20 | log/slog/internal/buffer
   1500     111       0     322 |    1611     322 | machine
    690       0       0       7 |     690       7 | machine/usb/cdc
      0       0      93       0 |      93      93 | machine/usb/descriptor
   1556     407      43       0 |    2006      43 | main
    494       0       0       0 |     494       0 | math/bits
    374    4856       0       0 |    5230       0 | math/rand
    820      71       0       0 |     891       0 | net
   3926     863       0      24 |    4789      24 | net/netip
    610      59      32       0 |     701      32 | os
   7736     908      48       0 |    8692      48 | reflect
   8194     722      16     736 |    8932     752 | runtime
    936       0       0       0 |     936       0 | runtime/volatile
   5394       0       0       0 |    5394       0 | slices
   3212       0       0       0 |    3212       0 | sort
   9266   16047    1354       0 |   26667    1354 | strconv
    550      64       0       0 |     614       0 | strings
   1378     120       0       0 |    1498       0 | sync
    102       0       0       0 |     102       0 | sync/atomic
     26       6       0       0 |      32       0 | syscall
  15228     845      72      76 |   16145     148 | time
    758    7444   12778       0 |   20980   12778 | unicode
   1410     288       0       0 |    1698       0 | unicode/utf8
------------------------------- | --------------- | -------
 176275  291973   17756    3552 |  486004   21308 | total
 ```
 
 </details>

**Comment by scottfeldman** [comment]
@soypat, nice, thanks for the update and the continued work on seqs.  Question: How much RAM does seqs use at run-time for socket buffers?  Just want to see if everything will fit.

**Pull request closed without merging**
