### PR TITLE
gameboy-advance#3: Add interrupt handler support

### PR DESCRIPTION
**Pull request by kylelemons**

### CODE REVIEW

**Comment by aykevl** [comment]
I think we should take a moment to think how an interrupt API should be made. We could quickly add one now, but an API is much harder to change later than an implementation so I would like to get this right from the beginning if possible.
Here is my proposal: https://github.com/tinygo-org/tinygo/issues/515
There are some issues, but especially the low-level API there should be implementable as-is for the GBA.

--- 

A different issue is that in this PR, the machine package imports the runtime package. In other targets, it's the other way round because the runtime needs to print panic messages to the serial console implemented in the machine package. I would like to keep it just one way, which means dropping the runtime import in the machine package.

**Comment by aykevl** [comment]
But I think I should explain why the interrupt API implemented here has problems:

* It uses an `Interrupts` global variable. I would strongly prefer simple package-level functions: I have never heard of a target that implements multiple interrupt controllers (unless you count the RISC-V core-local and global interrupts which is currently in the process of being overhauled). Using a global only adds unnecessary complexity.
* It expects the interrupt system to know how to enable/disable interrupts. This may be a static list on the GBA, but other systems are far more complex. On Cortex-M, each interrupt can separately be enabled/disabled but within each peripheral interrupt sources can also be enabled/disabled separately. SVD files don't contain this information so it would have to be written for each device manually which is unfeasible.
* Interrupt handlers are function pointers that can be changed at any time. This prevents the interrupt vector from being stored in ROM.

**Comment by kylelemons** [comment]
> But I think I should explain why the interrupt API implemented here has problems:
> 
> * It uses an `Interrupts` global variable. I would strongly prefer simple package-level functions: I have never heard of a target that implements multiple interrupt controllers (unless you count the RISC-V core-local and global interrupts which is currently in the process of being overhauled). Using a global only adds unnecessary complexity.

When you say "package level functions," do you mean something like this?

```
package main

import "unsafe"

//go:export IRQ_FOO
func fooHandler() {

}
```

That certainly feels familiar for embedded code, but it does not feel familiar for Go.  I considered (but haven't really thought through the scheduler implications of) an API more like `os/signal`, but having played around with the current implementation a bit I think being able to pass in user-defined closures at runtime is important for making this feel idiomatic to Go programmers.

> * It expects the interrupt system to know how to enable/disable interrupts.

Perhaps the API that has been defined in the machine package is too high-level.  I don't really have a lot of experience with the other (generated) machine packages.

> This may be a static list on the GBA, but other systems are far more complex. On Cortex-M, each interrupt can separately be enabled/disabled but within each peripheral interrupt sources can also be enabled/disabled separately. SVD files don't contain this information so it would have to be written for each device manually which is unfeasible.

The {register, mask} representation is very convenient for a hand-crafted machine package.  It is also a Go-based transliteration of the (as far as I know) [canonical interrupt reference for the GBA](https://www.coranac.com/tonc/text/interrupts.htm#sec-switch).  I don't know what I would have to write to be in line with the other machine packages, but if it's more repetitive than this, it might also be come a maintainability nightmare.  I don't have enough experience with SVD files to say, but it actually does strike me as the kind of thing that you could generate.  If I understand your description correctly, this is implementing precisely what you describe: there is a master interrupt enable, there are per-device interrupt enables, and there is an interrupt mask.  In order for an interrupt to fire, the CPU has to have interrupts enabled globally, you have to have the peripheral set to fire the interrupt you're interested in, and the interrupt mask must be set to allow that particular interrupt through when it does fire.  While processing the SVD, it seems like you can accumulate the set of these interrupts as you process the peripherals, and then generate your list of register offsets and bitmasks when you're through.

> * Interrupt handlers are function pointers that can be changed at any time. This prevents the interrupt vector from being stored in ROM.

I'm also not sure what the benfit of the interrupt vector being stored in ROM is, so I can't comment on that part.

**Comment by kylelemons** [comment]
@aykevl @deadprogram Any thoughts on the direction you want for interrupts? This PR has some important implications for some of the follow-on ones.

**Comment by deadprogram** [comment]
Closing as discussed in https://github.com/tinygo-org/tinygo/issues/783

**Pull request closed without merging**
