### PR TITLE
Correct Adafruit Clue's volume name to 'CLUEBOOT'

### LINKED ISSUE #1512: targets/clue-alpha: incorrect volume name for UF2 mass storage device (MSD)
```
$ uname -orv
5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 GNU/Linux

$ go version
go version go1.15.2 linux/amd64

$ tinygo version
tinygo version 0.15.0 linux/amd64 (using go version go1.15.2 and LLVM version 10.0.1)

$ ls
go.mod  go.sum  main.go

$ tinygo flash -target=clue_alpha main.go 
error: failed to flash /tmp/tinygo222558420/main.uf2: unable to locate device: FTHR840BOOT
```
Let me know if more context is required. Thank you!

### PR DESCRIPTION
**Pull request by rsjethani**
Closes #1512

### CODE REVIEW

**Comment by aykevl** [comment]
Do you have the CLUE Alpha or the regular CLUE?
It might be that the bootloader name was changed with the switch away from alpha status, so perhaps it would be a good idea to add a new targets/clue.json file specifically for the non-alpha version.

**Comment by rsjethani** [comment]
How do I verify its an ALPHA or otherwise? By going through this [blog post](https://blog.adafruit.com/2020/02/01/new-products-1-29-2020-featuring-adafruit-clue-nrf52840-express-with-bluetoothle-alpha/) and looking at the price difference I would say mine is not ALPHA. I looked closely at the video introduction in the above blog post and I see not difference whatsoever from the device that I have.

**Comment by aykevl** [comment]
You should know from how you purchased it. Did you purchase a CLUE Alpha or just a CLUE?
If you don't have the receipt you can look at when you purchased it, before or after the CLUE went out of the alpha phase.

**Comment by rsjethani** [comment]
Product link: https://shop.pimoroni.com/products/adafruit-clue-nrf52840-express-with-bluetooth-le
So it is Clue and not Clue Alpha.

Then I guess I should be adding clue.json to targets rather than modifying clue-alpha.json!

**Comment by deadprogram** [comment]
Oops just realized I did the same thing in #1549 as this PR. Well, I did also add the alias for a "clue" target.

Now closing. Thanks @rsjethani

**Pull request closed without merging**
