### PR TITLE
Add a note to use --recursive when cloning the TinyGo repo

### PR DESCRIPTION
**Pull request by justinclift**
Some form of info here about needing `--recursive` would be useful, otherwise people can be caught out.

### CODE REVIEW

**Comment by aykevl** [comment]
Sounds good. However, the primary sources are the files in here: https://github.com/tinygo-org/tinygo-site/tree/master/content/getting-started

**Comment by justinclift** [comment]
Good point. :smile:

The Linux instructions there are already ok, as they include:

```
go get -d github.com/tinygo-org/tinygo
cd $GOPATH/src/github.com/tinygo-org/tinygo
dep ensure
```

... which does work.  The text fragment here in BUILDING.md needed the extra push. :wink:

**Comment by justinclift** [comment]
Oops.  This PR was on the wrong branch.  I'll redo it for `dev` as well. :slightly_frowning_face:

**Comment by aykevl** [comment]
Oh no, I should have checked that. I force-pushed (!) the branch to remove the commit and added a protection rule that should hopefully prevent this from happening in the future.

**Comment by aykevl** [comment]
Some people don't use `go get` but use `git clone`, so I think it would be useful to have a note on that page. If you feel like adding it, of course :)

**Pull request merged**
