### PR TITLE
Add os.Getwd() test and extend support to wasi

### PR DESCRIPTION
**Pull request by fgsch**
Follow up from #2077.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @fgsch looks like a CI test fail here https://github.com/tinygo-org/tinygo/runs/4322982377?check_suite_focus=true#step:16:1210

**Comment by fgsch** [comment]
@deadprogram Yup, on it, thank you!

**Comment by dgryski** [comment]
How do I get this to run with `wasmtime` ?  I'm getting

```
    1: unknown import: `env::getcwd` has not been defined
```

**Comment by fgsch** [comment]
@dgryski is your wasi-libc up to date?

**Review by dgryski — APPROVED** [review]
LGTM

Works for me after rm-rf'ing lib/wasi-libc and rebuilding.

**Comment by deadprogram** [comment]
@fgsch do you want to squash these commits so I can merge? Or if you prefer I can do so. Thanks!

**Comment by fgsch** [comment]
@deadprogram Done.

**Comment by deadprogram** [comment]
Thanks @fgsch now merging.

**Pull request merged**
