### PR TITLE
cgo: add support for printf

### PR DESCRIPTION
**Pull request by aykevl**
The C printf function is sometimes needed for C files included using CGo. This PR makes sure they're available on all systems where CGo is fully supported (that is, everywhere except on AVR).

For baremetal systems using picolibc, I've picked the integer-only version of printf to save on flash size. In the future we might want to consider providing a way to pick the floating point version instead, if needed.

### CODE REVIEW

**Comment by aykevl** [comment]
```
--- FAIL: TestBinarySize (0.00s)
    --- FAIL: TestBinarySize/hifive1b/examples/echo (62.79s)
        sizes_test.go:85: Unexpected code size when compiling: -target=hifive1b examples/echo
        sizes_test.go:86:             code rodata   data    bss
        sizes_test.go:87: expected:   4476    280      0   2252
        sizes_test.go:88: actual:     7689    307      0   2252
    --- FAIL: TestBinarySize/microbit/examples/serial (65.76s)
        sizes_test.go:85: Unexpected code size when compiling: -target=microbit examples/serial
        sizes_test.go:86:             code rodata   data    bss
        sizes_test.go:87: expected:   2724    388      8   2256
        sizes_test.go:88: actual:     5824    420      8   2256
    --- FAIL: TestBinarySize/wioterminal/examples/pininterrupt (66.35s)
        sizes_test.go:85: Unexpected code size when compiling: -target=wioterminal examples/pininterrupt
        sizes_test.go:86:             code rodata   data    bss
        sizes_test.go:87: expected:   5996   1484    116   6816
        sizes_test.go:88: actual:     8783   1517    116   6816
```

See, that's why I added this test a while back. This should not have resulted in a code size change, yet it does.

EDIT: this is https://github.com/llvm/llvm-project/issues/52

**Comment by aykevl** [comment]
Found one remaining issue, which appears to be a wasmtime bug: https://github.com/bytecodealliance/wasmtime/issues/7833
EDIT: worked around it for now, using `fflush` (no idea why that works, but it's a temporary workaround until the root cause is found).

**Comment by deadprogram** [comment]
@aykevl there still appears to be some issue with the Windows build on this PR.

**Comment by aykevl** [comment]
> @aykevl there still appears to be some issue with the Windows build on this PR.

Yeah, I think I need to debug this on an actual Windows system.

**Comment by aykevl** [comment]
That CI failure should be fixed now. I just had to fix this one line:

```diff
 		if err != nil {
 			return BuildResult{}, err
 		}
-		unlock()
+		defer unlock()
 		libcDependencies = append(libcDependencies, job)
 		libcDependencies = append(libcDependencies, makeMinGWExtraLibs(tmpdir, config.GOARCH())...)
 	case "":
```

No idea why only this library didn't have the defer while the others did.

**Comment by deadprogram** [comment]
@aykevl can you please resolve the merge conflicts in this PR? Thanks!

**Comment by aykevl** [comment]
Rebased. Let's see how much will break this time.

**Comment by aykevl** [comment]
Ready for review again! The CI error is fixed.

**Comment by deadprogram** [comment]
Thanks for adding/fixing this @aykevl now merging.

**Pull request merged**
