### PR TITLE
Add machine.CPUReset()

### PR DESCRIPTION
**Pull request by scottfeldman**
Add machine.SystemReset() to do a hard reset on device.  Only available for cortexm, currently.

### CODE REVIEW

**Comment by scottfeldman** [comment]
doc link https://github.com/tinygo-org/tinygo-site/pull/337

**Comment by deadprogram** [comment]
@scottfeldman are you also planning on implementing this for any other architectures?

**Comment by scottfeldman** [comment]
@deadprogram not at the momemnt; I don't have any non-arm controllers.

**Comment by deadprogram** [comment]
@scottfeldman will you rename to `CPUReset()` as discussed here?

**Comment by deadprogram** [comment]
Now squashing/merging. Thanks for the addition @scottfeldman

**Pull request merged**
