### PR TITLE
wasm: include wasi-libc

### PR DESCRIPTION
**Pull request by aykevl**
This allows CGo code to call some libc functions.

Fixes part of #844.

### CODE REVIEW

**Comment by aykevl** [comment]
Note: there are no tests yet, because otherwise bare-metal CGo tests would break. I intend to add tests when a bare metal libc has been added.

**Comment by aykevl** [comment]
This PR can be tested with the following patch:

```diff
diff --git a/testdata/cgo/main.go b/testdata/cgo/main.go
index 41bc6892..557dea5c 100644
--- a/testdata/cgo/main.go
+++ b/testdata/cgo/main.go
@@ -4,6 +4,7 @@ package main
 int fortytwo(void);
 #include "main.h"
 int mul(int, int);
+#include <string.h>
 */
 import "C"
 
@@ -109,6 +110,12 @@ func main() {
        var _ C.option3_t = C.option3A
        println("option 2A:", C.option2A)
        println("option 3A:", C.option3A)
+
+       // libc: test whether C functions work at all.
+       buf1 := []byte("foobar\x00")
+       buf2 := make([]byte, len(buf1))
+       C.strcpy((*C.char)(unsafe.Pointer(&buf2[0])), (*C.char)(unsafe.Pointer(&buf1[0])))
+       println("copied string:", string(buf2[:C.strlen((*C.char)(unsafe.Pointer(&buf2[0])))]))
 }
 
 func printUnion(union C.joined_t) C.joined_t {
diff --git a/testdata/cgo/out.txt b/testdata/cgo/out.txt
index 73cb2b99..fcd0ccec 100644
--- a/testdata/cgo/out.txt
+++ b/testdata/cgo/out.txt
@@ -55,3 +55,4 @@ option F: 11
 option G: 12
 option 2A: 20
 option 3A: 21
+copied buffer: foobar
```

**Comment by deadprogram** [comment]
Hmm spoke too soon. Azure build did not succeed. Rerunning just to be sure...

**Comment by deadprogram** [comment]
https://github.com/CraneStation/wasi-libc/issues/46 might be helpful?

**Comment by deadprogram** [comment]
Actually i am thinking it might be the `wasi-libc-sysroot-v0` cache. What do you think?

**Comment by aykevl** [comment]
I suspect the self-test at the end somehow included system headers instead of the ones from wasi.

**Comment by deadprogram** [comment]
If we want to skip those tests at the end, we can run `make finish` instead of just `make` (the default task is `check` which is what is failing there.

**Comment by aykevl** [comment]
Interesting:

```
2020-01-23T16:10:21.4277832Z # Generate a test file that includes all public header files.
2020-01-23T16:10:21.4488191Z cd "D:/a/1/s/lib/wasi-libc/sysroot" && \
2020-01-23T16:10:21.4489227Z for header in $(find include -type f -not -name mman.h |grep -v /bits/); do \
2020-01-23T16:10:21.4489646Z     echo '#include <'$header'>' | sed 's/include\///' ; \
2020-01-23T16:10:21.4490010Z done |LC_ALL=C sort >share/wasm32-wasi/include-all.c ; \
2020-01-23T16:10:21.4490480Z cd - >/dev/null
2020-01-23T16:10:21.4934925Z FIND: Parameter format not correct
2020-01-23T16:10:21.5222246Z # Test that it compiles.
2020-01-23T16:10:21.5386023Z "D:/a/1/s/llvm-build/bin/clang" -O2 -DNDEBUG --target=wasm32-wasi -fno-trapping-math -mthread-model single --sysroot="D:/a/1/s/lib/wasi-libc/sysroot" -fsyntax-only "D:/a/1/s/lib/wasi-libc/sysroot/share/wasm32-wasi/include-all.c" -Wno-\#warnings
```

Especially the `FIND: Parameter format not correct` part.

**Pull request merged**
