### PR TITLE
Setting internal linkage and keeping default visibility for anonymous functions

### PR DESCRIPTION
**Pull request by pkedy**
Resolves issue #3031

/cc: @aykevl

### CODE REVIEW

**Comment by pkedy** [comment]
@aykevl Looks like I found the issue with the generics test failure under Windows. The test originally had `println` and I added 2 occurrences of `fmt.Println`. The two `println` should output before the two `fmt.Println`, but on Windows that is not the case. They output out the other way around. This tells me that TinyGo is handling stdout with Wasm differently on Windows compared to other OSes. It’s a separate issue but wanted to shed light on my findings.

To fix the test, I made replaced the `println` with `fmt.Println`. Now we just need to find a better way to detect generic functions without looking at the symbol name. This is where I could use your help. Worst case scenario, the logic I added seems to work.

Also, could you please retrigger the tests? Looks like the macOS encountered a hiccup.

**Comment by aykevl** [comment]
There is one other way to detect generic functions: by looking at the `Synthetic` field (it starts with something like "instantiation of ..."). I don't really like that method either but I think it's a more reliable method than looking at the symbol name.

**Comment by aykevl** [comment]
> To fix the test, I made replaced the `println` with `fmt.Println`. Now we just need to find a better way to detect generic functions without looking at the symbol name. This is where I could use your help. Worst case scenario, the logic I added seems to work.

While that fixes the problem, I'd much prefer if you'd use `println` everywhere instead of `fmt.Println` because that reduces the compile time for tests. The `fmt` package is rather large (and imports large packages).

**Comment by pkedy** [comment]
> I'd much prefer if you'd use println everywhere instead

✅  I switched to `println`.  

> by looking at the Synthetic field (it starts with something like "instantiation of ...").

I tried this and see that in some cases `Synthetic` has that prefix, however it is empty for in other functions that are detected by the symbol name and thus produces the linker error.

```
error: Linking globals named '(*github.com/tinygo-org/tinygo/testdata/generics/value.mapper[int, int]).Get[int int]$1': symbol multiply defined!
```

**Comment by pkedy** [comment]
@aykevl I tried this and it works and applies to fewer functions:

```golang
if strings.HasSuffix(name, "]$1") {
	b.llvmFn.SetLinkage(llvm.LinkOnceODRLinkage)
}
```

What is the significance of the `$1` suffix? Is this kind of function something we can detect instead?

**Comment by pkedy** [comment]
The `$1` seems to represent the anonymous function inside the generic function. I was able to produce an error for `$2` by adding a second anonymous func.

```golang
func (m *mapper[S, D]) Get(fn1 Callback[D], fn2 Callback[D]) {
	m.v.Get(func(v S) {
		fn1(m.tx(v))
	}, func(v S) {
		fn2(m.tx(v))
	})
}
```

```
error: Linking globals named '(*github.com/tinygo-org/tinygo/testdata/generics/value.mapper[int, int]).Get[int int]$2': symbol multiply defined!
```

**Comment by pkedy** [comment]
@aykevl It looks like this logic might be headed in the right direction.

```golang
// Set linkage to `linkonce_odr` for anonymous functions inside generic functions.
parent := b.fn.Parent()
insideGenericFunc := false
ancestor := parent
// Search ancestors for generic functions.
for ancestor != nil {
	if strings.HasPrefix(ancestor.Synthetic, "instantiation of ") {
		insideGenericFunc = true
		break
	}
	ancestor = ancestor.Parent()
}
// Test if this function is an anonymous function and set `linkonce_odr`.
if insideGenericFunc {
	for _, anonFunc := range parent.AnonFuncs {
		if anonFunc == b.fn {
			b.llvmFn.SetLinkage(llvm.LinkOnceODRLinkage)
			break
		}
	}
}
```

**Comment by aykevl** [comment]
Yes, those are indeed anonymous functions.
I'm now thinking we might want to use internal linkage for _all_ anonymous functions, because they're only called from one function anyway. Internal linkage means that this function does not appear in the symbol table and will be renamed if it is defined more than once (and I believe the duplicates should normally be discarded during optimization).

Also, it might be worth checking what happens if you use an anonymous function inside an anonymous function, it might have a `$1$1` suffix.

**Comment by pkedy** [comment]
Ok. I’ll try that out. I’ve already updated the test the have anonymous functions inside anonymous functions and that works in the logic in my above comment.

**Comment by aykevl** [comment]
Could be as simple as this:

```go
diff --git a/compiler/compiler.go b/compiler/compiler.go
index 1b588d9c..b8ae01f8 100644
--- a/compiler/compiler.go
+++ b/compiler/compiler.go
@@ -1265,6 +1265,7 @@ func (b *builder) createFunction() {
        // Create anonymous functions (closures etc.).
        for _, sub := range b.fn.AnonFuncs {
                b := newBuilder(b.compilerContext, b.Builder, sub)
+               b.llvmFn.SetLinkage(llvm.LinkOnceODRLinkage)
                b.createFunction()
        }
 }
```

(Here I've used `linkonce_odr`, it probably doesn't matter but is more consistent with https://github.com/tinygo-org/tinygo/blob/release/compiler/symbol.go#L199).

**Comment by aykevl** [comment]
Note that when you do this, you need to run `go test ./compiler -update`: a number of compiler tests will change with this change.

**Comment by pkedy** [comment]
I'm happy to report your one line fix works for the tests I added and in my project with the actual use case!

**Comment by pkedy** [comment]
I committed the fix. Many of the `.ll` files in testdata were updated. Please take a look and see if that is expected. Also the `TestAllocs2` test now fails. Looks like this effected memory escaping. Thoughts?

**Review by aykevl — APPROVED** [review]
The code looks good to me.
I do need to look into why the Allocs2 test now fails.

**Comment by aykevl** [comment]
Apparently we should use internal linkage, not `linkonce_odr`. Not sure why though, but with `linkonce_odr` many function attributes are not inferred (including the very important `nocapture`).

**Comment by pkedy** [comment]
`TestAllocs2` does not seem to fail using internal linked. I ran `go test ./compiler -update` to update the expected output and tests are passing for me locally. I'm going to go ahead and make this PR ready for review.

**Comment by pkedy** [comment]
I had to add a check to not set visibility to hidden when the linkage is "local" (internal or private)
otherwise the assertion in `llvm-project/llvm/include/llvm/IR/GlobalValue.h:236` fails:

```c++
  void setVisibility(VisibilityTypes V) {
    assert((!hasLocalLinkage() || V == DefaultVisibility) &&
           "local linkage requires default visibility");
    Visibility = V;
    if (isImplicitDSOLocal())
      setDSOLocal(true);
  }
```

```c++
  bool hasLocalLinkage() const { return isLocalLinkage(getLinkage()); }

  static bool isLocalLinkage(LinkageTypes Linkage) {
    return isInternalLinkage(Linkage) || isPrivateLinkage(Linkage);
  }
```

**Comment by pkedy** [comment]
@aykevl Everything is looking good now. What do you think?

Its great that we went from crazy hack to simple tweak. Thanks for all the helpful hints. Never would have gotten to the solution without them!

Also, please please please can this be released in 0.25.0? :innocent:

**Comment by deadprogram** [comment]
Thank you for working on this @pkedy now merging.

**Pull request merged**
