### PR TITLE
Stubs to make internal/testenv and other test packages work

### PR DESCRIPTION
**Pull request by dgryski**

### CODE REVIEW

**Comment by dgryski** [comment]
Draft PR until we decide which bits to pull in

**Comment by dgryski** [comment]
I'll remove the testenv stub now that `os/exec` stubs are landing.

**Comment by dgryski** [comment]
This is now just the `testing` and `debug` fixes.

**Comment by dgryski** [comment]
Weird CI failure, unrelated to my change.

**Review by aykevl — APPROVED** [review]
Looks good to me, can be merged once the assert-test-linux test passes.

**Pull request merged**
