### PR TITLE
Upgrade WASI version to wasi_snapshot_preview1

### PR DESCRIPTION
**Pull request by fgsch**
Addresses #1647.

### CODE REVIEW

**Comment by aykevl** [comment]
Looks good to me.

**Comment by aykevl** [comment]
But the test is failing, looks like a type issue:

```
# runtime
/home/circleci/project/src/runtime/runtime_wasm_wasi.go:50:39: cannot use int64(d) (value of type int64) as uint64 value in assignment
```

**Comment by fgsch** [comment]
@aykevl thanks. I will fix it and update this space.

**Comment by fgsch** [comment]
@aykevl This should be good now.

**Comment by deadprogram** [comment]
Thanks @fgsch now squash/merging.

**Pull request merged**
