### PR TITLE
os/File: add stubs for os.File Deadlines

### PR DESCRIPTION
**Pull request by leongross**
add `os.SetDeadline`, `os.SetReadDeadline`, `os.SetWriteDeadline` stubs for posix files.

### CODE REVIEW

**Comment by leongross** [comment]
@dgryski @deadprogram @aykevl @archie2x

**Review by deadprogram — APPROVED** [review]
Seems legit overall, but can we add a smoke test?

**Comment by deadprogram** [comment]
Thank you very much @leongross now squash/merging.

**Comment by leongross** [comment]
> Thank you very much @leongross now squash/merging.

Thanks for the fast review and merge @deadprogram !

**Pull request merged**
