### PR TITLE
Add support for linux/386 syscalls.

### PR DESCRIPTION
**Pull request by QuLogic**
This allows `go test` to work when running on a 32-bit machine. I haven't quite figured out how to test it using `GOARCH=386` on a non-32-bit machine though.

### CODE REVIEW

**Comment by aykevl** [comment]
Awesome! It looks right, but CI fails. However, this failure has been fixed in the dev branch. Can you rebase on top of dev and force-push this branch?

**Comment by QuLogic** [comment]
I don't see any CI? But I rebased anyway.

**Comment by deadprogram** [comment]
https://circleci.com/gh/tinygo-org/tinygo/2642 for example.

Seems like it is good, @aykevl can we merge this?

**Comment by aykevl** [comment]
Yes, this looks good. @QuLogic thank you for the addition!

**Comment by QuLogic** [comment]
Is there a reason you don't [enable PR builds](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories) instead of using a `staging` branch for CI? Then results would be posted directly here on the PR status.

**Comment by aykevl** [comment]
The main reason I haven't enabled it is that it would cause a full rebuild of LLVM, which takes over an hour (on two machines, so actually the combined cost is like 2.5h). Pushing directly to the staging branch avoids that. But perhaps it should be enabled anyway. @deadprogram what do you think?

An alternative would be to make a new container that contains the LLVM build we need (avoiding the reliance on CircleCI caching that doesn't seem to work across forks) but that is significantly more hassle and wouldn't work for MacOS anyway.

**Comment by deadprogram** [comment]
We for sure need this, the question is now to implement. Perhaps we should ask CircleCI team support how best to cache this in our build?

**Pull request merged**
