### PR TITLE
fix crash on type assert on empty interface

### PR DESCRIPTION
**Pull request by dgryski**

### CODE REVIEW

**Comment by dgryski** [comment]
Does this look like a better fix to https://github.com/tinygo-org/tinygo/issues/3788 ?

**Comment by dgryski** [comment]
I'll update this PR with the following test:
```
~/go/src/github.com/dgryski/bug/intf $ tinygo-old run main.go
panic: interp: offset out of range

goroutine 52 [running]:
github.com/tinygo-org/tinygo/interp.pointerValue.addOffset(...)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/interp/memory.go:523
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc001284640, 0xc0012c0050, {0xc0012a0590, 0x1, 0x0?}, 0xc0012809f0, {0xc0012ca0a8, 0x8})
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/interp/interpreter.go:427 +0x7865
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc001284640, 0xc0012c0000, {0x0, 0x0, 0x0?}, 0x0, {0x104853bba, 0x4})
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/interp/interpreter.go:526 +0x7ccc
github.com/tinygo-org/tinygo/interp.RunFunc({0xc0032382a0?}, 0xc0012b7ce0?, 0x40?)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/interp/interp.go:237 +0x3a5
github.com/tinygo-org/tinygo/builder.Build.func3(0xc000fc2f00)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/build.go:449 +0xc76
github.com/tinygo-org/tinygo/builder.runJob(0xc000fc2f00, 0x4364657469726568?)
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/jobs.go:222 +0x4d
created by github.com/tinygo-org/tinygo/builder.runJobs in goroutine 1
	/Users/dgryski/go/src/github.com/tinygo-org/tinygo/builder/jobs.go:123 +0x5bd
~/go/src/github.com/dgryski/bug/intf $ tinygo run main.go
x is 5
~/go/src/github.com/dgryski/bug/intf $ cat main.go
package main

func main() {
}

type myint int

func init() {
	if x, ok := any(5).(any); ok {
		println("x is", x.(int))
	}
}
```

**Comment by aykevl** [comment]
This looks like a good fix.
Can you add the test somewhere? For example, to testdata/interface.go.

**Comment by dgryski** [comment]
Test added.

**Comment by deadprogram** [comment]
Thanks for the fix on this @dgryski and to @aykevl for review. Now merging.

**Pull request merged**
