### PR TITLE
runtime: implement interface equality

### PR DESCRIPTION
**Pull request by aykevl**
Improved version of https://github.com/tinygo-org/tinygo/pull/569, fixing a bug and adding/enabling tests.

closes #569

### CODE REVIEW

**Comment by aykevl** [comment]
```
=== RUN   TestCompiler/testdata/channel.go#04
panic: todo: store [recovered]
	panic: todo: store
```

That's a weird error.

**Comment by deadprogram** [comment]
Some difference with Go1.11 it seems? That was at least one problem with the PR #569 I think...

**Comment by aykevl** [comment]
I'm working on a generic fix for `todo: store` that should hopefully also fix the build error here. It's ready, will send a PR any moment now.

**Comment by deadprogram** [comment]
OK #687 was merged so this is ready for rebase.

**Comment by aykevl** [comment]
Rebased.

**Comment by deadprogram** [comment]
:1234: merging.

**Pull request merged**
