### PR TITLE
Allow interrupts for stm32f103xx

### PR DESCRIPTION
**Pull request by tom-horn**
This is a submission for hacktoberfest based on the issue #1214, allowing interrupts to wake up the scheduler for the stm32f103xx microcontroller. If you have any advice I'd appreciate it, it would help with adding the same functionality for the other runtimes.

### CODE REVIEW

**Comment by aykevl** [comment]
CI is failing because src/runtime/runtime_stm32f103xx.go is not formatted. Can you run `go fmt` on it?

**Comment by deadprogram** [comment]
I think you also need to rebase against the `dev` branch to pickup recent commits such as https://github.com/tinygo-org/tinygo/commit/47dc1087e81463d8614b4b7437bbd3c0a489bbbc

**Comment by tom-horn** [comment]
Ok I've rebased onto dev to pick up that circle-ci bug fix, thanks for the tip. All checks passing now.

**Comment by deadprogram** [comment]
Hi @tom-horn seems like this PR has ended up with a bunch of extra merge commits. I would suggest that you open a new pull request by creating a new branch off of the current dev, and then using

```
git cherry-pick fd46d8d
git cherry-pick c6043d2
```

One you have that, push the new branch, and create a new PR using that branch. It should be clean for merge.

Hope that helps!

**Pull request closed without merging**
