### PR TITLE
make spell: add a few missing misspellings, fix format of .csv file

### PR DESCRIPTION
**Pull request by dkegel-fastly**
Also add *.md to the files being checked/fixed.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Review by dkegel-fastly — COMMENTED** [review]
should not be changing src/net

**Comment by dkegel-fastly** [comment]
Removed spurious change from src/net.  Should be ready to land.

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thanks for the improvement @dkegel-fastly and to @dgryski for quick review. Now merging.

**Pull request merged**
