### PR TITLE
machine/stm32f103, stm32f4: Add ADC support

### PR DESCRIPTION
**Pull request by deadprogram**
This is WIP on adding support for ADC on the STM32F4 family of processors.

### CODE REVIEW

**Comment by deadprogram** [comment]
Intended to help address #2297

**Comment by deadprogram** [comment]
Adding STM32F103 aka "Bluepill" to this PR as well.

**Comment by deadprogram** [comment]
Tested on my Adafruit Feather STM32F405 board and worked as expected.

**Review by kenbell — APPROVED** [review]
LGTM

I'm a complete novice on ADC input - but if I understand correctly, this code uses a single ADC in scan mode to scan all analog pins configured for analog input.

It seems like the only true commonality between f4 and f103 is possibly the 'get' function.  I don't think that's worth unifying though.  It looks like it should be able to re-use the f4 implementation for other classes of STM32 in future.

**Comment by deadprogram** [comment]
Thanks for reviewing @kenbell now merging.

**Pull request merged**
