### PR TITLE
Add support for esp32c3 to receive UART data

### PR DESCRIPTION
**Pull request by zdima**
Add interrupt to UART configuration to populate RingBuffer upon data receive.
The code was tested for a few weeks to connect esp32c3 with esp01s.

### CODE REVIEW

**Review by deadprogram — APPROVED** [review]
Looking good to me! I do not have one of these for any actual hardware testing myself.

**Comment by sago35** [comment]
I will check with m5stamp-c3.

**Review by sago35 — APPROVED** [review]
LGTM
I was able to get the example in src/examples/echo to work.

**Comment by deadprogram** [comment]
Thank you @zdima now merging.

**Pull request merged**
