### PR TITLE
machine/rp2040: correct issues with i2c/spi pin validation

### PR DESCRIPTION
**Pull request by deadprogram**
This PR corrects an issue with i2c pin validation introduced in https://github.com/tinygo-org/tinygo/pull/3443

### CODE REVIEW

**Comment by deadprogram** [comment]
Wait, I just looked at the datasheet more closely. I need to change this a little...

**Comment by deadprogram** [comment]
OK @soypat now I think I have corrected it in a way that preserves your original intent.

**Comment by deadprogram** [comment]
Made a second commit to correct error in the SPI pin validation.

Both of these issues were discovered by TinyHCI :robot:

**Comment by deadprogram** [comment]
These are the RP2040 Pico tests that fail until this PR is applied:

image

**Review by soypat — APPROVED** [review]
Thank goodness gracious (and @deadprogram) for TinyHCI!
Looks good to me! Sorry about the faulty PR.

**Comment by deadprogram** [comment]
Thanks for getting things started with the original PR @soypat for for quick review. Now merging.

**Pull request merged**
