### PR TITLE
fix: allow nintendoswitch target to compile

### PR DESCRIPTION
**Pull request by deadprogram**
This PR is to fix the build errors for the `nintendoswitch` target as mentioned in #2530

### CODE REVIEW

**Review by dkegel-fastly — APPROVED** [review]
LGTM

One of these days maybe we should go through all the sources and sort the buildtags into some canonical order...

**Comment by dkegel-fastly** [comment]
Might want to add a note about how timeOffset might be set in the future...?

**Review by aykevl — COMMENTED** [review]
Looks good to me.

Can you add a smoke test (or modify the existing one) to make sure this keeps working? I think all that is needed is a package that imports the os package (even if it's `import _ "os"`).

**Comment by deadprogram** [comment]
> Can you add a smoke test (or modify the existing one) to make sure this keeps working? 

Could you please point me to exactly where I could add this?

**Comment by aykevl** [comment]
Right now we use the following smoketest:

```makefile
	$(TINYGO) build             -o test.nro -target=nintendoswitch      examples/serial
	@$(MD5SUM) test.nro
```

You could add a new Go file (instead of examples/serial) for the Nintendo Switch, or you can use something like ./testdata/stdlib.go (though that might test more than intended and compiling fmt is a bit slow).

**Comment by deadprogram** [comment]
> You could add a new Go file (instead of examples/serial) for the Nintendo Switch, or you can use something like ./testdata/stdlib.go (though that might test more than intended and compiling fmt is a bit slow).

@aykevl instead of either of those, I changed which file is built for the smoketest to be one that includes the `os` package.

**Comment by deadprogram** [comment]
Thanks for the feedback/comments. Now merging.

**Pull request merged**
