### PR TITLE
Release 0.33.0

### PR DESCRIPTION
**Pull request by aykevl**

### CODE REVIEW

**Comment by deadprogram** [comment]
@aykevl do you wish to add some notes to the beginning?

**Comment by aykevl** [comment]
Notes, where?
In the past I've just made a PR with basically no description, because the title is pretty self-explanatory.

If you mean to the release, that happens later when actually drafting the release?

**Review by deadprogram — APPROVED** [review]
:tada:

**Comment by deadprogram** [comment]
Now merging, great work everyone!! :stars:

**Pull request merged**
