### PR TITLE
loader: use ioutil.TempDir to create a temporary directory

### PR DESCRIPTION
**Pull request by aykevl**
... instead of generating one with math/rand. The problem was that
math/rand is deterministic across runs, resulting in a possible race
when trying to create the same directory between two processes.
Additionally, because I used `os.MkdirAll`, no error was reported when
the directory already existed. The solution to this is to use the stdlib
function designed for this: ioutil.TempDir.

### CODE REVIEW

**Comment by deadprogram** [comment]
The CircleCI tests all are failing for same reason:

```
main.go:763: error: stat /home/circleci/.cache/tinygo: no such file or directory
```

**Comment by aykevl** [comment]
I see. That's an actual bug, will fix...

**Comment by aykevl** [comment]
Fixed, this should work now.

**Comment by deadprogram** [comment]
Thanks @aykevl now merging.

**Pull request merged**
