### PR TITLE
chore: fix some comments and typos

### PR DESCRIPTION
**Pull request by knowmost**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @knowmost thank you for submitting a PR.

You appear to have a new account, so welcome to Github. 

I also noticed that you have submitted PRs to several different repos with spelling corrections. What exactly prompted this and also what made you choose these particular repos?

Thanks in advance.

**Comment by knowmost** [comment]
> Hello @knowmost thank you for submitting a PR.
> 
> You appear to have a new account, so welcome to Github.
> 
> I also noticed that you have submitted PRs to several different repos with spelling corrections. What exactly prompted this and also what made you choose these particular repos?
> 
> Thanks in advance.

Thank you for your reply and questions

I just have some mild OCD, hoping to be more perfect. Also, as a beginner, I can only do some simple tasks first (and at the same time, in order to be able to write them on my resume).

Please don't worry about security issues, I don't have such thoughts and abilities, haha

**Comment by paralin** [comment]
Even though it's just typos, they are typos after all! Looks ok

**Comment by deadprogram** [comment]
Looks like that account did not have any other public activity. Also, the PRs to public repos were all within a short period of time in April. It is very odd activity pattern, so I must close this PR. Sorry!

**Pull request closed without merging**
