### PR TITLE
compiler: support pragmas on generic functions

### PR DESCRIPTION
**Pull request by aykevl**
Found this while playing around with some generic code. Luckily the fix is very simple.

### CODE REVIEW

**Comment by dgryski** [comment]
CI failures.

**Comment by aykevl** [comment]
This is very strange. It looks very much like a race condition of some sort.

EDIT 1:This crashes on macOS, sometimes: `go test -short -v -p 1`

EDIT 2: well that's great. It definitely looks like a race, but `-race` doesn't catch it.

**Comment by aykevl** [comment]
Solid reproducer:
```
tinygo clean && tinygo build -o test -p 1 ./testdata/generics.go
```

**Comment by aykevl** [comment]
Took me a few hours to create a solid reproducer, but here it is: https://github.com/golang/go/issues/59427

**Comment by aykevl** [comment]
I think I've fixed the issue. Let's see whether the CI passes this time.

**Comment by aykevl** [comment]
...apparently not. But at least I know how to fix it now.

**Comment by deadprogram** [comment]
Reminder to @aykevl on this PR :smile:

**Comment by aykevl** [comment]
Rebased. Please take another look.
Let's see whether all race conditions have indeed been fixed.

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by dgryski** [comment]
CI passing; does that mean we can merge this?

**Comment by deadprogram** [comment]
I just rebased this branch against the latest `dev` branch to make sure it still passes CI.

**Comment by deadprogram** [comment]
All passing, so now merging. Thank you @aykevl for working on this and to @dgryski for review.

**Pull request merged**
