### PR TITLE
Check for non-static allocas

### PR DESCRIPTION
**Pull request by aykevl**
This PR comes with two commits. The first one might be useful in general (and perhaps be submitted separately). The second one should not be merged now, but only after all non-static allocas are avoided in TinyGo (after at least #773 and #745 have been merged).

### CODE REVIEW

**Comment by aykevl** [comment]
Great, this works now when rebased on top of #773!
Marked as ready for review, even though #773 should me merged first (or you may decide to merge this instead and close #773).

**Comment by deadprogram** [comment]
@aykevl this needs to be rebased again to be merged.

**Comment by aykevl** [comment]
Rebased.

**Comment by deadprogram** [comment]
Can this be merged now?

**Comment by aykevl** [comment]
Yes, done.

**Pull request merged**
