### PR TITLE
machine/lorae5: correct mapping for I2C bus, add pin mapping to enable power

### PR DESCRIPTION
**Pull request by deadprogram**
This PR corrects the lorae5 mapping for the I2C2 bus, and also adds pin mappings to enable power.

### CODE REVIEW

**Comment by deadprogram** [comment]
cc/ @ManoloEvans

**Comment by ManoloEvans** [comment]
when the checks are done can you show me how to install it

**Review by ManoloEvans — APPROVED** [review]
Had an issue with a sensor not working properly due to pin mapping being incorrect. This fixed it.

**Comment by deadprogram** [comment]
Thanks for testing @ManoloEvans now merging.

**Comment by ofauchon** [comment]
Thanks for this contribution @deadprogram @ManoloEvans ;-)

**Pull request merged**
