### PR TITLE
all: release v0.21.0

### PR DESCRIPTION
**Pull request by aykevl**
Still waiting on #2277 which I think is important.

### CODE REVIEW

**Comment by dgryski** [comment]
https://github.com/tinygo-org/tinygo/pull/2255 and https://github.com/tinygo-org/tinygo/pull/2268 seem small and aid quality of life for running tests.

**Comment by aykevl** [comment]
I restarted #2255 to see whether it is a flaky test.
#2268 needs some work to fix the merge conflict, not sure I have the time to do that today.

**Comment by deadprogram** [comment]
Don't forget to update https://github.com/tinygo-org/tinygo/blob/dev/goenv/version.go#L15

**Comment by aykevl** [comment]
Rebased on the dev branch and updated.
Now ready for review/merge.

**Comment by aykevl** [comment]
All regular tests are passing.

**Comment by soypat** [comment]
I'd like to get a word in for https://github.com/tinygo-org/tinygo/pull/2230 (PWM upgrade for the rp2040) since it brings fixes to a buggy implementation and overall upgrades seeing the board is often the first one picked up by newcomers to tinygo

**Comment by deadprogram** [comment]
Amazing work from everyone on this release!

**Pull request merged**
