### PR TITLE
atsame51: add initial support for feather-m4-can

### PR DESCRIPTION
**Pull request by sago35**
Added `feather-m4-can` (atsame51j19) board support.

`feather-m4-can` is almost identical to `feather-m4` .
The differences are as follows

* chip
    * atsamd51j19  ->  atsame51j19
        * D51 = Cortex-M4F + Advanced Feature Set
        * E51 = Cortex-M4F + Advanced Feature Set + 2 x CAN
* board
    * Some of the pins have been changed.
    * USB VID/PID
    * msd-volume-name
    * ...

I plan to create a separate PR to add `CAN` support after this PR is merged.
There are no plans to add `ethernet` support at this time.

### CODE REVIEW

**Comment by sago35** [comment]
* Board
    * Name
        *Adafruit Feather M4 CAN Express
    * Board developer / designer / manufacturer
        * Adafruit 
    * schematic
        * https://learn.adafruit.com/adafruit-feather-m4-can-express/downloads
    * pinout and stuff
        * https://learn.adafruit.com/adafruit-feather-m4-can-express/pinouts
        * https://learn.adafruit.com/adafruit-feather-m4-can-express/downloads
    * URL
        * https://www.adafruit.com/product/4759
    * User manual for the board (if it exists)
        * https://learn.adafruit.com/adafruit-feather-m4-can-express
* Chip
    * chip name
        * ATSAME51J19
    * Clock / ROM / RAM size
        * 120 MHz / 512 KB / 192 KB
    * datasheet URL of the chip
        * https://www.microchip.com/wwwproducts/en/ATSAME51J19A
* URL of the source, such as arduino (if it exists)
    * https://github.com/adafruit/ArduinoCore-samd/tree/master/variants/feather_m4_can

**Comment by sago35** [comment]
```diff
sago3@B450GT3 MINGW64 /c/tinygo/tinygo (feather-m4-can)
$ diff targets/feather-m4.json targets/feather-m4-can.json
2,3c2,3
<     "inherits": ["atsamd51j19a"],
<     "build-tags": ["feather_m4"],
---
>     "inherits": ["atsame51j19a"],
>     "build-tags": ["feather_m4_can"],
6c6
<     "msd-volume-name": "FEATHERBOOT",
---
>     "msd-volume-name": "FTHRCANBOOT",
```

```diff
sago3@B450GT3 MINGW64 /c/tinygo/tinygo (feather-m4-can)
$ diff targets/atsamd51j19a.json targets/atsame51j19a.json
3,4c3,4
<       "build-tags": ["atsamd51j19a", "atsamd51j19", "atsamd51", "sam"],
<       "linkerscript": "targets/atsamd51.ld",
---
>       "build-tags": ["atsame51j19a", "atsame51j19", "atsame51", "atsame5x", "sam"],
>       "linkerscript": "targets/atsame5xx19.ld",
6c6
<               "src/device/sam/atsamd51j19a.s"
---
>               "src/device/sam/atsame51j19a.s"
```

```diff
sago3@B450GT3 MINGW64 /c/tinygo/tinygo (feather-m4-can)
$ diff -s targets/atsamd51.ld targets/atsame5xx19.ld
Files targets/atsamd51.ld and targets/atsame5xx19.ld are identical
```

**Comment by sago35** [comment]
```diff
sago3@B450GT3 MINGW64 /c/tinygo/tinygo (feather-m4-can)
$ diff -s src/machine/machine_atsamd51j19.go src/machine/machine_atsame51j19.go
1c1
< // +build sam,atsamd51,atsamd51j19
---
> // +build sam,atsame51,atsame51j19
3c3
< // Peripheral abstraction layer for the atsamd51.
---
> // Peripheral abstraction layer for the atsame51.
```

```diff
sago3@B450GT3 MINGW64 /c/tinygo/tinygo (feather-m4-can)
$ diff -s src/runtime/runtime_atsamd51j19.go src/runtime/runtime_atsame51j19.go
1c1
< // +build sam,atsamd51,atsamd51j19
---
> // +build sam,atsame51,atsame51j19

```

**Comment by deadprogram** [comment]
Looking good @sago35 thanks for adding this. Now merging.

**Pull request merged**
