### PR TITLE
all: add macOS support

### PR DESCRIPTION
**Pull request by aykevl**
WARNING: this PR depends on https://github.com/tinygo-org/go-llvm/pull/3, and after that one is merged `dep` should be run again to update the branch etc.

This PR adds macOS support, and automatically tests its support in Travis. I needed to disable linux/arm and linux/aarch64 tests in macOS because it tries to use the GNU toolchains, but that support is tested in Linux anyway so there is no big loss.

### CODE REVIEW

**Comment by deadprogram** [comment]
The associated go-llvm PR has been merged, so `dep` can now be run to update this PR.

**Comment by aykevl** [comment]
Rebased and updated the PR, let's see what Travis thinks of it.

**Comment by deadprogram** [comment]
Passed the tests, so I am going to merge.

**Comment by aykevl** [comment]
Great!

**Pull request merged**
