### PR TITLE
add reflect.Type.Key() support

### PR DESCRIPTION
**Pull request by cocotyty**

### CODE REVIEW

**Comment by dankegel** [comment]
Thanks for the patch and for filing https://github.com/tinygo-org/tinygo/issues/2728

As you can see, you have at least one test to adjust still before your pull request goes green; try running

  make test GOTESTFLAGS=-update

or something like that, see compiler/compiler_test.go.

Can you give an example of an open source go project that this benefits?  Maybe we can add it to the test corpus.

**Comment by cocotyty** [comment]
I don't know why [build-windows] always failed.

https://github.com/tinygo-org/tinygo/runs/5688641279?check_suite_focus=true

**Comment by cocotyty** [comment]
> Thanks for the patch and for filing #2728
> 
> As you can see, you have at least one test to adjust still before your pull request goes green; try running
> 
> make test GOTESTFLAGS=-update
> 
> or something like that, see compiler/compiler_test.go.
> 
> Can you give an example of an open source go project that this benefits? Maybe we can add it to the test corpus.



> Thanks for the patch and for filing #2728
> 
> As you can see, you have at least one test to adjust still before your pull request goes green; try running
> 
> make test GOTESTFLAGS=-update
> 
> or something like that, see compiler/compiler_test.go.
> 
> Can you give an example of an open source go project that this benefits? Maybe we can add it to the test corpus.

It will be open source project soonly.
We use tinygo to build a high performance api aggregation gateway.

**Comment by deadprogram** [comment]
This PR needs to be against the `dev` branch. Please see https://tinygo.org/docs/guides/contributing/#how-to-use-our-github-repository

Thank you!

**Comment by deadprogram** [comment]
@cocotyty maybe you want to try to start a new PR based on `dev` that git cherry-pick https://github.com/tinygo-org/tinygo/pull/2734/commits/4b84dfce1944657dc7ac025954f9265a868b3dac

**Comment by johnkeates** [comment]
encoding/json also seems to benefit from this 👍

**Comment by deadprogram** [comment]
@cocotyty thank you very much for working on this code.

I'd like to help you to get this PR reviewed/CI passing.

The simplest way would be to start a new PR off of the latest `dev` branch, and then to git cherry-pick https://github.com/tinygo-org/tinygo/pull/2734/commits/4b84dfce1944657dc7ac025954f9265a868b3dac https://github.com/tinygo-org/tinygo/pull/2734/commits/8342b3a4712368daecb698c3c5448ddb889886d9 and https://github.com/tinygo-org/tinygo/pull/2734/commits/2ade4e7b47b83ac981afdae566a8b82d70f38edf into that branch, then squash the commits together.

You could do the same thing by rebasing `dev` into this current PR, then using`git rebase -i` to clean it up.

Please let us know anything we can do to help. Thanks!

**Comment by cocotyty** [comment]
> 

Thank you ,I will create a new pull request for this feature.

**Pull request closed without merging**
