### PR TITLE
Rewrite goroutines, add support for channels

### PR DESCRIPTION
**Pull request by aykevl**
This PR increases the amount of code, but makes goroutine lowering more independent of the compiler which makes it somewhat easier to maintain.

### CODE REVIEW

**Comment by aykevl** [comment]
Note: I've found at least one bug, so this PR is not ready yet.

**Comment by aykevl** [comment]
I think it is now ready for merging. The bug I mentioned should be fixed, and wasm output that doesn't need a scheduler is the same size as before.

**Comment by deadprogram** [comment]
Please let me know when this feature is ready for testing after whatever further changes are needed.

**Comment by aykevl** [comment]
I think I finally figured out the bug and fixed it, so this PR is ready for review.

**Comment by aykevl** [comment]
@deadprogram can you maybe take a look?

**Comment by deadprogram** [comment]
I was unable to build this version:

```
$ make tgo
go build -o build/tgo -i .
# github.com/aykevl/tinygo/compiler
compiler/llvm.go:46:7: inst.RemoveFromParentAsInstruction undefined (type llvm.Value has no field or method RemoveFromParentAsInstruction)
Makefile:100: recipe for target 'build/tgo' failed
make: *** [build/tgo] Error 2
```

Is there some updated dependency I am missing?

**Comment by aykevl** [comment]
Yes, go-llvm has been updated to add this function.

**Comment by deadprogram** [comment]
Tested with the `blinky2` on the Microbit, and it runs as expected.

Tested on the SAMD21 and it locks each Go routine on the `time.Sleep()` call. Then after some investigation that is also the case on the current `master` branch for SAMD21. I will open a separate issue for that.

**Pull request merged**
