### PR TITLE
Add qtpy-rp2040 to TinyGo v0.25.0

### PR DESCRIPTION
**Pull request by eyz**
Hardware at https://www.adafruit.com/product/4900

### CODE REVIEW

**Comment by sago35** [comment]
* Primary Guide: Adafruit QT Py RP2040 
    * https://learn.adafruit.com/adafruit-qt-py-2040
    * schema : https://learn.adafruit.com/adafruit-qt-py-2040/downloads
    * pinout : https://learn.adafruit.com/adafruit-qt-py-2040/pinouts


Although not directly related to TinyGo, here is the Arduino-core pinout for reference.
https://github.com/earlephilhower/arduino-pico/blob/master/variants/adafruit_qtpy/pins_arduino.h

**Comment by sago35** [comment]
Make sure to create a PR for the dev branch.

Please add a note to README.md in the dev branch.
see: https://github.com/tinygo-org/tinygo/pull/3097/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by eyz** [comment]
- Added `[Adafruit QT Py RP2040](https://www.adafruit.com/product/4900)` in https://github.com/tinygo-org/tinygo/pull/3119/commits/f245a934b10d7779b6bfe58d79e6a885fd1f17c0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R69
- Changed target of PR to tinygo-org:dev

**Comment by sago35** [comment]
@eyz 
It would be helpful if you could rebase against the dev branch.

```
$ git checkout release
$ git fetch <tinygo-org/tinygo's repo>
$ git rebase <tinygo-org/tinygo's repo>/dev
```

If there is no problem, please push.

**Comment by eyz** [comment]
Rebased to tinygo's dev branch, which is the PR destination branch

**Comment by sago35** [comment]
@eyz 
Perhaps my instructions were wrong.
I wanted the following to happen.

https://github.com/tinygo-org/tinygo/tree/pr3119

**Comment by eyz** [comment]
> @eyz Perhaps my instructions were wrong. I wanted the following to happen.
> 
> https://github.com/tinygo-org/tinygo/tree/pr3119

I'll start over

**Pull request closed without merging**
