### PR TITLE
device: update SVD files

### PR DESCRIPTION
**Pull request by aykevl**
This updates lib/cmsis-svd, pulling in the updates to the Espressif SVD files here:
https://github.com/cmsis-svd/cmsis-svd-data/pull/3

This is needed for wifi/BLE support on the ESP32-C3 (the older SVD files were missing some necessary interrupts).

### CODE REVIEW

**Comment by aykevl** [comment]
Huh, looks like this needs some code updates.

This will probably happen after FOSDEM, I've got plenty of stuff to do before then.

**Comment by aykevl** [comment]
Updated the PR to fix ESP32-C3 support.

**Comment by deadprogram** [comment]
@aykevl this can be rebased against `dev` now, if you please.

**Comment by aykevl** [comment]
Rebased on the dev branch.

**Comment by deadprogram** [comment]
Now merging, thanks for the update @aykevl

**Pull request merged**
