### PR TITLE
[pyboard] replaced BUTTON_*_MASK by BUTTON_* to fit the new shifter

### PR DESCRIPTION
**Pull request by conejoninja**
driver

### CODE REVIEW

**Comment by deadprogram** [comment]
It occurs to me that we could leave in the `_MASK` values and just add the `_BUTTON` values. Seems like it would clarify intent, and also not break any existing code.

**Comment by deadprogram** [comment]
Just thinking that some comment about what these values are would be helpful.

**Comment by conejoninja** [comment]
BUTTON_* are now in the shifter driver, are still needed?

**Comment by deadprogram** [comment]
I think you are correct, this can just be closed now.

**Pull request closed without merging**
