### PR TITLE
os: stub out support for os/exec

### PR DESCRIPTION
**Pull request by aykevl**
This is mainly added so that the os/exec package can be imported. The os/exec package is often (indirectly) used in package tests.

### CODE REVIEW

**Comment by dgryski** [comment]
Still fails on my mac:
```
~/go/src/go.googlesource.com/go/src/sort $ ~/go/src/github.com/tinygo-org/tinygo/tinygo test compress/zlib
# os
/Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/os/exec.go:24:17: SysProcAttr not declared by package syscall
/Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/os/env.go:17:17: Environ not declared by package syscall
/Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/os/file_unix.go:120:35: Pipe2 not declared by package syscall
/Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/os/file_unix.go:120:55: O_CLOEXEC not declared by package syscall
```

**Review by dgryski — APPROVED** [review]
LGTM, but doesn't fix builds on Mac.  We need to figure out what's happening with syscalls in general there though.

**Review by dgryski — CHANGES_REQUESTED** [review]
Hmm... I think this actually breaks builds on Macs completely because of the use of SysProcAttr.

Probably don't want to merge this yet.

**Comment by aykevl** [comment]
Working on it.

**Comment by aykevl** [comment]
Let's see whether this works on macOS.

> Probably don't want to merge this yet.

Not going to merge anything that doesn't pass CI so don't worry :)

**Review by dgryski — APPROVED** [review]
Passes locally for me.  Waiting for CI, but optimistic.

**Comment by deadprogram** [comment]
Please resolve merge conflict, @aykevl thanks.

**Comment by deadprogram** [comment]
@aykevl reminder that this has merge conflicts needing to be resolved. Thanks!

**Comment by aykevl** [comment]
Rebased.

**Comment by aykevl** [comment]
Updated, it should now also pass tests on Windows.
I've broadened the scope of the commit a bit to include support for internal/testenv which imports os/exec and os.

**Comment by dgryski** [comment]
For other packages that pass with `internal/testenv`, see https://github.com/tinygo-org/tinygo/pull/2282

**Comment by aykevl** [comment]
Thanks! I've added those packages.

I haven't added the FAILS_IN_CI packages. I think we should investigate why they fail, it's not normal that compiling those packages take up so much RAM or CPU time. (Interestingly, while regexp/syntax is just a very slow interp pass, compress/lzw seems to cause tons of RAM consumption inside the function pass manager - this might be a LLVM bug).

**Comment by dgryski** [comment]
Hmm.. the previous failure was on CircleCI.  Maybe put `compress/lwz` back in now that the stdlib tests are running GitHub ?

**Comment by deadprogram** [comment]
Well, in any case this PR itself seems ready to merge, and has all tests passing. Thanks @aykevl and @dgryski

**Comment by deadprogram** [comment]
Spoke too soon, I probably should have rebased `dev` into this branch first. 

@aykevl Windows CI currently failing here https://github.com/tinygo-org/tinygo/runs/4331176452?check_suite_focus=true#step:14:393

**Comment by deadprogram** [comment]
Ran Windows again, and it passed. I guess it was literally a random failure? :laughing: 

```
--- FAIL: TestCompiler/Host/rand.go (36.23s)
```

**Comment by dgryski** [comment]
That Rand test is definitely flaky. I've had it in fail for me a few times before.

**Pull request merged**
