### PR TITLE
stm32: i2c implementation for F7, L5 and L4 MCUs

### PR DESCRIPTION
**Pull request by kenbell**
Needs sequencing with #1730 (move F103 to common i2c implementation).

I'd suggest merging #1730 first, then I'll update this PR to incorporate those changes.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @kenbell now that #1730 is merged, are there still changes you want to do to this PR?

**Comment by kenbell** [comment]
@deadprogram - I've rebased and fixed up the f103 support, so it should be good to go

**Comment by deadprogram** [comment]
@kenbell now that your other STM32 PR was merged, of course this one has a conflict that needs to be resolved, if you please.

**Comment by kenbell** [comment]
@deadprogram done. I also sneaked in i2c for the L4 series :)

**Comment by deadprogram** [comment]
Thanks for another awesome contribution @kenbell now merging.

**Pull request merged**
