### PR TITLE
runtime: implement resetTimer

### PR DESCRIPTION
**Pull request by joeshaw**
runtime: implement resetTimer

A follow up to #2954 / #1402, which implemented startTimer and stopTimer.

### CODE REVIEW

**Comment by deadprogram** [comment]
Looks like you might need to rebase against the latest `dev` branch?

**Comment by joeshaw** [comment]
It was latest `dev` when I pushed it, but it looks like the return value from `resetTimer` is not consistent. That needs investigating.

**Comment by joeshaw** [comment]
Actually, I think it was just flaky test timing.  Force-pushed an update to hopefully fix that 🤞

**Review by deadprogram — APPROVED** [review]
Thanks for working on this @joeshaw

**Pull request merged**
