### PR TITLE
makefile: Use release built tinygo in Makefile

### PR DESCRIPTION
**Pull request by arbourd**
Closes https://github.com/tinygo-org/tinygo/issues/2795

### CODE REVIEW

**Comment by dgryski** [comment]
Given that we copy the tinygo binary from the build directory to the release directory earlier in the makefile, I'm not sure this patch accomplishes anything.

**Comment by arbourd** [comment]
It's referenced in #2795. If you're like me and are using a LLVM directory that isn't the default, it doesn't know where the headers are. The built "release" binary does, because it's properly copied the headers over in an earlier step.

This solution was suggested by @aykevl: https://github.com/tinygo-org/tinygo/issues/2795#issuecomment-1111179833

**Comment by dgryski** [comment]
Ah, thanks for the background. If this works, then LGTM.

**Comment by aykevl** [comment]
@dgryski the `tinygo` binary locates some directories relative to itself, so yes this changes some things.

**Review by aykevl — APPROVED** [review]

**Comment by deadprogram** [comment]
Thank you for working on this @arbourd and thanks everyone else for reviewing. Now merging.

**Pull request merged**
