### PR TITLE
HiFive1 rev B support

### PR DESCRIPTION
**Pull request by aykevl**
https://wiki.osdev.org/HiFive-1_Bare_Bones

### CODE REVIEW

**Comment by aykevl** [comment]
Things that are needed for this to be mergeable:

 - [ ] https://github.com/posborne/cmsis-svd/pull/72
 - [ ] Interrupts need to be fixed. The `gen-device-svd.py` file assumes that it should create ARM assembly which of course won't work on RISC-V. Also, RISC-V interrupts work slightly different.
 - [ ] Preferably, #184 so that people do not have to build Clang with RISC-V support to use it.

There are more things (like `time.Sleep`/`time.Now` support, GPIO, other peripherals) that have not yet been implemented but they can happen at a later time.

**Comment by deadprogram** [comment]
Regarding the SVD file, I think we should run off our own fork of the cmsis-svd repo anyhow. We should also continue to submit upstream PRs as both you and I have been doing, but this allows us to not have to wait for the other maintainer, who seems somewhat busy.

Regarding the interrupts, and changes to the generator, we need to work on that part.

#184 you know I really want that anyhow. But we can incorporate that later, and continue to use the clang toolchain for now, right?

**Comment by aykevl** [comment]
> #184 you know I really want that anyhow. But we can incorporate that later, and continue to use the clang toolchain for now, right?

Actually no. RISC-V is not included in most LLVM builds so people wouldn't be able to use an external clang, unless they compile LLVM manually.

**Comment by aykevl** [comment]
The upstream SVD file hangs on the fact that the license situation isn't entirely clear and that SiFive doesn't provide SVD files. I have posted here on the forum in the hope that it will help: https://forums.sifive.com/t/svd-file-for-e310-g000/731/11

**Comment by aykevl** [comment]
* switched to our own fork of cmsis-svd
* rebased on top of #439 to avoid problems parsing SVD files
* changed the compiler and linker to be from the `riscv64-unknown-elf-*` toolchain (provided by SiFive). This should be changed in the future, but is likely easier for users than requiring them to build Clang with RISC-V support.

**Comment by aykevl** [comment]
This pull request is now ready to merge.

**Comment by deadprogram** [comment]
I started to test this.

First, I obtained the SiFive GNU tools. Then updated the submodule to get the latest SVD files, and re-ran the generator. SO far, so good.

I then ran into compilation problem:

```
$ tinygo build -size short -o test.elf -target=hifive1b            examples/blinky1
error: No available targets are compatible with triple "riscv32--none"
```

I think that indicates that my LLVM installation lacks the needed risc-v support, right?

**Comment by aykevl** [comment]
You need to rebuild LLVM, and then build it using `make`. This error indicates that you built without RISC-V support. I'm not aware of a LLVM build that includes RISC-V by default.

**Comment by deadprogram** [comment]
Can I just run our own `make llvm-source; make llvm-build` task to achieve this?

**Comment by aykevl** [comment]
Yes, just `make llvm-build` should be enough. But you probably need to remove (or move, to be safe) that directory first.

**Comment by deadprogram** [comment]
Added page at https://github.com/tinygo-org/tinygo/wiki/RISC-V to help anyone who want to experiement with this.

Now merging, great work @aykevl this is a massive step into the future.

**Pull request merged**
