### PR TITLE
Makefile: run smoke tests concurrently

### PR DESCRIPTION
**Pull request by niaow**
This change breaks each smoke test into a separate build rule.
The outputs are saved, and then all printed together at the end.

### CODE REVIEW

**Comment by niaow** [comment]
Before:
```
real    2m19.197s
user    11m51.756s
sys     4m32.056s
```

After:
```
real    0m34.854s
user    21m25.876s
sys     9m13.691s
```

I am pretty sure that the increase in user time on my machine is a result of multiple builds of the same thing running at the same time, which is a problem which still needs to be solved.

**Comment by niaow** [comment]
This is also blocked by #2348

**Comment by niaow** [comment]
I also seem to have forgotten yet again that `build` does not exist consistently in CI.

**Comment by sago35** [comment]
This PR is similar to the following PR.

#1355
#1349

**Comment by niaow** [comment]
Huh. I guess I missed that.

**Comment by niaow** [comment]
Hmm. I might try to rework the cache.

**Comment by aykevl** [comment]
Hmm. I'm not entirely convinced to be honest. The speed improvements are certainly tempting, but it would be unfortunate to lose the ability to specify the build commands as a list of commands. I really like how these commands are very easy to read and modify at the moment.

Perhaps there is a way to get the best of both worlds?

**Pull request closed without merging**
