### PR TITLE
build: another try to handle python unlink/link due to homebrew

### PR DESCRIPTION
**Pull request by deadprogram**
This PR is another try to handle python unlink/link due to homebrew.

### CODE REVIEW

**Comment by deadprogram** [comment]
This PR is a bit less fragile to version change than the previous one.

**Comment by deadprogram** [comment]
Finally working as desired. Took a few tries to get it robust enough. :sweat:

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thanks @dgryski for review now merging.

**Pull request merged**
