### PR TITLE
Draft: `runtime`: MemStats.Alloc/HeapAlloc support

### PR DESCRIPTION
**Pull request by bgould**
https://github.com/tinygo-org/tinygo/issues/742#issuecomment-1411026796

### CODE REVIEW

**Comment by dgryski** [comment]
Probably makes sense to fix some of the garbage collectors to track information for memstats or add comments indicating that we don't.

**Comment by bgould** [comment]
Agreed ... digging into this to understand the scope of the work and see if there is any low hanging fruit to start.

Also thinking it might make sense to break out the reflect stubs into a separate PR since it is not really related to MemStats.

**Comment by bgould** [comment]
Split `reflect` changes into separate PR: https://github.com/tinygo-org/tinygo/pull/3425

**Comment by dgryski** [comment]
Merged as part of #4506

**Pull request closed without merging**
