### PR TITLE
Minor changes to support go 1.17

### PR DESCRIPTION
**Pull request by fgsch**
I came across this while looking at something else. I believe this is needed but I have not tested it.

### CODE REVIEW

**Comment by fgsch** [comment]
cc @mathetake @sago35

**Review by mathetake — APPROVED** [review]

**Review by sago35 — APPROVED** [review]

**Comment by deadprogram** [comment]
Thank you! Now merging.

**Comment by aykevl** [comment]
I do not think this is necessary. A given Go version adds its own version and all previous versions as build tags. So for example, Go 1.16 adds build tags for `go1.1` all the way to `go1.16` (but not `go1.17` of course). So adding a build tag `go1.16` means "Go 1.16 and later".



> I believe this is needed but I have not tested it.

That's why you need to test ;)

**Comment by fgsch** [comment]
Bugger! Thanks for the cluebat @aykevl and feel free to revert this.

**Pull request merged**
