### PR TITLE
machine/samd21: implement Flash interface

### PR DESCRIPTION
**Pull request by deadprogram**
This PR add implementation of the Flash interface for the samd21 processor.

### CODE REVIEW

**Comment by bgould** [comment]
Tried this out using https://github.com/tinygo-org/tinyfs/blob/machine-flash/examples/console/littlefs/machine/main.go and got some strange results ... sort of works but "randomly" fails with filesystem corruption 

```
~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ tinygo flash -target feather-m0 .

~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ winpty python -m serial.tools.miniterm COM18
--- Miniterm on COM18  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

==> format
Successfully formatted LittleFS filesystem.

==> mount
Successfully mounted LittleFS filesystem.

==> write test.txt
hello!wrote 6 bytes to test.txt
==> ls
-rwxrwxrwx     6 test.txt
==> cat test.txt
00000000: 68 65 6c 6c 6f 21                                  hello!
==> write test2.txt
error opening test2.txt: littlefs: File name too long
==> ls
Could not read directory /: littlefs: Corrupted
==>
```

Going to see if I can get this example working using the SPI flash chip on the Feather M0 Express to try to isolate if the above corruption only happens with the NVMC, or if the littlefs library just doesn't work properly with samd21 altogether

**Comment by deadprogram** [comment]
I have a feeling I might know what is happening... checking something.

**Comment by deadprogram** [comment]
@bgould I added the wait check on read, since it could still be writing the data. That would explain your issue. I noticed I had to do this on the SAMD51 code to get it work correctly, which I why I suspect the same is happening for you. Please give a try to this now updated branch.

**Comment by bgould** [comment]
Tried the latest versio of this branch and still seeing similar corruption:

```
$ tinygo clean

~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ tinygo version
tinygo version 0.28.0-dev-67e03f87 windows/amd64 (using go version go1.19.4 and LLVM version 15.0.0)

~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ tinygo flash -target feather-m0 .

~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ winpty python -m serial.tools.miniterm COM18
--- Miniterm on COM18  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

==> format
Successfully formatted LittleFS filesystem.

==> mount
Successfully mounted LittleFS filesystem.

==> ls
==> samples
wrote 90 bytes to file0.txt
error opening file1.txt: littlefs: Corrupted
==> ls
Could not read directory /: littlefs: Corrupted
==>
```

**Comment by deadprogram** [comment]
Perhaps something to do with the padding? Or something else entirely? Can you verify that tinyfs is still working with stm32 or nrf?

**Comment by bgould** [comment]
Confirmed the same program is working on Circuit Playgound Bluefruit (nrf52840)... I can test the littlefs package on the feather board using the regular SPI flash chip that is on this board to see if that is working ...  but I think I need to expose another SPI/sercom in the board definition to do that

Also considering testing out removing the padding logic like you mentioned, as I believe that littlefs is probably (or could be configured to) write in blocks that would already been properly padded. Should have some time today or in the next few to experiment with it.

**Comment by akif999** [comment]
I tried the following and confirmed that it works.

* rev
     * 8940a797b12a73eff112b6770182acf372d2a502
* target
     * Seeed XIAO samd21
* user program
     * https://github.com/tinygo-org/tinygo/blob/samd-flash/src/examples/flash/main.go


```
$ tinygo flash -target=xiao -size=short -monitor .
   code    data     bss |   flash     ram
   8880     116    4632 |    8996    4748
Connected to COM3. Press Ctrl-C to exit.
Flash data start:       0x00004340
Flash data end:         0x00040000
Flash data size, bytes: 244928
Flash write block size: 4
Flash erase block size: 64 Reading data from flash: 1234567887654321123456788765432112345678876543211234567887654321
Writing data to flash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Reading data back from flash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by bgould** [comment]
> Confirmed the same program is working on Circuit Playgound Bluefruit (nrf52840)... I can test the littlefs package on the feather board using the regular SPI flash chip that is on this board to see if that is working ... but I think I need to expose another SPI/sercom in the board definition to do that

Tried the example program using the external SPI flash on my Feather M0 Express and it works ok, so I don't necessarily think the problem is with the littlefs library.  Will do some more experimentation to see if might be related to the padding behavior.

**Comment by deadprogram** [comment]
@bgould I added some error checking that might help you out. Also, I changed the erase block size, I think I had the wrong value possibly?

**Comment by bgould** [comment]
Last update seems to have fixed the issue.  Littlefs working well now.

LGTM

**Review by bgould — APPROVED** [review]

**Comment by deadprogram** [comment]
Thanks for reviewing and testing @bgould and @akif999 now merging.

**Pull request merged**
