### PR TITLE
transform: refactor interrupt lowering

### PR DESCRIPTION
**Pull request by aykevl**
Instead of doing everything in the interrupt lowering pass, generate
some more code in gen-device to declare interrupt handler functions and
do some work in the compiler so that interrupt lowering becomes a lot
simpler.

This has several benefits:

  - Overall code is smaller, in particular the interrupt lowering pass.
  - The code should be a bit less "magical" and instead a bit easier to
    read. In particular, instead of having a magic
    runtime.callInterruptHandler (that is fully written by the interrupt
    lowering pass), the runtime calls a generated function like
    device/sifive.InterruptHandler where this switch already exists in
    code.
  - Debug information is improved. This can be helpful during actual
    debugging but is also useful for other uses of DWARF debug
    information.

For an example on debug information improvement, this is what a
backtrace might look like before this commit:

    Breakpoint 1, 0x00000b46 in UART0_IRQHandler ()
    (gdb) bt
    #0  0x00000b46 in UART0_IRQHandler ()
    #1  <signal handler called>
    [..etc]

Notice that the debugger doesn't see the source code location where it
has stopped.

After this commit, breaking at the same line might look like this:

    Breakpoint 1, (*machine.UART).handleInterrupt (arg1=..., uart=<optimized out>) at /home/ayke/src/github.com/tinygo-org/tinygo/src/machine/machine_nrf.go:200
    200			uart.Receive(byte(nrf.UART0.RXD.Get()))
    (gdb) bt
    #0  (*machine.UART).handleInterrupt (arg1=..., uart=<optimized out>) at /home/ayke/src/github.com/tinygo-org/tinygo/src/machine/machine_nrf.go:200
    #1  UART0_IRQHandler () at /home/ayke/src/github.com/tinygo-org/tinygo/src/device/nrf/nrf51.go:176
    #2  <signal handler called>
    [..etc]

By now, the debugger sees an actual source location for UART0_IRQHandler
(in the generated file) and an inlined function.

### CODE REVIEW

**Comment by aykevl** [comment]
Oops, I need to update the tests.

**Comment by aykevl** [comment]
This PR is now ready for review.
The motivation for this PR is actually #2212. With this PR, the `-size=full` flag increases the number of bytes in the binary that can be attributed to a particular package because interrupt handlers are now correctly counted.

**Comment by deadprogram** [comment]
Any comments from @ardnew @ysoldak @soypat @sago35 or anyone else who is into interrupts?

**Comment by ysoldak** [comment]
Sorry, I'm useless in this code review, but I can test regression on nrf52840 (Nano BLE), AVR (Uno), RP2040 (Nano RP2040) and atsamd21g18a (Nano 33 IoT).

Is this example would be enough to flash on aforementioned boards and try if it still works?
https://github.com/tinygo-org/tinygo/blob/release/src/examples/pininterrupt/pininterrupt.go

**Comment by soypat** [comment]
I'm in pretty much the same spot as Yurii but I can test out on Arduino Uno, Mega and the pico sometime next week

**Comment by sago35** [comment]
I don't have the ability to review the compiler/ and transform/ sources yet either.
All other changes are checked.

**Comment by sago35** [comment]
I think it can be deleted.

https://github.com/tinygo-org/tinygo/blob/afb038e63b8b18d9694e72291e9678d9067fae5c/src/runtime/runtime_k210.go#L157-L159

**Comment by ysoldak** [comment]
Regression tested.

Verified with slightly modified "pininterrupt" example.

Works on:
- Nano 33 BLE (target: nano-33-ble, chip: nrf52840 -> cortex-m4)
- Nano 33 IoT (target: arduino-nano33, chip: atsamd21g18a -> cortex-m0plus)

Does not work on:
- Uno (target: arduino, chip: atmega328p -> avr)
  - no support?
- Nano RP2040 (target: nano-rp2040, chip: rp2040 -> cortex-m0plus)
  - support not merged, see #2215

**Comment by deadprogram** [comment]
Thanks for the reviews, everyone. Now merging.

**Pull request merged**
