### PR TITLE
Add signal stubs

### PR DESCRIPTION
**Pull request by leongross**
To make more u-root commands build using tinygo, add stubs for signaling capabilities.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by leongross** [comment]
@aykevl @deadprogram @scottfeldman

**Comment by deadprogram** [comment]
Thanks for adding this @leongross and thanks @dgryski for review. Now merging.

**Comment by leongross** [comment]
Thanks @deadprogram @dgryski this will come in handy!

**Pull request merged**
