### PR TITLE
avr: add support for `recover()`

### PR DESCRIPTION
**Pull request by aykevl**
You can see that it works with the following command:

    tinygo run -target=simavr ./testdata/recover.go

This also gets the following tests to pass again (which started failing since #2331):

    go test -run=Build -target=simavr -v

Adding support for AVR was a bit more compliated because it's also necessary to save and restore the Y register. That's why the first two commits move things around a bit.

### CODE REVIEW

**Comment by aykevl** [comment]
Pushed a fix for the test failure.

**Comment by deadprogram** [comment]
You are not kidding that it was a bit more complicated. Digesting the changes now. 

Hopefully after this the WebAssembly `recover()` is lot easier.

**Comment by aykevl** [comment]
> Hopefully after this the WebAssembly `recover()` is lot easier.

Unfortunately not, I'm afraid. WebAssembly is a really weird architecture.

**Comment by deadprogram** [comment]
Let's merge it! Thanks @aykevl

**Pull request merged**
