### PR TITLE
Support for the Espressif ESP32-C3-DevKit-RUST-1 development board

### PR DESCRIPTION
**Pull request by inindev**
Signed-off-by: John Clark <inindev@gmail.com>

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @inindev thank you for another board contribution.

Just wondering if the name might be a little too long.

Perhaps just `esp32-c3-devkit-rust-1` would be enough? :thinking:

**Comment by inindev** [comment]
I wondered the same thing, or if I should collapse a couple of dashes such as esp32c3-devkit-rust1 but thought it would break convention to remove the manufacturer name from the front.  I will make your suggested change.

**Comment by inindev** [comment]
I also thought I should update the "Supported boards/targets" of the repo README.md.  Would it be best to put a PR up for this file here or update a different location?

**Comment by inindev** [comment]
renaming complete

**Comment by deadprogram** [comment]
Thank you @inindev now merging.

**Pull request merged**
