### PR TITLE
Implement C.CString, C.GoBytes, etc

### PR DESCRIPTION
**Pull request by aykevl**
This fixes https://github.com/tinygo-org/tinygo/issues/854.

### CODE REVIEW

**Comment by aykevl** [comment]
I think I found a way to improve this PR a bit.

**Comment by deadprogram** [comment]
I would really like to have this for something. Any chance of being ready to land soon? :smile_cat:

**Comment by aykevl** [comment]
I'm a bit happier with it now.

**Comment by deadprogram** [comment]
Likewise, it is a lot easier to follow, and the test coverage is good. Now merging, thanks @aykevl

**Pull request merged**
