### PR TITLE
Add sponsor button to key repositories

### PR DESCRIPTION
**Pull request by conejoninja**
Add the sponsor button linking to open collective in the repository.

Needs to be enable ( https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository )

### CODE REVIEW

**Review by leongross — COMMENTED** [review]
Interestingly the CI for linux fails, although you did not touch this. I have the same issue in https://github.com/tinygo-org/tinygo/pull/4517, so `dev` seems to be broken? Same for `nix-test`.

**Comment by deadprogram** [comment]
The fix for nix is in... or at least for the CI. Please rebase against latest dev.

**Comment by conejoninja** [comment]
done, but now Linux/assert-test-linux fails :/

**Review by leongross — COMMENTED** [review]
```
/usr/bin/ld: ASTContext.cpp:(.text._ZL17DecodeTypeFromStrRPKcRKN5clang10ASTContextERNS3_19GetBuiltinTypeErrorERbb+0x670): undefined reference to `__isoc23_strtoul'
```
It looks to me as if there is still a version mismatch. The linker is unable to find the symbol `__isoc23_strtoul` which I think is defined in [glibc](https://github.com/bminor/glibc/blame/2c1903cbbac0022153a67776f474c221250ad6ed/stdlib/stdlib.h#L252), so it looks like the glibc version is too old.

**Comment by aykevl** [comment]
This PR doesn't change any code, so I'd suggest to just ignore the CI errors.
The CI errors are weird though, if they keep happening I think we should do a new llvm-build (by incrementing the cache key) to see whether that helps. It looks like a version mismatch indeed.

**Review by leongross — APPROVED** [review]
I agree @aykevl. Since we had some trouble in the past few days with the CI, I initially thought we should investigate this while we are debugging the CI. But on other PRs like https://github.com/tinygo-org/tinygo/pull/4517 this could not be observed, so let's get this merged.

**Comment by deadprogram** [comment]
Thank you @conejoninja now merging.

**Pull request merged**
