### PR TITLE
Test with LLVM 12.

### PR DESCRIPTION
**Pull request by QuLogic**
Just a check to see if CI will work; I already tested locally and found it crashed on wasm stuff, so there's still some work to do.

### CODE REVIEW

**Comment by aykevl** [comment]
```
The following additional packages will be installed:
  adwaita-icon-theme at-spi2-core binfmt-support binutils-aarch64-linux-gnu
```

`adwaita-icon-theme`?? Something is odd here. I suspect some packages are pulled in that shouldn't be pulled in (but that may be a problem with the container or Debian, not this PR).

**Comment by QuLogic** [comment]
There are two failures in the transform tests:
* In `maps.ll`, the main difference seems to be that `testUnused` contains two extra `hashmap` lines:
  ```
  %hashmap.value = alloca i32, align 4
  %hashmap.value.bitcast = bitcast i32* %hashmap.value to i8*
   ```
* In `coroutines.ll`, it appears that one of the `arguments` lines has added `nofree nosync`; differences on these lines appear to be ignored for LLVM<10 by `filterIrrelevantIRLines`, but it's been changed again for 12.

There's also the weird issue of not finding `-lclang`, and final abort due to:
```
LLVM ERROR: Cannot select: intrinsic %llvm.coro.size
```
Not sure if that's related to #1653 or some other bug.

**Comment by QuLogic** [comment]
Running `TestHost` localls, I can find that `testdata/channel.go` crashes after the `deadlocking` printout, which seems consistent with the WASI results, which seem to have trapped:
```
    0: failed to invoke command default
    1: wasm trap: unreachable
       wasm backtrace:
           0: 0x4258 - <unknown>!main.selectDeadlock
           1: 0x34f7 - <unknown>!main.main.resume
           2: 0x2517 - <unknown>!_start
       note: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information
```

I believe the `%llvm.coro.size` abort comes from the `testdata/json.go` file.

**Comment by aykevl** [comment]
I've made an issue over at the Xtensa fork so they will hopefully update their fork (which we use for ESP32 support): https://github.com/espressif/llvm-project/issues/46

**Comment by aykevl** [comment]
It appears there were some changes to coroutines in LLVM 12. The following code leads to a crash:

```go
package main

func main() {
	go selectDeadlock()
}

func selectDeadlock() {
	println("deadlocking")
	select {}
	println("unreachable")
}
```

**Comment by QuLogic** [comment]
Any ideas on finishing this? We're almost at LLVM 13 time now.

**Comment by aykevl** [comment]
I've made the `llvm12` branch where I continue working on support for LLVM 12.

**Comment by aykevl** [comment]
Progress:
After some digging, I found that the `llvm.coro.size` assert seems to be caused by added `noreturn` attributes. They are correct before the coroutine transformation pass, but not anymore afterwards. Removing the attribute gets testdata/channel.go to work again but doesn't fix testdata/json.go so it's not a complete fix. Also, simply removing the attribute seems incorrect.

```diff
diff --git a/transform/coroutines.go b/transform/coroutines.go
index 2aeff43c..1fc39635 100644
--- a/transform/coroutines.go
+++ b/transform/coroutines.go
@@ -1029,6 +1029,7 @@ func (c *coroutineLoweringPass) fixAnnotations() {
                                f.RemoveEnumAttributeAtIndex(i, kindID)
                        }
                }
+               f.RemoveEnumFunctionAttribute(llvm.AttributeKindID("noreturn"))
        }
 }
 
```

**Comment by aykevl** [comment]
I've been further experimenting in the llvm12 branch: https://github.com/tinygo-org/tinygo/compare/dev...llvm12
Still looking into why goroutines are crashing.

**Comment by aykevl** [comment]
Here is a small reproducer:

```go
package main

import "time"

func main() {
	go selectDeadlock()
	time.Sleep(1)
}

func selectDeadlock() {
	println("deadlocking")
	select {}
	println("unreachable")
}
```

**Comment by aykevl** [comment]
So the issue is that some functions don't return, the `selectDeadlock` above for example doesn't return. In coroutine lowering, goroutines are started by simply calling them. When those functions don't return (even if they simply exit without panicking), this will lead to unreachable instructions in the parent goroutine.

Here is another reproducer:

```go
package main

import "time"

func main() {
	go doPanic()
	time.Sleep(1)
}

func doPanic() {
	println("hello")
	panic("abort! abort!")
}
```

**Comment by aykevl** [comment]
An even more innocent example, no `panic` in sight!

```go
package main

import "time"

func main() {
	go goroutine()
	time.Sleep(1)
	println("main hello")
}

func goroutine() {
	for {
		println("go hello")
		time.Sleep(time.Second)
	}
}
```

It triggers an error because `goroutine` is called from main but doesn't actually return.
I'm now convinced this is a bug in how we do goroutines. It has always been buggy, but LLVM didn't do the optimizations yet that would catch the bug. But in LLVM 12, the optimizer has become smart enough to catch the (erroneous) IR that we were emitting.

**Comment by dgryski** [comment]
This can probably be closed now.

**Comment by QuLogic** [comment]
Yes indeed.

**Pull request closed without merging**
