### PR TITLE
all: use latest version of x/tools

### PR DESCRIPTION
**Pull request by aykevl**
We previously picked a work-in-progress patch, but this is the proper fix for this race condition. I think we should use that instead of relying on the previous work-in-progress patch.

(I didn't verify this still fixes the race condition, but it should, and if not we'll find out soon enough).

### CODE REVIEW

**Comment by deadprogram** [comment]
@aykevl looks like something went wrong on this PR https://app.circleci.com/pipelines/github/tinygo-org/tinygo/10982/workflows/26ac7071-bdda-414d-b768-62b6b79b5bf5/jobs/43358?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-118-3695_73

**Comment by aykevl** [comment]
Huh, weird. Looks like the race isn't quite fixed yet.

**Comment by aykevl** [comment]
I picked the wrong git hash, it was the commit right before the actual fix.
I've updated the PR and confirmed it still fixes the race.

**Comment by deadprogram** [comment]
Thanks for updating @aykevl now merging.

**Pull request merged**
