### PR TITLE
builder: write a symbol table when writing out the compiler-rt lib

### PR DESCRIPTION
**Pull request by aykevl**
This should fix an issue with LLVM 9 (specifically, ld.lld-9).
See: https://github.com/tinygo-org/tinygo/issues/595

### CODE REVIEW

**Comment by aykevl** [comment]
All smoketests have identical outputs, so this PR should not have any side effects on LLVM 8.

**Comment by deadprogram** [comment]
I suppose my only comment is that I would suggest implementing this in the form of a new function aka `createSymbolTable()` in part because the `CompileBuiltins()` is quite a few lines of code already.

**Comment by aykevl** [comment]
That's a fair request. I did it slightly differently: I made a function that builds an archive file (with symbol table) from a list of object files - this makes it reusable. I also replaced a panic with an error return.

**Comment by deadprogram** [comment]
Looks good, now merging.

**Pull request merged**
