### PR TITLE
Add flag for setting the goroutine stack size 

### PR DESCRIPTION
**Pull request by aykevl**
This is helpful in some cases where the default stack size isn't big enough. See https://github.com/tinygo-org/tinygo/pull/3135 for example.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by dgryski** [comment]
CI failure due to insufficiently creating an config struct during testing.

**Comment by eyz** [comment]
This will be a new `--stack-size` option?

**Comment by aykevl** [comment]
Thanks, should be fixed now.

**Comment by deadprogram** [comment]
Thanks @aykevl now merging.

**Pull request merged**
