### PR TITLE
all: use internal/cm package for WASI 0.2

### PR DESCRIPTION
**Pull request by ydnar**
- Replace a git submodule in `src/vendor` with an explicit dependency in `go.mod`.
- Copy of the contents of package `cm` in `src/internal/cm`. This eliminates the `src/vendor` directory introduced with the WASI 0.2 PR.
- Updates `internal/tools/tools.go` to add `github.com/ydnar/wasm-tools-go/cmd/wit-bindgen-go` as a versioned tool dependency.
- Updates `wasm-tools-go` to v0.1.4 and regenerates WASI 0.2 bindings in `src/internal/wasi`.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by ydnar** [comment]
Had to workaround TinyGo supporting Go 1.19, and wasm-tools-go requiring Go 1.22. Separate go.mod file to the rescue!

**Comment by deadprogram** [comment]
@ydnar do you want to squash any of these commits before merge?

**Comment by deadprogram** [comment]
Thanks for the improvement @ydnar and to @dgryski for the review. Now merging.

**Pull request merged**
