### PR TITLE
Harmonize stm32 ticks and sleep

### PR DESCRIPTION
**Pull request by kenbell**
This addresses #1666 - merging tick / sleep logic.

### CODE REVIEW

**Comment by kenbell** [comment]
@ofauchon would it be possible for you to test the LGT92 on this branch?  I don't have one available to validate with.

**Comment by ofauchon** [comment]
Hi @kenbell, 

I  ran a quick test on blinky1 example (which uses timer) 

```
$ git remote -v
origin	git@github.com:kenbell/tinygo.git (fetch)
origin	git@github.com:kenbell/tinygo.git (push)
$ git branch
* harmonize-stm32-ticks-and-sleep
```

After building and flashing (target=lgt92) , the led blinks as expexted, so your patch looks good to me . 

Please tell me if you need extra tests. 

Olivier

**Comment by kenbell** [comment]
@ofauchon that's perfect, thank you!

**Comment by deadprogram** [comment]
Any feedback on this from @aykevl or @ardnew ?

**Comment by deadprogram** [comment]
Since no comments/objections, I am going to merge now. I tested on STM32F405 board and worked as expected.

Thanks for working on this @kenbell it is a great step in the correct direction!

**Comment by ofauchon** [comment]
Hi @kenbell , 

Thank you for this great contribution !

At the moment, I'm working on STM32WL port, and It seems this latest generation of STM32 chips have 
new kind of Timer  ( LP/GP/Advance/TIM_Type... )


```
grep TIM stm32wle5.go  | grep Type 
	LPTIM1 = (*LPTIM_Type)(unsafe.Pointer(uintptr(0x40007c00)))
	LPTIM2 = (*LPTIM_Type)(unsafe.Pointer(uintptr(0x40009400)))
	LPTIM3 = (*LPTIM_Type)(unsafe.Pointer(uintptr(0x40009800)))
	TIM16 = (*GPTIM_Type)(unsafe.Pointer(uintptr(0x40014400)))
	TIM17 = (*GPTIM_Type)(unsafe.Pointer(uintptr(0x40014800)))
	TIM1 = (*AdavanceTIM_Type)(unsafe.Pointer(uintptr(0x40012c00)))
	TIM2 = (*GPTIM_Type)(unsafe.Pointer(uintptr(0x40000000)))

... Even the timer registers had been renamed: 

stm32wle5.go:	GPTIM_SR_UIF_Pos = 0x0
stm32wle5.go:	GPTIM_SR_UIF_Msk = 0x1
stm32wle5.go:	GPTIM_SR_UIF = 0x1
stm32wle5.go:	AdavanceTIM_SR_UIF_Pos = 0x0
stm32wle5.go:	AdavanceTIM_SR_UIF_Msk = 0x1
stm32wle5.go:	AdavanceTIM_SR_UIF = 0x1

```
Please tell me if you have a idea for a fix . 

Thx 

Olivier

**Comment by ofauchon** [comment]
Hi .. 

I could fix the build by patching  stm32wle5.svd, and "make  gen-device-stm32" 

```
[olivier@psx tinygo]$ diff -u ./lib/stm32-svd/svd/stm32wle5.svd.old ./lib/stm32-svd/svd/stm32wle5.svd
--- ./lib/stm32-svd/svd/stm32wle5.svd.old	2021-04-07 00:37:43.945618017 +0200
+++ ./lib/stm32-svd/svd/stm32wle5.svd	2021-04-07 00:37:55.405676992 +0200
@@ -9597,7 +9597,7 @@
       <peripheral>
          <name>TIM16</name>
          <description>General-purpose timers</description>
-         <groupName>GPTIM</groupName>
+         <groupName>TIM</groupName>
          <baseAddress>0x40014400</baseAddress>
          <addressBlock>
             <offset>0x0</offset>
@@ -10234,7 +10234,7 @@
       <peripheral>
          <name>TIM17</name>
          <description>General-purpose timers</description>
-         <groupName>GPTIM</groupName>
+         <groupName>TIM</groupName>
          <baseAddress>0x40014800</baseAddress>
          <addressBlock>
             <offset>0x0</offset>
@@ -22336,7 +22336,7 @@
       <peripheral>
          <name>TIM2</name>
          <description>General-purpose-timers</description>
-         <groupName>GPTIM</groupName>
+         <groupName>TIM</groupName>
          <baseAddress>0x40000000</baseAddress>
          <addressBlock>
             <offset>0x0</offset>
@@ -26589,4 +26589,4 @@
          </registers>
       </peripheral>
    </peripherals>
-</device>
\ No newline at end of file
+</device>
```

Now the question is how can we properly integrate SVD patches into tinygo

**Comment by kenbell** [comment]
Cool - we'd need to upstream this to the `stm32-rs` project.  I did a little write-up here: https://github.com/tinygo-org/tinygo/wiki/Adding-support-for-an-STM32-MCU

From the reference manuals, these timers aren't 100% the same as the 'basic' timers found on other chips.  I'm not sure if the Rust team would want to rename them, but we can ask.

If they don't want to rename, then we'll probably have to setup some kind of abstraction.  One way might be to do this per-chip family in the `machine` package:
```go
type Timer = stm32.TIM_Type   // stm32.GPTIM_Type for stm32wle5
const TIM_SR_UIF_Pos = stm32.TIM_SR_UIF_Pos   // stm32.GPTIM_SR_UIF_Pos for stm32wle5
...
```

**Pull request merged**
