### PR TITLE
docs: update CONTRIBUTING links to point to web site.

### PR DESCRIPTION
**Pull request by deadprogram**
This PR updates the CONTRIBUTING links to point to the web site. It also replaces the MS Azure build badge with a build badge to the Windows build on GH Actions.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by niaow** [comment]
Would it make sense to delete CONTRIBUTING.md instead, since we are also removing the reference to it?

**Comment by dgryski** [comment]
@niaow Having a CONTRIBUTING.md file means github will point to it when someone opens an issue or a PR.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#about-contributing-guidelines

**Comment by niaow** [comment]
Ah. Okay, makes sense.

**Pull request merged**
