### PR TITLE
Enable taking value of exported functions

### PR DESCRIPTION
**Pull request by kyegupov**
This is a fairly complex feature, so probably will require a fair share of reviewing.

Problem: I need to supply an address of a function written in TinyGo to be used by external code (like callback). The problem is, TinyGo assumes that every non-exported function is a closure and adds an implicit last parameter (a pointer to closure context) to every function's signature. Exported functions are not patched that way, so TinyGo disallows saving them as values, to avoid attempting to call them with a wrong set of parameters.

The above behavior is not documented in https://tinygo.org/compiler-internals/calling-convention/ :(

If I disable that check to just retrieve the function value and never call it, LLVM still complains because I want to use `func (...myparams...)` as a value of type `func (...myparams..., *i8)`.

The solution in this patch is attempting to resolve this problem via the following (minimally intrusive) hack:

* there are now 2 compile-time kinds of function values: closures and "export ABI" functions
* every function signature with the first parameter `_exportABI struct{}` (effectively empty) will be of "export ABI" kind
* signatures of functions with "export ABI" do not have an extra parameter for a pointer to closure context
* function values with "export ABI" signatures are just function pointer, not pairs of (context, funcPtr)
* function values of both kinds still can be "called" correctly

On WebAssembly target it seems to do the right thing.

If accepted, this needs to be documented in https://tinygo.org/compiler-internals/calling-convention/

Tests added. As a drive-by, some additions to the `Sizeof` implementation.

### CODE REVIEW

**Comment by kyegupov** [comment]
@aykevl the problem is, I cannot "use privateSquare as a function value.", because privateSquare has, effectively, a signature of "(x int, closureContext *i8) -> int", and I need to expose a pointer to a function with a signature of "(x int) -> int". My target is WebAssembly and it makes distinction between those.

**Comment by aykevl** [comment]
Ah, now I see the problem.
I will have to think about this a bit. This is one solution, but perhaps there are other ways that look less like a hack.

And by the way, now I realize that this extra context parameter to functions is also part of the public ABI: a function value can also be passed as an argument and then called by the external code. So then it needs to go into the calling convention or ABI docs after all.

**Comment by aykevl** [comment]
Would a solution like the following work for you? It is not currently supported, but can be added:

```go

//go:export external_func
func external_func(cb func callback(int i))

func main() {
    // call imported function
    external_func(mycallback)
}

//go:export mycallback
func mycallback(int i) {
    println("called a callback:", i)
}
```

The idea is to change the calling convention for function values in functions that are exported to be bare function pointers (no context). This disallows passing any Go function value, but can still allow exported functions as they do not have the context parameter.
The advantage here is that it does not affect the wider type system. I'm afraid that this `_exportABI` hack will cause unintended side effects in the future.

**Comment by kyegupov** [comment]
@aykevl no, unfortunately it won't work, because what I'm actually doing is more like
`external_func(serialized(listOfNameAndCallbackPairs))`

(actual code is https://github.com/Joystream/tinygo-wasm-substrate/blob/ff36f1921f26cfef4f7d3bbf46220342f9a792bf/srcore/srsandbox/sr-sandbox.go#L79 and https://github.com/Joystream/tinygo-wasm-substrate/blob/master/srcore/srsandbox/sr-sandbox.go#L131)

I do not expect much problems with the _exportABI hack. The Go's typesystem should prevent exportabi and non-export-abi types from ever mixing.

**Comment by deadprogram** [comment]
Hello @kyegupov we have switched to using the `dev` branch for all active development. Details here: https://github.com/tinygo-org/tinygo/blob/dev/CONTRIBUTING.md#how-to-use-our-github-repository

Can you please resolve the merge conflict in this branch that has resulted from that switch? Thank you.

**Comment by kyegupov** [comment]
@deadprogram done

**Comment by aykevl** [comment]
With #174, there is initial support for pointer types in CGo.

With this PR, you can take the address of a Go function and pass it to an external function:

```go
// int mul(int, int);
import "C"

import "unsafe"

//export someExternalFunc
func someExternalFunc(arr []unsafe.Pointer)

func main() {
    var callback unsafe.Pointer = C.mul
    // Do something with the callback, like pass it to an external function in whatever way you want.
    // example:
    someExternalFunc([]unsafe.Pointer{callback})
}

//export mul
func mul(a, b int) int {
    return a * b
}
```

I haven't tested this code but something like that should be possible. Would that solve this issue?

> I do not expect much problems with the _exportABI hack. The Go's typesystem should prevent exportabi and non-export-abi types from ever mixing.

True, but it introduces complexity which is what I'm trying to avoid. Now I'm truly understanding why the Go developers try to avoid complexity so much - it's often exponential.
For example, either reflection would have to deal with these special pointer types (bringing in a _lot_ of complexity) or types that contain an exportabi function type must not be allowed in interfaces. I'd go with the latter to avoid all that extra complexity for little gain. But maybe there are other things I haven't thought about that would also be complicated.
Also, I haven't seen a real use case outside of Parity Substrate for this special type, so that's also what holds me back. If it is broadly useful it would be useful, but currently I'm very hesitant to add it. The `-wasm-abi` flag, in comparison, was much easier and didn't really affect the compiler itself.

**Comment by aykevl** [comment]
I'm not yet convinced that the complexity cost is worth it, especially since this only seems to be useful for a single use case (interfacing with a particular WebAssembly ABI). Closing now. It can be reopened if it turns out this is more broadly useful.

**Pull request closed without merging**
