### PR TITLE
Handle 64-bit len/cap parameters in make

### PR DESCRIPTION
**Pull request by kyegupov**
Fixes https://github.com/aykevl/tinygo/issues/120

### CODE REVIEW

**Comment by kyegupov** [comment]
(note another interesting thing: since len/cap are supposed to be nonnegative, what is the point of calling CreateSExt? the resulting uintptr number will be wildly wrong anyway, wouldn't it?)

**Comment by aykevl** [comment]
> (note another interesting thing: since len/cap are supposed to be nonnegative, what is the point of calling CreateSExt? the resulting uintptr number will be wildly wrong anyway, wouldn't it?)

The index `uint8(255)` is a valid index (if the slice is long enough), but `int8(-1)` is not, even though they have the same bit pattern. So indexes have to be correctly zero/sign extended.

**Comment by kyegupov** [comment]
But if you sign-extend int8(-1), you get MaxUint32() value, which is probably not something you want.
I think there should be a guard against negative values.

**Comment by deadprogram** [comment]
Seems good, any reason to not merge this?

**Comment by aykevl** [comment]
@kyegupov I'm afraid this is the wrong solution, but I would have to check the language specification to be certain (and to explain why). Also, I would like to reproduce the bug first on my machine because in theory this issue should be covered by the slice tests, and in fact those tests pass for the WebAssembly target.

**Comment by kyegupov** [comment]
@aykevl you wish has been granted, here's how to reproduce this error in tests: https://github.com/aykevl/tinygo/pull/128

**Comment by kyegupov** [comment]
The language spec does not seem to cover this particular aspect: https://golang.org/ref/spec#Making_slices_maps_and_channels

**Comment by aykevl** [comment]
This is the important part (highlight by me):

> Each of the size arguments n and m **must be of integer type** or an untyped constant. A constant size argument must be non-negative and representable by a value of type int; if it is an untyped constant it is given type int. If both n and m are provided and are constant, then n must be no larger than m. **If n is negative or larger than m at run time, a run-time panic occurs.**

Most importantly, it doesn't say anything about the type of n and m except that they must be integers. That means the full range of int/uint in all sizes is supported, including uint64. It also means that code like the following is not allowed:

```go
make([]byte, uint64(0x2000000003), 5)
```

When you truncate code like this to uintptr on a 32-bit platform, it may not result in a runtime panic because the `len` param (`n`) is truncated to 3 because the high bits are chopped off. This is why you have to do the bounds check at the highest integer size necessary and why something like [`runtime.sliceBoundsCheck64`](https://github.com/aykevl/tinygo/blob/master/src/runtime/panic.go#L53) exists.
This makes me think, there probably should be a `runtime.sliceBoundsCheckMake64` to fix this bug. Also, I see that the function names and param types are somewhat inconsistent, which makes bounds checking even more confusing.

**Comment by aykevl** [comment]
Here is some code that is incorrectly allowed by this PR but not by the main Go compiler and not by #129 either.

```go
package main

func main() {
	s := make([]byte, getLen(), getCap())
	println(len(s))
}

func getLen() uint64 {
	return 0x200000003
}

func getCap() int {
	return 5
}
```

As you can see, truncate-then-check is dangerous and allows invalid code.

**Comment by deadprogram** [comment]
Hi @kyegupov any thoughts about @aykevl last comment?

**Comment by kyegupov** [comment]
This is superseded by https://github.com/tinygo-org/tinygo/pull/129

**Pull request closed without merging**
