### PR TITLE
all: update to version 0.25.0

### PR DESCRIPTION
**Pull request by aykevl**

### CODE REVIEW

**Comment by deadprogram** [comment]
@aykevl I merged https://github.com/tinygo-org/tinygo/pull/3032 do you want to add to CHANGELOG before merge?

**Comment by aykevl** [comment]
Rebased and updated the CHANGELOG.

**Comment by sago35** [comment]
Please add the following

* #3032
* #3036

**Comment by aykevl** [comment]
>   * [Setting internal linkage and keeping default visibility for anonymous functions #3032](https://github.com/tinygo-org/tinygo/pull/3032)

This is included, but I worded it a bit differently:

> `compiler`: fix multiple defined function issue for generic functions

>   * [wasm,wasi: stub runtime.buffered, runtime.getchar #3036](https://github.com/tinygo-org/tinygo/pull/3036)

Sorry I misunderstood the patch. I normally don't add a changelog entry for patches to features that are new in a release, but this one was already included in v0.24.0. I have updated the changelog.

**Review by sago35 — APPROVED** [review]

**Comment by sago35** [comment]
@aykevl @deadprogram 
Please also add this information to the Release page.

**Comment by aykevl** [comment]
Sorry about the delay, I've finally updated the release page.

**Pull request merged**
