### PR TITLE
Makefile: add report-stdlib-tests-pass

### PR DESCRIPTION
**Pull request by dkegel-fastly**
"make report-stdlib-tests-pass" just turns the Makefile variables into an easily parsed report of what platforms each standard library package passes tests on.

Intention is to use this to populate new columns in https://tinygo.org/docs/reference/lang-support/stdlib,
cf. https://gophers.slack.com/archives/CDJD3SUP6/p1646132970005739?thread_ts=1645753063.867579&cid=CDJD3SUP6

### CODE REVIEW

**Review by stuartmscott — COMMENTED** [review]
Thanks for putting this together!

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by dkegel-fastly** [comment]
Rebased.

**Comment by deadprogram** [comment]
Now merging, thanks @dkegel-fastly

**Pull request merged**
