### PR TITLE
main: release 0.14.0

### PR DESCRIPTION
**Pull request by aykevl**
Perhaps some extra PRs need to be merged before actually merging this (and making the release) but I've already done some of the time consuming part here.

### CODE REVIEW

**Comment by deadprogram** [comment]
We should add the couple of PRs that made it into `dev` in the last couple of days to the changelog.

**Comment by aykevl** [comment]
I have updated this PR to reflect the latest changes in the dev branch. I think this release is now ready.

**Comment by deadprogram** [comment]
Incredible work from everyone on this release! Now merging.

**Comment by deadprogram** [comment]
So I think to complete this release, we now need to do the following:

```
git checkout dev
git pull --rebase origin dev
git checkout master
git rebase dev
git branch -m master release
git push -u origin release
```

Once that is done, then we change the settings in the Github web interface to use `release` as the default branch *Settings > Branches > Default branch" and that should be it.

I have done this procedure already on GoCV repo for the most recent release there.

**Comment by aykevl** [comment]
I have created the release branch and pushed it, but for some strange reason I can't push the master branch :thinking: but that shouldn't be a problem.
I have set the release branch as the default branch.

**Pull request merged**
