### PR TITLE
fix GBA ROM header

### PR DESCRIPTION
**Pull request by mogenson**
Populate the GBA ROM header so that emulators and physical Game Boy Advance consoles recognize the ROM as a valid game.

This PR removes the need for post-processing of a GBA ROM by a tool like `gbafix`. It's based on [this commit](https://github.com/rust-console/gba/commit/016d9a577db6aeff0354a6d55da3fb9a57891b24) to the [rust-console/gba](https://github.com/rust-console/gba) project: 

Testing:
```
$ tinygo build -target=gameboy-advance -o gba-display.gba examples/gba-display
$ file gba-display.gba
gba-display.gba: Game Boy Advance ROM image (, Rev.00)
$ mgba gba-display.gba # also copy rom to flashcart
```

Note: The reserve space at the end of the header had to be hand-tuned to this specific value of 98 bytes. Can anyone here tell me why? Something to do with word boundaries for ARM vs Thumb mode? Padding with 158 bytes also worked, but anything less than 98 bytes failed to boot.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @mogenson thanks for the contribution. I do not have enough specific knowledge to weigh in on this subject, perhaps @aykevl or @kylelemons or someone else can comment.

**Comment by mogenson** [comment]
Sure, here's some background info on the GBA ROM header format: http://www.akkit.org/info/gbatek.htm#gbacartridgeheader

**Comment by deadprogram** [comment]
Even without this commit I am able to build/run that example:

```
$ tinygo build -target=gameboy-advance -o gba-display.gba examples/gba-display
tinygo:ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
$ mgba gba-display.gba
```

mgba

Am I missing something?

**Comment by mogenson** [comment]
Curious. I'm on Ubuntu 20.04, LLVM 10, and mgba 0.7.0. If I build tinygo 0.16.0 from the release branch then compile a gba-display.gba ROM. I see the following:

```
$ file gba-display.gba
gba-display.gba: dBase III DBT, version number 0, next free block index 3925868590, 1st item "A\003\240\343\004\020\240\343"
```

```
$ mgba gba-display.gba
The game has crashed with the following error: Jumped to invalid address: 00000000
```

```
$ hexdump gba-display.gba
0000000 002e ea00 0000 0000 0000 0000 0000 0000
0000010 0000 0000 0000 0000 0000 0000 0000 0000
*
00000b0 3130 0096 0000 0000 0000 0000 f000 0000
00000c0 0012 e3a0 f000 e129 d02c e59f 001f e3a0
00000d0 f000 e129 d024 e59f 0301 e3a0 1020 e59f
00000e0 1004 e500 1001 e3a0 1208 e580 3014 e59f
00000f0 ff13 e12f 0010 e59f ff10 e12f 0000 0300
0000100 0400 0300 00f4 0800 0154 0800 0110 0800
0000110 4800 e92d c034 e59f e0ff e3a0 2000 e3a0
0000120 0001 e3a0 ecff e38e 10b0 e1dc 000e e352
0000130 4800 08bd ff1e 012f 300e e002 2001 e282
0000140 0310 e111 3310 11a0 30b0 11cc fff6 eaff
0000150 0202 0400 4800 e92d 0068 e59f 1068 e59f
0000160 2000 e3a0 0000 e151 0001 0a00 2004 e480
0000170 fffb eaff 0054 e59f 1054 e59f 2054 e59f
0000180 0000 e152 0002 0a00 3004 e491 3004 e480
0000190 fffa eaff 0040 e59f 1001 e3a0 1000 e5c0
00001a0 0038 e59f 1000 e5c0 0034 e59f 1034 e59f
00001b0 1000 e041 2321 e1a0 1000 e3a0 0020 eb00
00001c0 4800 e8bd 0008 ea00 0c00 0300 0c14 0300
00001d0 0c00 0300 025c 0800 0c00 0300 0c10 0300
00001e0 0c11 0300 0000 0200 0000 0204 0301 e3a0
00001f0 1003 e3a0 c01e e3a0 201f e3a0 1000 e5c0
0000200 0341 e3a0 1004 e3a0 1000 e5c0 102c e59f
0000210 0032 e35c ff1e 012f 3000 e3a0 0d96 e353
0000220 0003 0a00 0003 e081 3e1e e283 20b0 e1c0
0000230 fff9 eaff 1002 e281 c001 e28c fff3 eaff
0000240 963c 0600 3000 e3a0 0003 e152 f00e 01a0
0000250 1003 e7c0 3001 e283 fffa eaff          
000025c
```

With this PR, the `file` command reports: `Game Boy Advance ROM image (, Rev.00)` and `hexdump` shows the header is populated:

```
0000000 0046 ea00 ff24 51ae 9a69 21a2 843d 0a82
0000010 e484 ad09 2411 988b 81c0 217f 52a3 19be
0000020 0993 20ce 4610 4a4a 27f8 ec31 c758 33e8
0000030 e382 bfce f485 94df 4bce c109 5694 c08a
0000040 7213 fca7 849f 734d caa3 619a 9758 27a3
0000050 03fc 7698 1d23 61c7 0403 56ae 38bf 0084
0000060 a740 fd0e 52ff 03fe 956f f130 fb97 85c0
0000070 d660 2580 63a9 03be 4e01 e238 a2f9 ff34
0000080 3ebb 4403 0078 cb90 1188 943a c065 637c
0000090 f087 af3c 25d6 8be4 0a38 72ac d421 07f8
00000a0 0000 0000 0000 0000 0000 0000 0000 0000
00000b0 0000 0096 0000 0000 0000 0000 5100 0000
00000c0 0000 0000 0000 0000 0000 0000 0000 0000
*
0000120 0012 e3a0 f000 e129 d02c e59f 001f e3a0
0000130 f000 e129 d024 e59f 0301 e3a0 1020 e59f
0000140 1004 e500 1001 e3a0 1208 e580 3014 e59f
0000150 ff13 e12f 0010 e59f ff10 e12f 0000 0300
0000160 0400 0300 0154 0800 01b4 0800 0170 0800
0000170 4800 e92d c034 e59f e0ff e3a0 2000 e3a0
0000180 0001 e3a0 ecff e38e 10b0 e1dc 000e e352
0000190 4800 08bd ff1e 012f 300e e002 2001 e282
00001a0 0310 e111 3310 11a0 30b0 11cc fff6 eaff
00001b0 0202 0400 4800 e92d 0068 e59f 1068 e59f
00001c0 2000 e3a0 0000 e151 0001 0a00 2004 e480
00001d0 fffb eaff 0054 e59f 1054 e59f 2054 e59f
00001e0 0000 e152 0002 0a00 3004 e491 3004 e480
00001f0 fffa eaff 0040 e59f 1001 e3a0 1000 e5c0
0000200 0038 e59f 1000 e5c0 0034 e59f 1034 e59f
0000210 1000 e041 2321 e1a0 1000 e3a0 0020 eb00
0000220 4800 e8bd 0008 ea00 0c00 0300 0c14 0300
0000230 0c00 0300 02bc 0800 0c00 0300 0c10 0300
0000240 0c11 0300 0000 0200 0000 0204 0301 e3a0
0000250 1003 e3a0 c01e e3a0 201f e3a0 1000 e5c0
0000260 0341 e3a0 1004 e3a0 1000 e5c0 102c e59f
0000270 0032 e35c ff1e 012f 3000 e3a0 0d96 e353
0000280 0003 0a00 0003 e081 3e1e e283 20b0 e1c0
0000290 fff9 eaff 1002 e281 c001 e28c fff3 eaff
00002a0 963c 0600 3000 e3a0 0003 e152 f00e 01a0
00002b0 1003 e7c0 3001 e283 fffa eaff          
00002bc
```

Is there something else to check to see if this is just a problem for me, and this PR is not needed? Note, I also have an Arch Linux machine that shows the same result.

**Comment by aykevl** [comment]
I can reproduce the game crash. Maybe it's the mGBA version? I'm also using mGBA 0.7.0, and I have the exact same binary output as @mogenson.

I suspect the issue is not the missing Nintendo logo but rather that the alignment is wrong, something that might be fixed by a single line patch. However, I'm not quite sure what mGBA is expecting here.

I feel a bit uneasy merging in the Nintendo logo (which might have copyright issues) without knowing for sure that it is necessary.

**Comment by deadprogram** [comment]
I am running older mgba it would seem, as the 0.5.2 is the version in the 18.04 package repo.

**Comment by scraly** [comment]
Any news about it? :-)

**Comment by racerxdl** [comment]
@aykevl / @deadprogram the logo is nescessary for running on real hardware, since it refuses to boot if not in the catridge. I can confirm it does run fine with it (or using gbafix).

image

Nowadays there are some special crafted catridges that allows to no have that correctly (you can even change it to whatever you want since it tricks the CPU thinking is the right logo), but they're not very common.

**Comment by aykevl** [comment]
Ok, merged this PR. I'm hoping Nintendo won't come after us for including the GBA logo :sweat_smile: (although there is a good chance this is actually protected because it's purely for compatibility).

**Comment by racerxdl** [comment]
@aykevl at least is very very easy to remove in the case nintendo comes after.  Also that is the same for all gameboy series, it checks for that bytes in the same position. The difference is that GBA just check to boot, the older Gameboys also display that directly from the catrige, and there are some catridge that does some trick to validate the logo, and then change on boot. https://shop.insidegadgets.com/product/gameboy-512kb-32kb-fram-flash-cart-custom-boot-logo-option/

But even with that trick, it needs to include a bootlogo somewhere  in the catridge otherwise it will refuse to boot.

**Pull request merged**
