### PR TITLE
runtime/atsamd51: fix clock init code

### LINKED ISSUE #649: incorrect clock rates on atsamd51
The CPU clock rate on atsamd51 is incorrect, and unpredictable.

I set up the SysTick clock to generate ticks every 10ms, and made an interrupt handler that flips a GPIO pin every time it fires.  Then I probed that pin with a scope.

First time, I saw a square wave with 14ms between transitions.
I hit the reset button, then I saw a square wave with 6ms between transitions.
I reset it again, then I saw a square wave with 12ms between transitions.
I reset it again, then I saw a square wave with 23ms between transitions.
I reset it again, the program didn't start up at all.
I reset it again, then I saw a square wave with 8ms between transitions.

The CPU is not running at 120MHz; DPLL0 is settling at a different rate each time the chip is reset. 
 This makes it difficult to work with timing-sensitive peripherals, like neopixels.

The initClocks() function for atsamd51 has a bug.  I will submit a pull request with the fix.

### PR DESCRIPTION
**Pull request by Infinoid**
This fixes #649 .

The code is trying to set up the following chain:

GCLK7 = DFLL48M / 24 = 2MHz
DPLL0 = GCLK7 * 60 = 120MHz

But the setup of GCLK7 was wrong.  DIVSEL is a single-bit flag field, DIV is a 16 bit integer field.  The code should assign the value (24) to the integer field, not the flag.

### CODE REVIEW

**Comment by Infinoid** [comment]
For review purposes, the relevant docs are here: http://ww1.microchip.com/downloads/en/DeviceDoc/60001507E.pdf section 14.8.3.

**Comment by aykevl** [comment]
I was just looking at that section!

**Comment by aykevl** [comment]
Oops, https://github.com/tinygo-org/tinygo/issues/649#issuecomment-545622217 should have been here, not at the bug report.

**Comment by Infinoid** [comment]
I updated this to fix a second, related issue that was introduced after v0.8.0 (which is where I developed the original fix).

I have now tested this on current dev branch; it works.

**Comment by Infinoid** [comment]
In summary, this PR fixes 2 bugs:

- setup of GCLK7 should use GENCTRL_DIV_Pos, not GENCTRL_DIVSEL_Pos for the shift offset.  DIVSEL is a flag, DIV is the integer field that should get the divisor value (24).  Looks like this was incorrect since the file's creation.
- setup of PLL0 should write the main multiplier value (59) to LDR, instead of writing to LDRFRAC twice.  This bug was introduced a couple of weeks ago:
https://github.com/tinygo-org/tinygo/commit/92e07ec8afa28662b740009eeee616d312d6d1ff#diff-185c01b39331690809325d7ba673c75cR98

According to http://ww1.microchip.com/downloads/en/DeviceDoc/60001507E.pdf section 28.6.5, PLL output speed = input * (LDR + 1 + (LDRFRAC/32)).  Setting LDR=59 and LDRFRAC=0 results in a multiplier of 60.  And 2MHz * 60 = 120MHz.

I also added some better comments in there to try to explain what the magic numbers are doing.  There was a funny comment in there: `// this means 100 Mhz?`  Hopefully that should be more clear now.

**Comment by deadprogram** [comment]
Tested and it works as promised. Thank you very much for the contribution @Infinoid now squash/merging.

**Pull request merged**
