### PR TITLE
compiler,runtime: fix multiple definitions of a single function

### LINKED ISSUE #351: error: verification error after IR construction
When building the https://github.com/tinygo-org/drivers/tree/master/examples/espat/espconsole example as part of the build in the smoke test, the following error is now appearing:

```shell
$ tinygo build -size short -o test.elf -target=itsybitsy-m0 ./examples/espat/espconsole/main.go
conflicting debug info for argument
  call void @llvm.dbg.value(metadata i8* %0, metadata !30275, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 32)), !dbg !30291
!30280 = !DILocalVariable(name: "s", arg: 1, scope: !30278, file: !29386, line: 171, type: !127)
!30275 = !DILocalVariable(name: "s", arg: 1, scope: !30270, file: !30271, line: 150, type: !127)
conflicting debug info for argument
  call void @llvm.dbg.value(metadata i8 %2, metadata !30276, metadata !DIExpression()), !dbg !30291
!30281 = !DILocalVariable(name: "c", arg: 2, scope: !30278, file: !29386, line: 171, type: !162)
!30276 = !DILocalVariable(name: "c", arg: 2, scope: !30270, file: !30271, line: 150, type: !162)
error: verification error after IR construction
```

### PR DESCRIPTION
**Pull request by aykevl**
`strings.IndexByte` used to be implemented in the runtime. Now it is implemented using a direct call to `internal/bytealg.IndexByte`. Fixes #351.

The real problem is of course https://github.com/golang/go/issues/31330.

### CODE REVIEW

**Comment by aykevl** [comment]
This fails on Go 1.11 only, because the change was introduced in Go 1.12. @deadprogram maybe we should drop support for Go 1.11? One reason for keeping it would be that the next Debian stable release will ship with Go 1.11 so supporting Go 1.11 would ease the installation for people using that. Alternatives would be to allow multiple definitions and just pick the first (gross, hard to maintain in the future) or to check the version of the used Go standard library (more work). Any preferences?

**Comment by deadprogram** [comment]
I hate to say it, but checking the version of the Go standard library sounds like the way. The Debian thing is reason enough.

**Comment by aykevl** [comment]
This is hopefully fixed now.

**Comment by deadprogram** [comment]
It fixes it for me. Now merging, thank you very much!

**Pull request merged**
