### PR TITLE
runtime: disallow defer in interrupts

### PR DESCRIPTION
**Pull request by aykevl**
This often doesn't work because there might not be a current task to push the defer frame to. It will instead show an unhelpful nil pointer dereference panic.

We could make this work with a separate defer stack for interrupts (as if they were newly started goroutines) but that is difficult with multiple interrupts happening at the same time (we shouldn't jump to a previous interrupt in `panic()`!). So instead, disable defer altogether in interrupts and adjust panic/recover accordingly.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by dgryski** [comment]
Do we also want to tweak the compiler so that defers get printed as allocations when `-print-allocs` is on?

**Comment by aykevl** [comment]
> Do we also want to tweak the compiler so that defers get printed as allocations when `-print-allocs` is on?

Those allocations are regular allocations, they should already get printed with `-print-allocs=.`. (Note that many simple defers don't allocate, it's mainly the ones in loops that require a heap allocation).

**Comment by deadprogram** [comment]
The fix for nix is in... or at least for the CI. Please rebase against latest dev.

**Comment by aykevl** [comment]
Rebased!

**Comment by deadprogram** [comment]
Thanks for the improvement @aykevl and to @dgryski for reviewing. Now merging.

**Comment by glococo** [comment]
Hi @aykevl , I refactorized tinygo somehow in this way:
machine.Serial.Enable().Receive( rx_callback )
however when an interrupt is fired, Arm jump to "handler mode", execute the interrupt, and when finish I would like to leave the handler mode and run the "callback" function in thread mode.

Why ? because runing the callback funcion in thread mode frees "interrupt active" register and in case of race conditions, interrupt can be called again while the callback is still running/paused and could keep filling a buffer.

I tried using defer (with previous tinygo version) but jump from iniside the handler mode, not freeing the interrupt active.
Any help is appreciated.

**Comment by aykevl** [comment]
@glococo the best way to do this right now is using a non-blocking send on a channel. Something like this:

```go
var ch = make(chan struct{}, 1)

// inside the interrupt handler
select {
case ch <- struct{}{}:
default:
}

// in a separate goroutine
for range ch {
    // handle event
}
```

As long as every operation is non-blocking, you can use channels inside interrupts.

**Pull request merged**
