### PR TITLE
all: switch to LLVM 9

### PR DESCRIPTION
**Pull request by aykevl**
This will probably require some compiler changes.

### CODE REVIEW

**Comment by aykevl** [comment]
This is very unfortunate:

```
FAILED: tools/lld/ELF/CMakeFiles/lldELF.dir/MapFile.cpp.obj 
C:\ProgramData\chocolatey\bin\c++.exe  -DGTEST_HAS_RTTI=0 -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/lld/ELF -ID:/a/1/s/llvm-project/lld/ELF -ID:/a/1/s/llvm-project/lld/include -Itools/lld/include -Iinclude -ID:/a/1/s/llvm-project/llvm/include -Wa,-mbig-obj -Werror=date-time -std=gnu++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment  -O2 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT tools/lld/ELF/CMakeFiles/lldELF.dir/MapFile.cpp.obj -MF tools\lld\ELF\CMakeFiles\lldELF.dir\MapFile.cpp.obj.d -o tools/lld/ELF/CMakeFiles/lldELF.dir/MapFile.cpp.obj -c D:/a/1/s/llvm-project/lld/ELF/MapFile.cpp
In file included from D:/a/1/s/llvm-project/lld/ELF/SymbolTable.h:13,
                 from D:/a/1/s/llvm-project/lld/ELF/MapFile.cpp:25:
D:/a/1/s/llvm-project/lld/ELF/Symbols.h:470:35: error: static assertion failed: SymbolUnion too large
 static_assert(sizeof(SymbolUnion) <= 80, "SymbolUnion too large");
               ~~~~~~~~~~~~~~~~~~~~^~~~~
[2748/3153] Building CXX object tools/lld/ELF/CMakeFiles/lldELF.dir/LTO.cpp.obj
FAILED: tools/lld/ELF/CMakeFiles/lldELF.dir/LTO.cpp.obj 
C:\ProgramData\chocolatey\bin\c++.exe  -DGTEST_HAS_RTTI=0 -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/lld/ELF -ID:/a/1/s/llvm-project/lld/ELF -ID:/a/1/s/llvm-project/lld/include -Itools/lld/include -Iinclude -ID:/a/1/s/llvm-project/llvm/include -Wa,-mbig-obj -Werror=date-time -std=gnu++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment  -O2 -DNDEBUG    -fno-exceptions -fno-rtti -MD -MT tools/lld/ELF/CMakeFiles/lldELF.dir/LTO.cpp.obj -MF tools\lld\ELF\CMakeFiles\lldELF.dir\LTO.cpp.obj.d -o tools/lld/ELF/CMakeFiles/lldELF.dir/LTO.cpp.obj -c D:/a/1/s/llvm-project/lld/ELF/LTO.cpp
In file included from D:/a/1/s/llvm-project/lld/ELF/SymbolTable.h:13,
                 from D:/a/1/s/llvm-project/lld/ELF/LTO.cpp:13:
D:/a/1/s/llvm-project/lld/ELF/Symbols.h:470:35: error: static assertion failed: SymbolUnion too large
 static_assert(sizeof(SymbolUnion) <= 80, "SymbolUnion too large");
               ~~~~~~~~~~~~~~~~~~~~^~~~~
[2749/3153] Linking CXX static library lib\liblldDriver.a
ninja: build stopped: subcommand failed.
mingw32-make: *** [Makefile:133: llvm-build] Error 1
```

**Comment by deadprogram** [comment]
It is unfortunate indeed. From the comment in the LLVM code the size limit is arbitrary.

It would be good to output `sizeof(SymbolUnion)` as suggested here https://reviews.llvm.org/D64077#1731233 perhaps just a different maximum size would solve the assertion.

In any case, since this is Windows only problem, and sinec there is not really any standard package management, perhaps we can use a custom LLVM build for Windows until the problem in upstream LLVM is resolved.

**Comment by jadr2ddude** [comment]
Have you tried using the latest LLVM tag instead ([llvmorg-9.0.0](https://github.com/llvm/llvm-project/releases/tag/llvmorg-9.0.0))?

**Comment by aykevl** [comment]
Why? That tag points to a much older commit on the LLVM 9 branch. This is more recent (and us currently used):

**Comment by aykevl** [comment]
I was monkey-patching the PR a bit to figure out how to get it to compile.
Here is a possible fix for LLVM: https://reviews.llvm.org/D70266

**Comment by aykevl** [comment]
Hopefully I can land this change in LLVM soon. I have a patch ready but lost my commit access during the recent SVN->GitHub migration. After it has been committed to LLVM master I can request it to be backported to LLVM 9.

If all goes well, it may appear in the release/9.x branch soon. If it doesn't land in a few days, downgrading to MinGW 7.3 on Azure Pipelines also works around this issue.
In other words: I'll make sure to get this PR ready in time before the next release.

**Comment by aykevl** [comment]
I didn't want to wait so just added code to the Azure Pipelines file to downgrade MinGW before building.

This PR is now ready for review.

Before merging, [this branch](https://github.com/tinygo-org/go-llvm/tree/llvm9) should be merged in the master branch of go-llvm, using fast-forward. If it isn't done with fast-forward, the build will probably break (because the hash in go.mod doesn't match anymore). I can do that manually when this PR is accepted.

**Comment by aykevl** [comment]
I did some file size comparisons. With the various tests the file size sometimes goes up and sometimes goes down. But with bigger programs the file size goes down significantly: testdata/stdlib.go goes down by 1.8% for both wasm and armv6m and 0.4% for linux/amd64. Not massive, but in compiler terms this is very significant.

**Comment by aykevl** [comment]
:tada:

**Pull request merged**
