### PR TITLE
Nucleo stm32l432

### PR DESCRIPTION
**Pull request by kenbell**
Adds basic support for the board (UART and LED).

Because UART function is on different alt funcs for Tx/Rx, extended common UART code to support that.

### CODE REVIEW

**Comment by kenbell** [comment]
NOTE: this doesn't currently use the unified tick / sleep timer logic in PR #1673  - depending on which change merged first, will adapt the other to match.

**Comment by deadprogram** [comment]
@kenbell you can now please resolve your (expected) merge conflict since #1673 has been merged. Thanks!

**Comment by kenbell** [comment]
@deadprogram - thanks.  I think this is good to go now

**Comment by deadprogram** [comment]
Hello @kenbell still seems to be a merge conflict here.

**Comment by kenbell** [comment]
@deadprogram sorry about that.  Should be fixed now.

**Comment by deadprogram** [comment]
OK, now it is a different file that is conflicting. Probably having to do with your other PR that was just merged earlier.

**Comment by kenbell** [comment]
@deadprogram yeah, I think that caused it.  I've rebased.

Looks like test-llvm11-go116 is breaking now.  I don't think it's the code?  I can't see the output of that test, but I don't think there's anything here that would be go version specific.

**Comment by deadprogram** [comment]
@kenbell I understand that the scope of this had to grow a little due to needing to have separate Rx/Tx alt function setup for the STM32L4 but this looks good to me. 

I would just suggest squash https://github.com/tinygo-org/tinygo/pull/1710/commits/e6f8b45ceffdad5ac37a625817afa8186a4a56c0 https://github.com/tinygo-org/tinygo/pull/1710/commits/704a17e15cf642cc09fc744a28afae0efd56f917 and https://github.com/tinygo-org/tinygo/pull/1710/commits/f0424311865fa366656ee4735a226f1398c5e8a3 into a single commit. The other two commits are fine as they are IMO.

**Comment by kenbell** [comment]
@deadprogram - sure thing, have merged.

**Comment by deadprogram** [comment]
Thanks @kenbell now merging.

**Pull request merged**
