### PR TITLE
compiler: extend flash command to support different output file types

### PR DESCRIPTION
**Pull request by deadprogram**
This PR addresses #142 by extending the `tinygo flash` command to support different output file types based on contents of flash key in target file.

For example, the target file `microbit.json`

```json
"flash": "openocd -f interface/cmsis-dap.cfg -f target/nrf51.cfg -c 'program {hex} reset exit'",
```

will continue to compile a `.hex` file becase the token in the `flash` key is `{hex}`.

Modifying the target file `itsybitsy-m0.json` like this:

```json
"flash": "uf2conv.py {bin}"
```

will compile a `.bin` file before trying to execute the flashing command.

### CODE REVIEW

**Comment by aykevl** [comment]
It seems to me that this was never really necessary, this works just fine for me:

```json
{
    "flash": "/home/ayke/src/uf2/utils/uf2conv.py {hex}"
}
```

**Comment by deadprogram** [comment]
This seemed to be the case for me: https://github.com/Microsoft/uf2/issues/3

**Comment by aykevl** [comment]
Well, it actually works for me. Program seems to work fine.

**Comment by deadprogram** [comment]
I know I have that problem if I used the bossac bootloader. In any case, it does set up the next part which will be a pure Go solution to replace that Python script.

**Comment by aykevl** [comment]
Oh that would be really nice. To eliminate dependencies one by one.

**Pull request merged**
