### PR TITLE
nrf: add support for SoftDevices to PCA10040 board

### PR DESCRIPTION
**Pull request by aykevl**
This is a work in progress.

### CODE REVIEW

**Comment by deadprogram** [comment]
This is very exciting to see the progress here!

**Comment by aykevl** [comment]
Cleaned up this PR, it's finally ready for review!
All commits except for the last have already been sent for review in other PRs.

**Comment by aykevl** [comment]
Rebased to avoid conflicts.

**Comment by deadprogram** [comment]
So the actual softdevice bits do not get flashed in with the firmware with this PR, correct? You must use some separate flashing tool to put it into the correct location.

Also, where is the code that then uses this code again?

**Comment by aykevl** [comment]
See https://github.com/aykevl/go-bluetooth. I have added examples and the commands to flash the SoftDevice.

**Comment by deadprogram** [comment]
:satellite: now merging.

**Comment by aykevl** [comment]
Awesome! :tada:

This has been a lot of work over a long period, to get to this point. Having CGo support will also enable other projects to make use of existing code (written in C/C++) to be usable with TinyGo.

**Pull request merged**
