### PR TITLE
cgo: implement structs, arrays, and unions

### PR DESCRIPTION
**Pull request by aykevl**
I think this covers the majority of C types.

### CODE REVIEW

**Comment by aykevl** [comment]
I'm afraid I made a mistake... I think https://circleci.com/gh/tinygo-org/tinygo/515 is related to the first commit in this PR.

**Comment by deadprogram** [comment]
I have run into a number of structs that contain a union, it would be great to also accommodate that case.

**Comment by aykevl** [comment]
I haven't tested it but in theory that should also be covered. Maybe useful to add as a test, just to be sure.

**Comment by aykevl** [comment]
Sure enough, this results in a compiler error (actually, `panic: expected field inside cursor`):

```c
typedef struct collection {
    short         s;  
    long          l;  
    float         f;  
    unsigned char c;
    union {
        int   a;
        float b;
    };
} collection_t;
```

**Comment by deadprogram** [comment]
So, should we merge this PR now, or work on it further to address the nested union error you mention above? I vote to merge sooner, and then add in a future iteration.

**Comment by aykevl** [comment]
> I'm afraid I made a mistake... I think the error in https://circleci.com/gh/tinygo-org/tinygo/515 is related to the first commit in this PR.

Well I found the root cause. CXCursor.data is an array of 3 pointers, but the middle one usually contains 0x1, which is not a real pointer. This happens to work on Linux but not on macOS.

**Comment by aykevl** [comment]
From my POV it can be merged.

**Pull request merged**
