### PR TITLE
WIP: Reflection

### PR DESCRIPTION
**Pull request by aykevl**

### CODE REVIEW

**Comment by deadprogram** [comment]
Seems like this branch is possibly complete enough to merge in. It does have its own tests, and it passes the other tests.

It needs another update to bring it in line with the current `master` but after that, perhaps it should be landed.

This should also be accompanied with some documentation somewhere about the state of the reflection feature, and what is still missing.

@aykevl what do you think?

**Comment by aykevl** [comment]
Yeah I think this could be merged. I've intentionally kept it so that it can be merged at each point.
Of course, it's far from complete, and some parts of it might need to be redesigned. For example, there is no support for structs or named types, which are perhaps the most useful feature of reflection.

**Comment by deadprogram** [comment]
Now merging into `dev` branch for integration. Great work on this @aykevl

**Comment by han2015** [comment]
HI @aykevl 

> Many packages, especially in the standard library, rely on reflection to work. 

This branch have been merged, that means we can use more standard libraries now?
 about doc, It's more friendly if add the supported packages list in doc.

**Comment by aykevl** [comment]
> This branch have been merged, that means we can use more standard libraries now?

Yes. For example, this was necessary to support the fmt package.

> about doc, It's more friendly if add the supported packages list in doc.

That's indeed on the todo list. It should be autogenerated so it can easily be updated.

**Pull request merged**
