### PR TITLE
Provide Set/Get for each register field described in SVD files.

### PR DESCRIPTION
**Pull request by zdima**
This is a work around for ReplaceBits implementation, which is not working properly with masks defined in device/*.go generated from SVD (issue #2166). It is based on @aykevl suggestion to supply "every register has methods like SetSOC_CLK_SEL for a register like esp.SYSTEM.SYSCLK_CONF."
This PR define a type for each register and such type provides Set/Get functions for each field deigned by SVD file.
The PR also include fixes in source files due to register's type change and which identified by smoketest.

### CODE REVIEW

**Comment by aykevl** [comment]
Overall this looks good, but there is an issue: binary size increases in the drivers repo. I haven't investigated yet why this is the case. The biggest increase is for `tinygo build -size short -o ./build/test.hex -target=wioterminal ./examples/rtl8720dn/webclient/`, which increases from 129356 to 129868 bytes in code size.

(I've used [`sizediff`](https://gist.github.com/aykevl/bc593ce06b22d64d8dcbb335a40a1e40#file-sizediff) to compare the difference in size before and after, with the output from `make smoke-test`).

**Comment by zdima** [comment]
@aykevl, what dev revision do you use to build for wioterminal? I think I am missing something.
I want to build revision I have branched (c8719f8d143dc7388289a9806dd076916f0bdd94) and getting build errors in picolibc: 

```
$ git checkout $VER 
$ go build 
$ go install
$ tinygo clean
$ make gen-device-sam 
$ cd ../tinygo-drivers
$ tinygo build -size short -o ./build/test-$VER.hex -target=wioterminal ./examples/rtl8720dn/webclient/

/Users/zdima/WorkFolder/tinygo-test/lib/picolibc-stdio.c:16:13: error: array initializer must be an initializer list
FILE *const stdin = &__stdio;
            ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/stdio.h:276:16: note: expanded from macro 'stdin'
#define stdin (__iob[0])
               ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc-stdio.c:17:27: error: alias definition of '__iob' after tentative definition
__strong_reference(stdin, stdout);
                          ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/stdio.h:282:17: note: expanded from macro 'stdout'
#define stdout (__iob[1])
                ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc-stdio.c:16:13: note: previous definition is here
FILE *const stdin = &__stdio;
            ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/stdio.h:276:16: note: expanded from macro 'stdin'
#define stdin (__iob[0])
               ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc-stdio.c:18:27: error: alias definition of '__iob' after tentative definition
__strong_reference(stdin, stderr);
                          ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/stdio.h:288:17: note: expanded from macro 'stderr'
#define stderr (__iob[2])
                ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc-stdio.c:16:13: note: previous definition is here
FILE *const stdin = &__stdio;
            ^
/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/stdio.h:276:16: note: expanded from macro 'stdin'
#define stdin (__iob[0])
               ^
3 errors generated.
clang-11: error: no such file or directory: '/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/asprintf.c'
clang-11: error: no input files
clang-11: error: no such file or directory: '/Users/zdima/WorkFolder/tinygo-test/lib/picolibc/newlib/libc/tinystdio/atod_engine.c'
clang-11: error: no input files
error: failed to build /Users/zdima/WorkFolder/tinygo-test/lib/picolibc-stdio.c: exit status 1

```

**Comment by aykevl** [comment]
> what dev revision do you use to build for wioterminal

I'm using the parent revision of your branch, the same as you.

You need to run `git submodule update --init` to fix those picolibc build errors. You can see this issue by running `git status`, which shows that the submodule was updated.

**Comment by zdima** [comment]
@aykevl , Looks like the generated code has extra checks due to new types.
For example, it was `INTFLAG volatile.Register8`.
Now it is a type with method:
```
INTFLAG SERCOM_USART_INT_INTFLAG_Type
...
type SERCOM_USART_INT_INTFLAG_Type struct{ volatile.Register8 }
```

This is new IR code:

```
gep.next2:                                        ; preds = %deref.next
  %4 = getelementptr inbounds %"device/sam.SERCOM_USART_EXT_Type", %"device/sam.SERCOM_USART_EXT_Type"* %2, i32 0, i32 18, !dbg !139356
--- extra code start here
  br i1 false, label %gep.throw3, label %gep.next4, !dbg !139356

gep.throw3:                                       ; preds = %gep.next2
  call void @runtime.nilPanic(i8* undef, i8* null), !dbg !139356
  unreachable, !dbg !139356

gep.next4:                                        ; preds = %gep.next2
  %5 = getelementptr inbounds %"device/sam.AC_COMPCTRL_Type", %"device/sam.AC_COMPCTRL_Type"* %4, i32 0, i32 0, !dbg !139356
--- extra code end here
  %6 = call i32 @"(*runtime/volatile.Register32).Get"(%"runtime/volatile.Register32"* %5, i8* undef, i8* undef), !dbg !139357
  %7 = and i32 %6, 255, !dbg !139358
  %8 = trunc i32 %7 to i8, !dbg !139359
  call void @"(*machine.UART).Receive"(%machine.UART* %uart, i8 %8, i8* undef, i8* undef), !dbg !139360
  call void @llvm.dbg.value(metadata %machine.UART* %uart, metadata !139350, metadata !DIExpression()), !dbg !139361
  br i1 false, label %gep.throw5, label %gep.next6, !dbg !139362

```

This is old:
```
gep.next2:                                        ; preds = %deref.next
  %4 = getelementptr inbounds %"device/sam.SERCOM_USART_EXT_Type", %"device/sam.SERCOM_USART_EXT_Type"* %2, i32 0, i32 18, !dbg !34026
  %5 = call i32 @"(*runtime/volatile.Register32).Get"(%"runtime/volatile.Register32"* %4, i8* undef, i8* undef), !dbg !34027
  %6 = and i32 %5, 255, !dbg !34028
  %7 = trunc i32 %6 to i8, !dbg !34029
  call void @"(*machine.UART).Receive"(%machine.UART* %uart, i8 %7, i8* undef, i8* undef), !dbg !34030
  call void @llvm.dbg.value(metadata %machine.UART* %uart, metadata !34020, metadata !DIExpression()), !dbg !34031
  br i1 false, label %gep.throw3, label %gep.next4, !dbg !34032

```

**Comment by aykevl** [comment]
How did you capture the IR?

This code:
```llvm
  br i1 false, label %gep.throw3, label %gep.next4, !dbg !139356
```

is a `br i1 false`, which is normally optimized away (it's essentially the same thing as `if false {`).

**Comment by zdima** [comment]
> How did you capture the IR?

I use -printir option.

> is a `br i1 false`, which is normally optimized away (it's essentially the same thing as `if false {`).

But it's follow by additional calls. Not sure that will be optimized.
```
gep.throw3:                                       ; preds = %gep.next2
  call void @runtime.nilPanic(i8* undef, i8* null), !dbg !139356
  unreachable, !dbg !139356

gep.next4:                                        ; preds = %gep.next2
  %5 = getelementptr inbounds %"device/sam.AC_COMPCTRL_Type", %"device/sam.AC_COMPCTRL_Type"* %4, i32 0, i32 0, !dbg !139356

```
Is there a way to gat asm file? 
objdump -D hard to read.

**Comment by zdima** [comment]
@aykevl 
If I change new type to alias instead:
`type SERCOM_USART_INT_INTFLAG_Type struct{ volatile.Register8 }`
to
`type SERCOM_USART_INT_INTFLAG_Type volatile.Register8`
, the size is become even larger and I have to implement all replacement methods of Register* type.

I can't change it to `type SERCOM_USART_INT_INTFLAG_Type struct{ Reg uint8 }` as this will break code returning Register* based on condition. For example: https://github.com/tinygo-org/tinygo/blob/06df31944c6af706d6cb8b30a2e92d19060436d2/src/device/nxp/mimxrt1062_clock.go#L338

**Comment by zdima** [comment]
Submitted another https://github.com/tinygo-org/tinygo/pull/2325 to address binary size.

**Pull request closed without merging**
