### PR TITLE
Added missing TCPAddr and UDPAddr implementations to the net package

### PR DESCRIPTION
**Pull request by waj334**

### CODE REVIEW

**Comment by waj334** [comment]
#3432 Will fix the failing build

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by dgryski** [comment]
#3432 is merged; this can be rebased now.

**Review by dgryski — APPROVED** [review]
LGTM.  Ignore flaky windows for now I guess.

**Review by soypat — APPROVED** [review]
LGTM!

**Comment by wzekin** [comment]
@dgryski any progress? my code relies on this.

**Comment by dgryski** [comment]
This PR doesn't need to add `internal/itoa`, since we use the upstream version.  That first commit should be altered and second two commits removed when the entire PR rebased against a current dev branch.

**Comment by waj334** [comment]
I'll fix this up tonight

**Comment by soypat** [comment]
@scottfeldman Scott, are you not adding these types in your PR as well?

**Comment by scottfeldman** [comment]
Yes, the netdev PR adds TCPAddr/UDPAddr types to "net" package.

**Comment by dgryski** [comment]
@scottfeldman How long until your PR is merged?  Could we split some of those changes into a separate PR with the "easy" stuff to get it merged and leave the "harder" stuff for later review?

**Comment by scottfeldman** [comment]
@dgryski I don't know how long.  It's a large PR.  Yes, doing a separate PR would probably work.  I can look into it.

**Comment by waj334** [comment]
All fixed up! I also went ahead and added the missing methods for IPAddr.

**Review by dgryski — APPROVED** [review]
LGTM.

**Comment by scottfeldman** [comment]
LGTM.  To not hold things up, pull this PR and I'll rebase my PR.

**Pull request merged**
