### PR TITLE
Fix regression in maps after running interp per package

### PR DESCRIPTION
**Pull request by aykevl**
The bug https://github.com/tinygo-org/tinygo/issues/1805 was introduced in #1758. This PR fixes this issue by removing the affected code entirely. This is why the bugfix doesn't come with a test: I'm not sure how I would test code that isn't there anymore.

To make that work, I had to fix a bug in the interp package that I found while working on this change.

I expected a small reduction in code size, but that didn't happen. The code in testdata/map.go is affected, but it's only reduced in size. I haven't investigated why. All other code (even rather extensive tests such as testdata/json.go) are not affected, which is great. This shows that the special map support in the interp package was never really needed.

### CODE REVIEW

**Comment by dkegel-fastly** [comment]
Seems to solve the problem here.

**Comment by aykevl** [comment]
Apparently I did not test enough, the testdata/map.go test is failing. I will need to investigate this further.

**Comment by aykevl** [comment]
Looks like I fixed it (see commit message for details).

**Comment by deadprogram** [comment]
Great work @aykevl! Now merging.

:world_map:

**Pull request merged**
