### PR TITLE
sam: remove redundant build tags

### PR DESCRIPTION
**Pull request by aykevl**
Some build tags were duplicated. This commit removes them.

### CODE REVIEW

**Review by sago35 — CHANGES_REQUESTED** [review]
Please add arduino-zero.json.
The other files did not have duplicate tags.

```json
{
    "inherits": ["atsamd21g18a"],
    "build-tags": ["arduino_zero"],
    "flash-command": "bossac -i -e -w -v -R -U --port={port} --offset=0x2000 {bin}",
    "flash-1200-bps-reset": "true"
}
```


I checked with the following command

```
$ tinygo targets | xargs -n 1 tinygo info
```

**Comment by aykevl** [comment]
Oops I missed that one somehow, thank you! Now fixed.

**Review by sago35 — APPROVED** [review]

**Comment by sago35** [comment]
Looks good to me.

**Comment by deadprogram** [comment]
Thanks @ayke now merging.

**Pull request merged**
