### PR TITLE
src/{syscall, os}: add Fstat, with tests

### PR DESCRIPTION
**Pull request by dkegel-fastly**
This is the Fstat part of https://github.com/tinygo-org/tinygo/pull/2371, plus tests and a windows implementation.

### CODE REVIEW

**Comment by dkegel-fastly** [comment]
Beyond the current build failure, I think this doesn't work on wasi yet.

**Comment by dkegel-fastly** [comment]
On wasi, I think this requires https://github.com/tinygo-org/tinygo/pull/2469 before it'll pass.
On i386 and arm, it seems to need syscall.seek to be implemented, not sure why.
( cf. https://github.com/tinygo-org/tinygo/issues/1906 ).

**Comment by dkegel-fastly** [comment]
This now works around #1906 by leaving Fstat a stub on i386-linux and arm-linux.

The workaround is a single commit that should be reverted once tinygo supports go assembly.

**Comment by dkegel-fastly** [comment]
May need a tweak to let wasi tests pass still.  I will push a new version tonight.

**Review by dgryski — APPROVED** [review]
LGTM.  Can we add `archive/zip` to the passing tests yet?

**Comment by dkegel-fastly** [comment]
Oh, yeah, when I rebase tonight I will try adding that.

**Comment by dkegel-fastly** [comment]
archive/zip is not passing on wasi yet, so I added it to the passing-on-native-tests list.

I don't quite understad *why* it isn't passing on wasi... probably means this pull request isn't fully baked yet.

**Comment by dkegel-fastly** [comment]
Also not passing on windows.  Back to the kitchen!

**Comment by dgryski** [comment]
Started looking into why it's not passing on wasi and fell down the rabbit hole of `io/fs` interfaces and implementations.

**Comment by dkegel-fastly** [comment]
I broke my gaze away from that, too.

**Comment by dkegel-fastly** [comment]
aha, archive/zip failure on windows is expected, it needs ReadAt.  Excluding that test on windows.

**Comment by dgryski** [comment]
The `TestFSModTime` test (which is the failing test on wasi) passes when run independently.  This points to a garbage collection issue or similar.  However, running with `gcAsserts = true`  fails:

This is worth opening its own bug for.

```
~/go/src/go.googlesource.com/go/src/archive/zip $ tinygo test -target=wasi archive/zip
panic: runtime error: gc: metadata array is too small
Error: failed to run main module `/var/folders/5b/_hr1d1fd3qn4t9vtfx5p61wm0000gp/T/tinygo272422465/main`

Caused by:
    0: failed to invoke command default
    1: wasm trap: wasm `unreachable` instruction executed
       wasm backtrace:
           0: 0x9bc6 - <unknown>!runtime.runtimePanic
           1: 0x23d43 - <unknown>!runtime.calculateHeapAddresses
           2: 0x2d431 - <unknown>!_start
       note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable to may show more debugging information

FAIL	archive/zip	2.088s
```

**Comment by dkegel-fastly** [comment]
Let's land this now, link to the new bug, and deal with that later.

**Comment by dgryski** [comment]
Filed https://github.com/tinygo-org/tinygo/issues/2554

**Comment by dkegel-fastly** [comment]
Ship it!

**Comment by deadprogram** [comment]
OK that was a bit complicated to follow at first, but I understand the reasoning behind how this PR is setup. Merging, counting on you both @dkegel-fastly and @dgryski to help get it sorted out once the "real" solution is available.

**Pull request merged**
