### PR TITLE
Remove SimpleDCE and add compiler testing

### PR DESCRIPTION
**Pull request by aykevl**
The first commit removes most of the ir package and either moves the code to compiler/symbol.go or removes it altogether. After this, not much remains of the ir package and it should be removed eventually.

The second commit relies on the added flexibility provided by the first commit to add testing to the compiler package. It only contains one very basic test but it provides a framework for future tests to be added in a similar way.

Warning: this PR may have consequences. I found that the image/png package stopped compiling due to a bug in the compiler (it produces invalid IR), probably because a function that previously was removed with SimpleDCE is now included in the build. It also slows down the compiler significantly, I've measured +12% (driver smoke tests) to +53% (tinygo smoke tests) increase in compile time. However, this PR is one of the many changes necessary to allow packages to be compiled independently which should eventually speed up the compiler by compiling packages in parallel and caching already compiled packages.

Replaces #466.

### CODE REVIEW

**Comment by deadprogram** [comment]
This PR now has merge conflicts that need to be resolved.

**Comment by aykevl** [comment]
Rebased. This PR should not be merged before the next release, it's too big and invasive and relies on followup changes (not yet made) to shrink compile time again.

**Comment by aykevl** [comment]
> I found that the image/png package stopped compiling due to a bug in the compiler (it produces invalid IR), probably because a function that previously was removed with SimpleDCE is now included in the build.

This regression has now been fixed by #1040.

**Comment by aykevl** [comment]
This PR has been superseded by other (merged) PRs.

**Pull request closed without merging**
