### PR TITLE
machine/samd51: implement Flash interface

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds the implementation of the Flash interface for the samd51 processor in similar fashion to #3496 did for samd21.

### CODE REVIEW

**Comment by akif999** [comment]
I tried the following and confirmed that it works.

* host OS
    * Windows11 64bit
* rev
     * 10610cd4763ad1ca8a505e8dc4d40fbeaa3faef5
* target board
     * Adafruit Feather-m4 express
* user program
     * https://github.com/tinygo-org/tinygo/tree/10610cd4763ad1ca8a505e8dc4d40fbeaa3faef5/src/examples/flash
 
```
$ tinygo flash -target=feather-m4 -size=short -monitor .
   code    data     bss |   flash     ram
   9428     164    6680 |    9592    6844
Connected to COM14. Press Ctrl-C to exit.
Flash data start:       0x00008000
Flash data end:         0x00080000
Flash data size, bytes: 491520
Flash write block size: 8
Flash erase block size: 8192

Reading data from flash: 1234567887654321123456788765432112345678876543211234567887654321
Writing data to flash: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Reading data back from flash: 1234567887654321123456788765432112345678876543211234567887654321
```

**Comment by deadprogram** [comment]
Thanks for testing @akif999 

@bgould do you have a way to verify this with TinyFS? Or alternative, can you point me to whatever you changed to do the test, so I can use it as well? :smile_cat:

**Comment by bgould** [comment]
Preliminary testing didn't work on Feather M4 Express.

This is the branch/example I've been using for testing: https://github.com/tinygo-org/tinyfs/blob/machine-flash/examples/console/littlefs/machine/main.go

```
~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ tinygo flash -target feather-m4 .

~/src/tinyfs/examples/console/littlefs/machine (machine-flash)
$ winpty python -m serial.tools.miniterm COM20
--- Miniterm on COM20  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

==> lsblk

-------------------------------------
 Device Information:
-------------------------------------
 flash data start: 0001A000
 flash data end:  00080000
-------------------------------------

==> format
Could not format LittleFS filesystem: littlefs: No space left on device

==> mount
Successfully mounted LittleFS filesystem.

==> ls
==> write test.txt
error opening test.txt: littlefs: File name too long
==>
```

**Comment by bgould** [comment]
On second try, still got some errors but actually if I ignore them and it kind of starts to work fine

```
$ winpty python -m serial.tools.miniterm COM20
--- Miniterm on COM20  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

==> lsblk

-------------------------------------
 Device Information:
-------------------------------------
 flash data start: 0001A000
 flash data end:  00080000
-------------------------------------

==> mount
Successfully mounted LittleFS filesystem.

==> ls
==> samples
error opening file0.txt: littlefs: File name too long
==> samples
wrote 90 bytes to file0.txt
wrote 90 bytes to file1.txt
wrote 90 bytes to file2.txt
wrote 90 bytes to file3.txt
wrote 90 bytes to file4.txt
==> ls
-rwxrwxrwx    90 file0.txt
-rwxrwxrwx    90 file1.txt
-rwxrwxrwx    90 file2.txt
-rwxrwxrwx    90 file3.txt
-rwxrwxrwx    90 file4.txt
==> cat file0.txt
00000000: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f     !"#$%&'()*+,-./
00000010: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f    0123456789:;<=>?
00000020: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f    @ABCDEFGHIJKLMNO
00000030: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f    PQRSTUVWXYZ[\]^_
00000040: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f    `abcdefghijklmno
00000050: 70 71 72 73 74 75 76 77 78 79                      pqrstuvwxy
==>
```

**Comment by deadprogram** [comment]
That still does not seem correct. I pushed one more small set of changes, please see if that appears to make any different if you get a chance.

**Comment by bgould** [comment]
Awesome, seems to be working now:

```
--- Miniterm on COM20  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

==> lsblk

-------------------------------------
 Device Information:
-------------------------------------
 flash data start: 0001A000
 flash data end:  00080000
-------------------------------------

==> format
Successfully formatted LittleFS filesystem.

==> mount
Successfully mounted LittleFS filesystem.

==> ls
==> samples
wrote 90 bytes to file0.txt
wrote 90 bytes to file1.txt
wrote 90 bytes to file2.txt
wrote 90 bytes to file3.txt
wrote 90 bytes to file4.txt
==> cat file0.txt
00000000: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f     !"#$%&'()*+,-./
00000010: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f    0123456789:;<=>?
00000020: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f    @ABCDEFGHIJKLMNO
00000030: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f    PQRSTUVWXYZ[\]^_
00000040: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f    `abcdefghijklmno
00000050: 70 71 72 73 74 75 76 77 78 79                      pqrstuvwxy
==> rm file2.txt
==> ls
-rwxrwxrwx    90 file0.txt
-rwxrwxrwx    90 file1.txt
-rwxrwxrwx    90 file3.txt
-rwxrwxrwx    90 file4.txt
==>
```

LGTM

**Review by bgould — APPROVED** [review]

**Comment by deadprogram** [comment]
Thank you very much for the reviews and testing @bgould and @akif999 :heart: 

Now merging.

**Pull request merged**
