### PR TITLE
rp2040: add support for EnterBootloader()

### PR DESCRIPTION
**Pull request by sago35**
It should be merged after #2989

This PR adds flash-1200-bps-reset support to the rp2040.
In other words, the BOOTSEL button no longer needs to be pressed.
(Of course, if something goes wrong, you will need BOOTSEL)

### CODE REVIEW

**Comment by sago35** [comment]
Seems to be a flash failure from linux when in bootloader.
A few fixes are needed.

**Comment by deadprogram** [comment]
There just has to be a way to avoid all of those changes in https://github.com/tinygo-org/tinygo/pull/2990/commits/7559556e32c84d9c1da0e110c9bc55d28dafcc1e

Let me look at it a little more in depth.

**Comment by deadprogram** [comment]
After this commit https://github.com/tinygo-org/tinygo/pull/2990/commits/004646300f03666e55bacb37b89de8feb2d57374 the blinky1 program no longer runs. So something not quite right! I am using a brand new pico I got at Embedded World.

**Comment by sago35** [comment]
What OS are you using?

**Comment by sago35** [comment]
@deadprogram 
Adjusted the period for returning ACKs.
This would solve the timing problem.

**Comment by deadprogram** [comment]
I tested this branch with all the commits except for 7559556e32c84d9c1da0e110c9bc55d28dafcc1e (change to ignore PortReset failures) and it worked perfectly!

My OS: `Ubuntu 20.04.4 LTS`

My kernel:

```
$ uname -a
Linux ron-XPS-13-7390 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

How should we proceed?

**Comment by sago35** [comment]
In order to split the PR, the following was made into a separate PR

* #2992

**Comment by deadprogram** [comment]
Needs rebase/merge conflict resolved please, @sago35

**Comment by sago35** [comment]
@deadprogram Rebased.

**Comment by deadprogram** [comment]
Haha! I typed that last message at the same time you did the rebase. Or maybe you were just a little quicker!

**Comment by deadprogram** [comment]
Great work @sago35 now merging.

**Pull request merged**
