### PR TITLE
machine/usb/hid: fix hidreport (2)

### PR DESCRIPTION
**Pull request by sago35**
MediaKey initialization is failing due to issue #3719.
I changed the code a little to make it work.

### CODE REVIEW

**Review by aykevl — COMMENTED** [review]
Huh, that's odd, I don't see why the code would have changed.
Any idea what causes this bug? (I'm wary of changes that are just "to make things work" without a good explanation as to why they work).

---

Also, it looks like CI is failing because the musl submodule fails.

**Comment by sago35** [comment]
@aykevl 
I have no idea, but I suspect that the code in the following state is not working? I am thinking that it is not working.

* file scope variable
* PutUint16() in the initialization binary.LittleEndian.
    * Maybe there is a little more to it than that, I don't know what it is.

**Comment by sago35** [comment]
> I'm wary of changes that are just "to make things work" without a good explanation as to why they work

I have the same idea.
However, if this is not working well, my project will not work well.

**Comment by deadprogram** [comment]
I prefer the simpler code in this case anyhow. But we should investigate further.

**Comment by deadprogram** [comment]
While we investigate, I am going to merge this to avoid breaking @sago35 other code. Thanks for the fix!

**Pull request merged**
