### PR TITLE
gomod: update chromedp module

### PR DESCRIPTION
**Pull request by leongross**
The CI for signal-unix fails with

```
setup_test.go:124: Started server at "http://127.0.0.1:41079/" for dir: /tmp/TestChan2059857126/001
    setup_test.go:28: Command: tinygo build -o /tmp/TestChan2059857126/001/chan.wasm -target wasm testdata/chan.go; err=<nil>; full output:
    setup_test.go:43: failed to start browser: chrome failed to start:
        [194871:194871:1016/152617.392419:FATAL:zygote_host_impl_linux.cc(128)] No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise seehttps://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
        #0 0x55a2cb91b552 base::debug::CollectStackTrace()
        #1 0x55a2cb90872e base::debug::StackTrace::StackTrace()
        #2 0x55a2cb85d94a logging::LogMessage::Flush()
        #3 0x55a2cb85e4e9 logging::LogMessageFatal::~LogMessageFatal()
        #4 0x55a2c9a6e40e content::ZygoteHostImpl::Init()
        #5 0x55a2cad3ba9c content::ContentMainRunnerImpl::Initialize()
        #6 0x55a2cad3999c content::RunContentProcess()
        #7 0x55a2cad39dc7 content::ContentMain()
        #8 0x55a2c68d1380 ChromeMain
        #9 0x7f9c7ce2a1ca (/usr/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
        #10 0x7f9c7ce2a28b __libc_start_main
        #11 0x55a2c68d102a _start
        Crash keys:
          "switch-32" = "about:blank"
          "switch-31" = "--use-angle=swiftshader-webgl"
          "switch-30" = "--ozone-override-screen-size=800,600"
          "switch-29" = "--ozone-platform=headless"
          "switch-28" = "--noerrdialogs"
          "switch-27" = "--remote-debugging-port=0"
          "switch-26" = "--user-data-dir=/tmp/chromedp-runner647325871"
          "switch-25" = "--disable-ipc-flooding-protection"
          "switch-24" = "--disable-backgrounding-occluded-windows"
          "switch-23" = "--mute-audio"
          "switch-22" = "--disable-popup-blocking"
          "switch-21" = "--password-store=basic"
          "switch-20" = "--enable-automation"
          "switch-19" = "--disable-client-side-phishing-detection"
          "switch-18" = "--disable-background-networking"
          "switch-17" = "--no-default-browser-check"
          "switch-16" = "--headless"
          "switch-15" = "--disable-renderer-backgrounding"
          "switch-14" = "--disable-extensions"
          "switch-13" = "--disable-default-apps"
          "switch-12" = "--hide-scrollbars"
          "switch-11" = "--disable-background-timer-throttling"
          "switch-10" = "--use-mock-keychain"
          "switch-9" = "--metrics-recording-only"
          "switch-8" = "--disable-prompt-on-repost"
          "switch-7" = "--disable-dev-shm-usage"
          "switch-6" = "--no-first-run"
          "switch-5" = "--safebrowsing-disable-auto-update"
          "switch-4" = "--disable-sync"
          "switch-3" = "--disable-breakpad"
          "switch-2" = "--force-color-profile=srgb"
          "switch-1" = "--disable-hang-monitor"
          "num-switches" = "34"
          "commandline-disabled-feature-3" = "BlinkGenPropertyTrees"
          "commandline-disabled-feature-2" = "Translate"
          "commandline-disabled-feature-1" = "site-per-process"
          "commandline-enabled-feature-2" = "NetworkServiceInProcess"
          "commandline-enabled-feature-1" = "NetworkService"
          "osarch" = "x86_64"
          "pid" = "194871"
          "ptype" = "browser"
```

Update the chromium driver to prohibit crashing.

### CODE REVIEW

**Comment by aykevl** [comment]
It might fix it, but because it's a flaky test (it only fails sometimes) it's hard to say. But updating it still seems like a good idea, there's a good chance they've fixed the flakiness already.

Can you base this PR on the dev branch (without the unix-signal commit), and run `go mod tidy`?

**Comment by aykevl** [comment]
Looking at https://github.com/tinygo-org/tinygo/actions/workflows/linux.yml, apparently the last time this failure happened was two days ago. It seems to have been a problem with CI that is now fixed by GitHub. So probably no fix needed from our side.

**Comment by leongross** [comment]
Good to know. Anyways, wouldn't it make sense to update the dependencies in general from time to time?

**Comment by aykevl** [comment]
> Good to know. Anyways, wouldn't it make sense to update the dependencies in general from time to time?

Yes, it does. Can you make a new PR for this? This PR was closed because the `unix-signal` branch was deleted after merging.

**Pull request closed without merging**
