### PR TITLE
ci: only build the necessary LLVM libraries

### PR DESCRIPTION
**Pull request by aykevl**
This should improve rebuild time, but perhaps more importantly massively reduces cache size which then reduces incremental build time.

### CODE REVIEW

**Comment by aykevl** [comment]
This needs some changes for Windows.

**Comment by sago35** [comment]
I made the following changes and was able to build on Windows 10
We need to change lib/libclang.a to lib/liblibclang.a.

source : cca0eab3da7065d568ca073df61f03beecbd2086

```diff
diff --git a/Makefile b/Makefile
index 69eacad..0b1c54b 100644
--- a/Makefile
+++ b/Makefile
@@ -74,6 +74,10 @@ CLANG_LIBS = $(START_GROUP) -lclangAnalysis -lclangARCMigrate -lclangAST -lclang
 
 LLD_LIBS = $(START_GROUP) -llldCOFF -llldCommon -llldCore -llldDriver -llldELF -llldMachO -llldMinGW -llldReaderWriter -llldWasm -llldYAML $(END_GROUP)
 
+# These build targets appear to be the only ones necessary to build all TinyGo
+# dependencies. Only building a subset significantly speeds up rebuilding LLVM.
+NINJA_BUILD_TARGETS = lib/liblibclang.a lib/libLLVMRuntimeDyld.a lib/libLLVMExecutionEngine.a lib/libLLVMInterpreter.a lib/libLLVMCoroutines.a lib/libLLVMCoverage.a lib/libLLVMMCJIT.a lib/libclangCodeGen.a lib/libclangDynamicASTMatchers.a lib/libclangFrontendTool.a lib/libclangHandleCXX.a lib/libclangHandleLLVM.a lib/libclangRewriteFrontend.a lib/libclangStaticAnalyzerCheckers.a lib/libclangStaticAnalyzerCore.a lib/libclangStaticAnalyzerFrontend.a lib/libclangToolingASTDiff.a lib/liblldCOFF.a lib/liblldDriver.a lib/liblldELF.a lib/liblldMinGW.a lib/liblldWasm.a llvm-config clang llvm-ar llvm-nm
+
 
 # For static linking.
 ifneq ("$(wildcard $(LLVM_BUILDDIR)/bin/llvm-config*)","")
@@ -146,7 +150,7 @@ $(LLVM_BUILDDIR)/build.ninja: llvm-source
 
 # Build LLVM.
 $(LLVM_BUILDDIR): $(LLVM_BUILDDIR)/build.ninja
-	cd $(LLVM_BUILDDIR); ninja
+	cd $(LLVM_BUILDDIR); ninja $(NINJA_BUILD_TARGETS)
 
 
 # Build wasi-libc sysroot

```

**Comment by aykevl** [comment]
Many things changed on Windows as a result of the switch to LLVM 11. Let me try to update this PR...

**Comment by aykevl** [comment]
I have updated the PR and rewritten it in a way that is more maintainable. And it now works on both Windows and Linux (and probably macOS if the tests pass).

**Comment by aykevl** [comment]
Before:

```
Found a cache from build 23089 at llvm-build-11-linux-v1-noassert
Size: 696 MiB
```

After:

```
Found a cache from build 23591 at llvm-build-11-linux-v2-noassert
Size: 185 MiB
```

This should speed up CI significantly, as a lot of time is spent restoring cached content.

The size reduction on Windows is also significant: from 3,348.6 MB to 1,149.2 MB (or 1,208.3 MB to 370.4 MB compressed, not sure why this is so much bigger than the Linux build).

**Comment by deadprogram** [comment]
Looking good now @aykevl thanks for the speedup!

Now merging.

**Pull request merged**
