### PR TITLE
reflect: Value.Set: fix direction of assignment check

### PR DESCRIPTION
**Pull request by dgryski**

### CODE REVIEW

**Comment by aykevl** [comment]
Could you maybe add a test to show the difference? For example, by assigning an integer to an empty interface (which should work now).

**Comment by dgryski** [comment]
I'll add a test.

**Comment by dgryski** [comment]
Forgot this needs `NumMethods()`, so needs to be rebased after merged after https://github.com/tinygo-org/tinygo/pull/3529

**Comment by deadprogram** [comment]
#3529 has been merged @dgryski so you can rebase this now, if you please.

**Comment by dgryski** [comment]
Rebased now that #3529 is in.

**Comment by deadprogram** [comment]
@dgryski please see failing CI

**Comment by dgryski** [comment]
Yeah, going to be related to the merge. My guess is that this will need to be combined with the other AssignableTo PR.

**Comment by dgryski** [comment]
This passes when rebased onto https://github.com/tinygo-org/tinygo/pull/3557 ;  Probably easiest to just move this commit onto that PR instead.

**Pull request closed without merging**
