### PR TITLE
Add impact on binary size as a comment to PRs

### PR DESCRIPTION
**Pull request by aykevl**
Testing this...

### CODE REVIEW

**Comment by aykevl** [comment]
Well, finally, I think this is ready for review.

The comment could be improved quite a bit, which I hope to do in follow-up PRs. This is just basic functionality.

* It can say "there is no difference" when all the hashes are the same (and skip the sizediff output entirely).
* It can say "the size didn't change, but some binaries did" (and maybe show a plain old diff?).
* If there is a difference in binary size, it can provide a short summary, something like "23 out of 112 smoke tests changed in size, of which 20 were reduced in size and 3 increased in size".

**Comment by sago35** [comment]
I have not seen the code at all.
How does it work when the smoke test is added or removed?

**Comment by aykevl** [comment]
> How does it work when the smoke test is added or removed?

The drivers repo is tested, not the smoke tests in the tinygo repo. This repository stays the same when checking out the dev branch.

**Comment by aykevl** [comment]
Can someone take a look at this PR? I think it's very important to catch regressions early.

**Comment by deadprogram** [comment]
Looking good to me! I say we merge it.

**Pull request merged**
