### PR TITLE
build: fix for macos homebrew in GH action

### PR DESCRIPTION
**Pull request by deadprogram**
This PR has a fix for macos homebrew for the GH actions build as discussed in https://github.com/Homebrew/brew/issues/15621

### CODE REVIEW

**Comment by dgryski** [comment]
CI still failed? https://github.com/tinygo-org/tinygo/actions/runs/7239840804/job/19722180236?pr=4046#step:4:320

**Comment by deadprogram** [comment]
And now not even rebuilding?

**Comment by deadprogram** [comment]
@dgryski now I think I have it correct.

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thanks for review @dgryski now merging.

**Pull request merged**
