### PR TITLE
esp32: optimize SPI transmit

### PR DESCRIPTION
**Pull request by aykevl**
For write-only operations (in SPI displays for example), the transmit speed is doubled with this relatively small change.

### CODE REVIEW

**Comment by deadprogram** [comment]
See https://github.com/tinygo-org/tinygo/runs/7529106699?check_suite_focus=true#step:10:497 for build error

**Comment by aykevl** [comment]
Oops, my Makefile was incorrect and wasn't recompiling the binary after I made some changes. The code should work now (and be even slightly faster!)

**Comment by deadprogram** [comment]
Can you please rebase against `dev` now that the CI fix is in?

**Review by deadprogram — APPROVED** [review]

**Comment by aykevl** [comment]
Rebased.

**Comment by deadprogram** [comment]
Thanks @aykevl now merging.

**Pull request merged**
