### PR TITLE
machine/stm32wl: unify implementation for RNG for stm32wl with other STM32 processors

### PR DESCRIPTION
**Pull request by deadprogram**
This PR unifies the implementation for RNG for stm32wl with other STM32 processors.

### CODE REVIEW

**Comment by deadprogram** [comment]
Please make sure this looks good to you @ofauchon thanks!

**Review by ofauchon — APPROVED** [review]
I tested this branch on Nucleo-wl55jc (stm32wl55).
Simple RNG tests passed.
LGTM

**Review by kenbell — APPROVED** [review]
lgtm

**Comment by deadprogram** [comment]
Thanks @kenbell @ofauchon now merging.

**Pull request merged**
