### PR TITLE
os: implement CreateTemp

### PR DESCRIPTION
**Pull request by dkegel-fastly**
Until tinygo implements fastrand(), use a placeholder RNG here.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thanks @dkegel-fastly now merging.

**Comment by deadprogram** [comment]
Hmm, it appears that merging this PR did not go as expected. There are now multiple failing tests in the `dev` branch.

https://app.circleci.com/pipelines/github/tinygo-org/tinygo/6157/workflows/0ebbbf04-a55a-4767-8379-0318593d29b5/jobs/34551?invite=true#step-117-283

See https://github.com/tinygo-org/tinygo/runs/4380866344?check_suite_focus=true#step:16:849

Also see https://github.com/tinygo-org/tinygo/runs/4380866344?check_suite_focus=true#step:16:1209

Thoughts @dkegel-fastly @dgryski ?

**Comment by dgryski** [comment]
Looks like constants need to be defined for the other platforms. Build tags. Bah.

**Comment by deadprogram** [comment]
Should I perhaps just revert this for now? Or will someone work on a fix right away?

**Comment by dgryski** [comment]
I'll start on a fix

**Comment by dgryski** [comment]
Fix: https://github.com/tinygo-org/tinygo/pull/2342

**Pull request merged**
