### PR TITLE
Release 0.32.0

### PR DESCRIPTION
**Pull request by aykevl**
There's still a small issue I'd like to patch before the release. But here's a changelog for when it happens.

### CODE REVIEW

**Comment by aykevl** [comment]
That small issue apparently doesn't exist.

**Comment by deadprogram** [comment]
@aykevl can you please add https://github.com/tinygo-org/tinygo/pull/4296 to the changelog and then I promise no more merges for this release :)

**Comment by leongross** [comment]
Thanks for getting this one in before the release @deadprogram @aykevl :)

**Comment by deadprogram** [comment]
Great work everyone! Now merging.

**Pull request merged**
