### PR TITLE
compiler: fix string compare functions

### PR DESCRIPTION
**Pull request by dgryski**
Before:
	x < x false
	x <= x true
	x == x true
	x >= x false
	x > x true

After:
	x < x false
	x <= x true
	x == x true
	x >= x true
	x > x false

### CODE REVIEW

**Comment by dgryski** [comment]
`sort` package tests still fail.  Investigating.

**Comment by dgryski** [comment]
Fixed. Remaining `sort` test failures are due to lack of `SkipNow()` support.

**Comment by aykevl** [comment]
Looks like you need to run `go test ./compiler -update` to update the IR.

Also, can you add some tests to testdata/binop.go that show that this bug is fixed?

**Review by aykevl — APPROVED** [review]
LGTM.

**Comment by deadprogram** [comment]
Good work on these fixes @dgryski thank you!

Now merging.

**Pull request merged**
