### PR TITLE
net: implement Pipe

### PR DESCRIPTION
**Pull request by Hrily**
Fixes: #3187 

#### Testing

This pulls in tests from official go implementation along with some helper code for the test.

### CODE REVIEW

**Review by dgryski — APPROVED** [review]
LGTM.  Are there any tests or packages using `net.Pipe` that you can use as additional tests?

**Comment by Hrily** [comment]
Hey @dgryski 

[These](https://sourcegraph.com/search?q=context:global+%22net.Pipe%22+file:_test.go+repo:%5Egithub%5C.com/golang/go%24&patternType=regexp) are the files where `net.Pipe` is used in tests. But apart from `pipe_test.go`, other files don't have their packages present in tinygo, not sure if this is a requirement for porting.

Let me know on whether it's possible to port and if so, how.

**Comment by dgryski** [comment]
No, I just meant have you tested this implementation in tinygo with other third packages that want a net.Pipe, not that those tests should be included in the tinygo repo.

**Comment by deadprogram** [comment]
Thank you for the code contribution @Hrily and to @dgryski for review. Now merging.

**Pull request merged**
