### PR TITLE
fix(wasip2): export `_initialize`

### PR DESCRIPTION
**Pull request by rvolosatovs**
Closes https://github.com/tinygo-org/tinygo/issues/4488
Refs https://github.com/tinygo-org/tinygo/pull/4482

Turns out `_initialize` was not exported by `wasip2` components and so `init()` was never called in reactors. This PR fixes that, by initializing the heap and calling all initializers, just like `run()` would normally do

Note: `wasm-tools 1.217` or later are *required* for `init()` to work in reactors (since `_initialize` is ignored in earlier versions, see https://github.com/bytecodealliance/wasm-tools/pull/1747)

Thanks @alexcrichton for assisting in debugging this in https://bytecodealliance.zulipchat.com/#narrow/stream/217126-wasmtime/topic/calling.20.60_initialize.60

### CODE REVIEW

**Comment by lxfontes** [comment]
ran same scenario as in #4482

Before
```
varHolder: {str:top ptr:0x15b30 mapStr:map[] mapPtr:map[]}
ptrHolder: &{str:top ptr:0x15b40 mapStr:map[] mapPtr:map[]}
callHolder: {str:top ptr:0x15df0 mapStr:map[a:b] mapPtr:map[c:0x16140]}
```

With this PR
```
varHolder: {str:top ptr:0x15b38 mapStr:map[a:b] mapPtr:map[c:0x15b40]}
ptrHolder: &{str:top ptr:0x15b48 mapStr:map[a:b] mapPtr:map[c:0x15b50]}
callHolder: {str:top ptr:0x164c0 mapStr:map[a:b] mapPtr:map[c:0x16720]}
```

🎉

**Review by aykevl — CHANGES_REQUESTED** [review]
With this change, if `wasi:cli/run@0.2.0#run` is called, the package initializers will be called twice. I don't think that's the intention?

**Comment by rvolosatovs** [comment]
> With this change, if `wasi:cli/run@0.2.0#run` is called, the package initializers will be called twice. I don't think that's the intention?

how about https://github.com/tinygo-org/tinygo/pull/4490/commits/03d535de3b1a726d8f532c536187a0574f5b71bf ?

**Comment by rvolosatovs** [comment]
Looking at tests, it does not look like `_initialize` is actually called for `run` implementations?
Perhaps we need to call `_initialize` from within `run` and guard by `sync.Once` or such?

**Comment by rvolosatovs** [comment]
Reworked the PR a bit - initialization is now done always, but guarded by `sync.OnceValue` - since the spec is not completely clear on the semantics here, this ensures that initialization is done for both reactors and command components.

For reactors, runtime must always call `_initialize` and for commands it may not

**Comment by aykevl** [comment]
> Looking at tests, it does not look like `_initialize` is actually called for `run` implementations?

That's not how I understand the wasip2 spec, my understanding is that `_initialize` needs to be called first in all cases but that it wasn't always done previously.

@ydnar?

**Comment by ydnar** [comment]
What version of `wasm-tools` is used to create the component? It needs at least v1.217.0: https://github.com/bytecodealliance/wasm-tools/compare/v1.216.0...v1.217.0

The relevant commit is: https://github.com/bytecodealliance/wasm-tools/commit/108c37d94fea2e1b764ecf329edbbeea1e9326b0

**Comment by ydnar** [comment]
Once #3165 lands, the `wasi:cli/command#run` export should be wired up to call `main.main` and do nothing else.

**Comment by ydnar** [comment]
Fixed in #4496.

**Comment by ydnar** [comment]
#4496 merged. Want to try `dev` branch?

**Comment by ydnar** [comment]
@rvolosatovs is still necessary? Can you verify against dev branch?

**Comment by rvolosatovs** [comment]
> @rvolosatovs is still necessary? Can you verify against dev branch?

latest `dev` branch seems to work

**Pull request closed without merging**
