### PR TITLE
docs: add submodule update step prior to 'make release'

### PR DESCRIPTION
**Pull request by brandentimm**
The instructions for 'make release' were missing a step to update submodules, which would cause the task to fail.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @brandentimm thanks for the PR.

I think maybe a better place to do this might be as part of this step: https://github.com/tinygo-org/tinygo/blob/bf3f195f6667a826f83d0b113c9cfb6164c1f723/BUILDING.md#download-the-source

What do you think?

**Comment by brandentimm** [comment]
Makes sense, I'll update it and re-submit.

**Comment by brandentimm** [comment]
@deadprogram well now I'm seeing what I initially missed in the section you referenced, the note about using --recursive when cloning.  So I think adding an additional note in there seems redundant.  

Perhaps instead we add a note in the 'make release' section calling out that if you haven't cloned recursively, you'll need to run  'git submodule update --init'?

**Comment by deadprogram** [comment]
I think by the time people see that notice about `--recursive` they will have already cloned. So maybe we should say if you have not used that flag to run the submodule command.

**Comment by aykevl** [comment]
I think this is a useful addition, so can be merged from my point of view.

**Comment by brandentimm** [comment]
I've clarified the need for submodule update in the release step.

**Comment by deadprogram** [comment]
Thank you for helping reduce friction for people getting stuck on that @brandentimm now going to squash/merge.

Thanks again!

**Pull request merged**
