### PR TITLE
net: use netdev package

### PR DESCRIPTION
**Pull request by deadprogram**
This PR uses the `net` submodule branch https://github.com/tinygo-org/net/tree/netdev3 with all of the @scottfeldman changes  and also brings in the other changed files from the commits in https://github.com/tinygo-org/tinygo/pull/3614 

If this works, it was some pretty serious rebasing to get here. Not quite as serious as the work @scottfeldman did on the original PRs, of course.

UPDATE: now using https://github.com/tinygo-org/net/tree/dev

### CODE REVIEW

**Comment by deadprogram** [comment]
The CI passed, so I squashed a few commits to clean things up. This PR is ready for testing and any additional review.

**Comment by scottfeldman** [comment]
Cool.  Is there a way to link crypto/tls directory to tinygo-org/net/crypto/tls?

**Comment by deadprogram** [comment]
> Is there a way to link crypto/tls directory to tinygo-org/net/crypto/tls?

Not really, no. To do that would require another separate git submodule `crypto`

**Comment by deadprogram** [comment]
Rebased against latest `dev`.

**Comment by deadprogram** [comment]
The size difference check will fail until this is merged into dev branch due to switching to submodule.

**Comment by deadprogram** [comment]
Now using https://github.com/tinygo-org/net/tree/dev branch. One more step closer to be able to be merged.

**Comment by deadprogram** [comment]
Rebased against latest `dev`

**Comment by deadprogram** [comment]
Rebased again against what will likely be the next release. Getting closer... :runner:

**Comment by scottfeldman** [comment]
thank you

**Comment by deadprogram** [comment]
I think we should merge this PR and the associated PR in drivers now https://github.com/tinygo-org/drivers/pull/613

@aykevl @scottfeldman @soypat @sago35 @dgryski @ysoldak @kenbell anyone else have any further comments or feedback to add?

**Comment by soypat** [comment]
@deadprogram I've been busy working on a TCP stack and I feel I could re-review the model again since I've learned so much on net stack design. Will try to get around to re-reviewing netdev model this weekend

**Comment by deadprogram** [comment]
Thanks @soypat !

**Comment by scottfeldman** [comment]
@soypat the repo/branches to review would be:

tinygo-org/tinygo  (net-submodule-netdev3)
tinygo-org/net     (dev)
tinygo-org/drivers (netdev3)

That's the combo I've been testing/developing against.

**Comment by deadprogram** [comment]
You probably will need https://github.com/tinygo-org/drivers/tree/scottfeldman-netdev3 for the drivers, which is rebased against the latest `dev` in drivers repo.

**Comment by soypat** [comment]
### Roll back net.IP, net.HardwareAddr 
I'm thinking maybe we should roll back some of these decisions due to design concerns regarding data ownership model of slices, heap allocations and performance concerns. By using immutable and stack allocated values we'd reduce complexity of working with this stack.

I just started reading and noticed we are using `net.IP` type and `net.HardwareAddress` (something I vouched for a long time ago). In my newer developments I've actually removed traces of these at the netdev API level in favor of the following

```go
import "net/netip"

type addrdev interface {
    HardwareAddrAs6() ([6]byte, error)
    Addr() (netip.Addr, error)
}
```
The benefits of `netip.Addr` have been documented by the [tailscale team](https://tailscale.com/blog/netaddr-new-ip-type-for-go/). 

As for HardwareAddrAs6, this avoids the question of "whose slice is that?". Is it returning a copy or a view into the hardware address of the Stack/Device/Adapter? Do I have to worry about heap allocations upon repeatedly calling HardwareAddr? Should I copy the value before passing it into this function that may/may not modify the contents?

I will also vouch for avoiding naming methods using `Get*` since Get implies some sort of action when a netdev could simply just return a field in it's struct. The Get idiom is also discouraged in the [Effective Go document.](https://go.dev/doc/effective_go#Getters)


### Naming
The naming: `probe.Probe` does not really tell me or I think anyone of what is happening, why the call is needed. Having different packages for netlink/probe/netdev is confusing- these packages often need one another. This on top of the `netdev.Netdever`, `probe.Probe`, and `netlink.Netlinker` which is stuttersome at best and just confusing at worse because if I put myself in the place of someone who knows a thing or two about networking I don't think I could reliably always make out which is which. They are just too similarly named or vaguely named... and often are represented by the same underlying type, which adds to the confusing aspect of it all (see composing interfaces below)!

### Other Suggestions on interface API design and naming
1. Put all three of these packages in a single unifying package to drive the point that they are supposed to be used together. This could also reduce stutter
2. Use names that evoke responsabilities of the interfaces. i.e. if we were to unify under `tinynet` (other suggested names: `afinet`, `inet`, `ethnet`, `links`, `network`) : 
   - `netlink.Netlinker` -> `tinynet.NetworkLinkEndpoint` or simply `tinynet.NetlinkEndpoint` (see gvisor)
   - `netdev.Netdever` -> `tinynet.NetworkInterface`, maybe look at gvisor
   - `probe.Probe` -> `tinynet.DefaultLink`, seems to me much more descriptive
3. Composing Interfaces: Maybe just coalesce Netlinker and Netdever interfaces? It seems to me they are composed. [Gvisor seems to also think so](https://github.com/google/gvisor/blob/master/pkg/tcpip/stack/registration.go#L703), we could probably take some inspiration from them as their interfaces seem pretty logical. The gvisor file I've linked contains pretty much any interface we could probably use in the future, I think it is very important we understand how they've structured them.
4. If we do 3 it would seem to follow that the `probe.Probe/tinynet.DefaultLink` would return a single interface since it is composed, so that's something I think we should strive for. I think it would make a lot of sense from an API usage standpoint.

As a final note I'm still working on the TCP stack and still learning about stack design and may come around to new findings.

**Comment by soypat** [comment]
Upon further thought- could we not keep the netlink+netdev+probe packages out of tinygo-drivers until they mature enough that we are comfortable with their API? I feel like we really need to sit down and start using them. We can merge the tinygo-org/tinygo PR (this one) which would expose the needed functionality to make it work with the `net` package while not exposing any API that may be subject to future breakage. I think that's a sound path to follow given the scope of these changes- we're certainly going to need to make breaking changes in the future and frustrate users of the drivers package if we rush into this.

**Comment by scottfeldman** [comment]
> You probably will need https://github.com/tinygo-org/drivers/tree/scottfeldman-netdev3 for the drivers, which is rebased against the latest `dev` in drivers repo.

Oh ya, sorry about that.  That is the correct branch.

**Comment by scottfeldman** [comment]
> Upon further thought- could we not keep the netlink+netdev+probe packages out of tinygo-drivers until they mature enough that we are comfortable with their API? I feel like we really need to sit down and start using them. We can merge the tinygo-org/tinygo PR (this one) which would expose the needed functionality to make it work with the `net` package while not exposing any API that may be subject to future breakage. I think that's a sound path to follow given the scope of these changes- we're certainly going to need to make breaking changes in the future and frustrate users of the drivers package if we rush into this.

Rush?  It's been almost a year since I sent on the RFC and no one is using the API except me because it never makes it to dev.  How do we sit down and start using them?  Frustrated.

**Comment by scottfeldman** [comment]
> ### Roll back net.IP, net.HardwareAddr
> I'm thinking maybe we should roll back some of these decisions due to design concerns regarding data ownership model of slices, heap allocations and performance concerns. By using immutable and stack allocated values we'd reduce complexity of working with this stack.

Yes, we can change them again.
 
> ### Naming
> 3. Composing Interfaces: Maybe just coalesce Netlinker and Netdever interfaces? It seems to me they are composed. [Gvisor seems to also think so]

> (https://github.com/google/gvisor/blob/master/pkg/tcpip/stack/registration.go#L703), we could probably take some inspiration from them as their interfaces seem pretty logical. The gvisor file I've linked contains pretty much any interface we could probably use in the future, I think it is very important we understand how they've structured them.
> 4. If we do 3 it would seem to follow that the `probe.Probe/tinynet.DefaultLink` would return a single interface since it is composed, so that's something I think we should strive for. I think it would make a lot of sense from an API usage standpoint.
> 
> As a final note I'm still working on the TCP stack and still learning about stack design and may come around to new findings.

I'm not sure what to do.  If I update the interfaces, they may need to change again as you learn more.  For my personal needs, I have what I need now, and if driver/stack interfaces change, I should be insulated from those changes since I'm building apps on top of "net".  

Would consider taking over on the driver/stack interfaces and develop a PR to replace mine?  I think it would get us quicker to the goal, and you're right in the middle so to speak with your stack work.  I think the tinygo-org/tinygo and tinygo-org/net PRs are ready to go; it's just the tinygo-org/drivers parts that are unsettled.  The driver/examples/net should only need minor mods, if any.  Need to make sure the existing drivers (wifinina/rtl8720/espat) work with those examples.

**Comment by scottfeldman** [comment]
> > Upon further thought- could we not keep the netlink+netdev+probe packages out of tinygo-drivers until they mature enough that we are comfortable with their API? I feel like we really need to sit down and start using them. We can merge the tinygo-org/tinygo PR (this one) which would expose the needed functionality to make it work with the `net` package while not exposing any API that may be subject to future breakage. I think that's a sound path to follow given the scope of these changes- we're certainly going to need to make breaking changes in the future and frustrate users of the drivers package if we rush into this.
> 
> Rush? It's been almost a year since I sent on the RFC and no one is using the API except me because it never makes it to dev. How do we sit down and start using them? Frustrated.

Sorry, I know you're right to get the APIs right as best we can, even if it takes more time.  Also sorry for being difficult to work with on this part of the project.  If you could take over the driver PR, I would appreciate it and be relieved and can work on crytpo/tls port and ch9120 driver.  Thanks for the review time.

**Comment by soypat** [comment]
> I have what I need now, and if driver/stack interfaces change, I should be insulated from those changes since I'm building apps on top of "net".

Alright, we still need to merge netdev-3 on tinygo-org/net for this to work though with the `useNetdev` hack?

> Would consider taking over on the driver/stack interfaces and develop a PR to replace mine? 

As soon as I get around to finishing the TCP stack I'll be available. By then it I think I'll have a solid idea of where to take the API.

> I think the tinygo-org/tinygo and tinygo-org/net PRs are ready to go;

I would think so as well. It is my understanding there is no exported API that break compatibility with upstream Go. I do have one reservation though regarding `net.netdev` interface: replace `net.IP` with `netip.Addr` and `netip.AddrPort` where appropiate. Proposal below:

```go
type netdever interface {
	// GetHostByName returns the IP address of either a hostname or IPv4
	// address in standard dot notation
	GetHostByName(name string) (netip.Addr, error)

	// Addr returns IP address assigned to the interface, either by
	// DHCP or statically
	Addr() (netip.Addr, error)

	// Berkely Sockets-like interface, Go-ified.  See man page for socket(2), etc.
	Socket(domain int, stype int, protocol int) (int, error)
	Bind(sockfd int, addr netip.AddrPort) error
	Connect(sockfd int, host netip.AddrPort) error
	Listen(sockfd int, backlog int) error
	Accept(sockfd int, addr netip.AddrPort) (int, error)
	Send(sockfd int, buf []byte, flags int, deadline time.Time) (int, error)
	Recv(sockfd int, buf []byte, flags int, deadline time.Time) (int, error)
	Close(sockfd int) error
	SetSockOpt(sockfd int, level int, opt int, value interface{}) error
}
```


@scottfeldman Finally, as unsincere as it may sound I am sorry it took this long and is still taking this long to get these up to where they are now. I do feel like this took way more than it could have.

**Review by soypat — APPROVED** [review]
@deadprogram @scottfeldman This PR looks good. Are we ready to create the corresponding https://github.com/tinygo-org/net/tree/dev PR?

**Comment by deadprogram** [comment]
I have merged the `dev` branch of `net` into `main` on that repo, so I can now update this PR to point to it.

**Comment by deadprogram** [comment]
Actually, since the submodule already pointed to that SHA, no change required in this repo.

**Comment by soypat** [comment]
Aha! So it was merged, must have missed the `netdev.go` file first time I looked at it. I've created a PR to modify the netdever API to use the `netip.Addr` type which is a pretty good fit for embedded systems where heap allocations are a relatively large cost to pay. Be great to get eyes from you too @scottfeldman since this would impact your APIs which are already in use.

PR in question: https://github.com/tinygo-org/net/pull/8

**Comment by scottfeldman** [comment]
PR tinygo-org/net#8 LGTM.  Need a corresponding PR in tinygo-drivers for the netdever interface changes.

**Comment by scottfeldman** [comment]
> ### Naming
> The naming: `probe.Probe` does not really tell me or I think anyone of what is happening, why the call is needed. Having different packages for netlink/probe/netdev is confusing- these packages often need one another. This on top of the `netdev.Netdever`, `probe.Probe`, and `netlink.Netlinker` which is stuttersome at best and just confusing at worse because if I put myself in the place of someone who knows a thing or two about networking I don't think I could reliably always make out which is which. They are just too similarly named or vaguely named... and often are represented by the same underlying type, which adds to the confusing aspect of it all (see composing interfaces below)!

One comment about naming: The names netdev, netlink, and probe are all borrowed from Linux network driver kernel space, so they would be familiar to someone that's worked in that space.  I'm from that space, but I didn't think about others not being familiar with those names.  It's likely these Linux names have roots in BSD networking, so they should be familiar to folks with background in UNIX BSD networking drivers.

It could be worse!  I could have used Microsoft NDIS names for everything, complete with VeryLongNamesWithCamelCase.

In any case, here's how I would define netdev, netlink, and probe:

netdev: an L3 interface; the thing that is assigned an IP address and can send/recv IP traffic.  Has an UP/DOWN state.

netlink: an L2 interface; to send/recv eth traffic.  Has a MAC address.  Has an UP/DOWN state.

probe: OS function to probe system hardware, matching devices to drivers.  Matching is done by some unique hardware ID like PCI device/vendor ID or USB device ID.  Probe will create a driver instance for each matching device.  We're not an OS, but we need some mechanism to bind a driver to a device without explicitly calling out the driver.  Similar to how a tinygo app uses machine.LED without specifying the target hardware, an app should be able to use "net" package without specifying the target networking hardware.  That is the intent of probe.

**Comment by scottfeldman** [comment]
> PR [tinygo-org/net#8](https://github.com/tinygo-org/net/pull/8) LGTM. Need a corresponding PR in tinygo-drivers for the netdever interface changes.

Ok, I added tinygo-org/drivers#622 as a matching PR to match tinygo-org/net#8.  Both need to go in together.  @soypat Please review tinygo-org/drivers#622.

**Comment by deadprogram** [comment]
Updated to point to latest `main` branch in `net`.

**Comment by deadprogram** [comment]
> One comment about naming: The names netdev, netlink, and probe are all borrowed from Linux network driver kernel space, so they would be familiar to someone that's worked in that space.

:100: this is probably very key to getting more people onboard with helping add/maintain this code.

**Comment by deadprogram** [comment]
I am using drivers repo branch `scottfeldman-netdev3` as it is rebased against the latest things.

**Comment by deadprogram** [comment]
The time has come to merge this! Great work @scottfeldman and thanks very much to @soypat for so much help reviewing and testing.

**Comment by aykevl** [comment]
I'm sorry I missed the discussion on the net package (it was a bit much to follow - sorry!), but why is this a submodule and not a regular package? Is there some benefit to keeping it in a submodule?

**Pull request merged**
