### PR TITLE
Remove microbit matrix

### PR DESCRIPTION
**Pull request by conejoninja**
Code should be moved to a driver

### CODE REVIEW

**Comment by deadprogram** [comment]
The reason I added them here, was so that these docs would work from the main repo without any external dependencies: https://tinygo.org/usage/basic/#building-flashing-a-blink-program-for-micro-bit

**Comment by conejoninja** [comment]
wops! I had my doubts about removing the example too, didn't feel quite right. There will be some duplicated code with the external driver, but it's small enough.

(I think there's need for a _Displayer_ compatile external driver)

**Comment by deadprogram** [comment]
Your driver PR is far superior to the code you propose to remove. But it then removes the easy path to a blinking LED on the microbit. Really I just care about that.

What do you think, @conejoninja can you leave in just enough code to do that?

**Comment by aykevl** [comment]
I also never felt quite right about putting this driver into the machine package, but if we replace this I'd like to see _some_ way of blinking an LED.

**Comment by conejoninja** [comment]
The alternative example could be this, similar to existing others:

```go
// blink program for the BBC micro:bit that uses the entire LED matrix
package main

import (
	"machine"
	"time"
)

func main() {
	/* microbit's matrix pins
	{{LED_ROW_1, LED_COL_1}, {LED_ROW_2, LED_COL_4}, {LED_ROW_1, LED_COL_2}, {LED_ROW_2, LED_COL_5}, {LED_ROW_1, LED_COL_3}},
	{{LED_ROW_3, LED_COL_4}, {LED_ROW_3, LED_COL_5}, {LED_ROW_3, LED_COL_6}, {LED_ROW_3, LED_COL_7}, {LED_ROW_3, LED_COL_8}},
	{{LED_ROW_2, LED_COL_2}, {LED_ROW_1, LED_COL_9}, {LED_ROW_2, LED_COL_3}, {LED_ROW_3, LED_COL_9}, {LED_ROW_2, LED_COL_1}},
	{{LED_ROW_1, LED_COL_8}, {LED_ROW_1, LED_COL_7}, {LED_ROW_1, LED_COL_6}, {LED_ROW_1, LED_COL_5}, {LED_ROW_1, LED_COL_4}},
	{{LED_ROW_3, LED_COL_3}, {LED_ROW_2, LED_COL_7}, {LED_ROW_3, LED_COL_1}, {LED_ROW_2, LED_COL_6}, {LED_ROW_3, LED_COL_2}}
	*/
	ledrow := machine.GPIO{machine.LED_ROW_1}
	ledrow.Configure(machine.GPIOConfig{Mode: machine.GPIO_OUTPUT})
	ledcol := machine.GPIO{machine.LED_COL_1}
	ledcol.Configure(machine.GPIOConfig{Mode: machine.GPIO_OUTPUT})
	ledcol.Low()
	for {
		ledrow.Low()
		time.Sleep(time.Millisecond * 500)

		ledrow.High()
		time.Sleep(time.Millisecond * 500)
	}
}
```


The comment with the matrix' row-columns could be helpful if you are unaware they are not in order, not really sure what could be the correct format to put it.

**Comment by deadprogram** [comment]
That example, and a comment that explains that the microbit uses an LED matrix and a link to the driver is probably enough, and to direct people to more info who need it. Don't need the full LED matrix layout as comment.

**Comment by deadprogram** [comment]
Looks good now, thanks @conejoninja merging.

**Pull request merged**
