### PR TITLE
WIP: Esp8266 Get Function

### PR DESCRIPTION
**Pull request by vertoforce**
I really am not positive about what I'm doing, but the more I get my feet wet the more I can help :)

For anyone looking to make similar changes, it looks like the registers are defined [here](https://github.com/cnlohr/nosdk8266/blob/f189866d1ecbcdb7a7fe71be3c200458cd257b22/useful/esp8266.h).

You can see the esp8266 technical specs [here](https://www.espressif.com/sites/default/files/documentation/esp8266-technical_reference_en.pdf)

Fixes https://github.com/tinygo-org/tinygo/issues/1396

### CODE REVIEW

**Comment by vertoforce** [comment]
Reading more in to the datasheets...

**Comment by vertoforce** [comment]
I'm not sure why you are bit shifting the input pin in the setting of values (`1<<p`), but I removed it in the getting.  I might be wrong there.

**Comment by deadprogram** [comment]
Hello @vertoforce thanks for contributing to TinyGo.

Regarding the GPIO input, this is info from https://www.espressif.com/sites/default/files/documentation/esp8266-technical_reference_en.pdf:

> 2.2.3. GPIO Input Register
> bit[15:0] the input status bit (readable and writable):
> If the related bit is set to be 1, the IO pin status is high level. If the related bit is set to be 0,
> the IO pin status is low level. Bit[15:0] contains 16 GPIO input status bits. 

This is a very common pattern on microcontrollers, which is the state of the bit in a particular position corresponds to that specific pin.

So, pin 0 is bit 0, pin 1 is bit 1, pin 2 is bit 2, etc.  This is why you frequently see (1 << pin) which refers to that bit position.

So you would probably want your code to be something like:

```go
return esp.GPIO.GPIO_IN.Get()&(1 << p) != 0
```

Hope that helps!

**Comment by vertoforce** [comment]
Ah right, thanks @deadprogram! I had a brain-dead moment there forgetting what bitshifts really do.

Updated the PR :)

**Comment by deadprogram** [comment]
Can you please run `go fmt` on your changes, @vertoforce that should allow it to pass the CI tests. Thanks.

**Comment by vertoforce** [comment]
Whoops my bad, done!

**Comment by deadprogram** [comment]
@vertoforce I think you are almost there. If you rebase your branch against the latest `dev` branch then the CircleCI tests should be able to pass.

**Comment by vertoforce** [comment]
Sweet, did it.  Thanks for the help :)

**Comment by deadprogram** [comment]
Looking good now @vertoforce I am going to squash/merge.

Thanks!

**Pull request merged**
