### PR TITLE
Small test improvements

### PR DESCRIPTION
**Pull request by directionless**
Hi!  This PR has a collection of things I think improve the tests. As I haven't talked to any of y'all about them, I recognize that you may disagree. I will not be offended of you don't like some of this, or want me to separate them, or whatnot. 

* Add an ENV the makefile will parse to add `-short` to the `go test` options
* Add llvm bin directory to the PATH in the Makefile
* Enable parallel tests. This required moving tmpfile creation into `runTest`, instead of being shared.
* Change the targeting and dispatch. 

Caveat — I’m on a osx laptop. I can run the short tests successfully, but I get clang errors no matter what I do. So this _probably_ doesn’t make things worse, but I can’t test all the permutations

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @directionless I changed this PR to `dev as mentioned here https://github.com/tinygo-org/tinygo/blob/master/CONTRIBUTING.md#how-to-use-our-github-repository

Here are now some merge conflicts that must be resolved, separate from any feedback on the PR itself, which I will leave to @aykevl probably...

Thank you!

**Comment by aykevl** [comment]
@directionless I agree with the overall goal of this PR. In fact, I have done some preparation for parallel execution of tests a long time ago: https://github.com/tinygo-org/tinygo/commit/3289dd713424ae5ed8391aa750308fcf259b4b23

Unfortunately, when I run this test in CircleCI, there are various errors. I'm not sure what exactly causes them, but they are so random that I'm suspecting memory corruption. For example:
https://circleci.com/gh/tinygo-org/tinygo/1908
https://circleci.com/gh/tinygo-org/tinygo/1905
https://circleci.com/gh/tinygo-org/tinygo/1904

I don't really know what's going on here.

**Comment by deadprogram** [comment]
Seems like this work continues in #641 I would to propose this PR gets closed. Thoughts?

**Comment by deadprogram** [comment]
I am going to close this PR. Please reopen if needed, or look to #641 for further work. Thank you!

**Comment by directionless** [comment]
Sorry I vanished on y'all. Closing is reasonable

**Pull request closed without merging**
