### PR TITLE
Go 1.22 support

### PR DESCRIPTION
**Pull request by aykevl**
Work in progress Go 1.22 support. ~Some features haven't been implemented yet, and cgo crashes.~

### CODE REVIEW

**Comment by aykevl** [comment]
I think the only thing missing is `reflect.TypeFor`, which is now required by encoding/json (and should be trivial to implement).

**Comment by aykevl** [comment]
This is ready for review.

Two things are still missing:

  * The standard library doesn't have a Go module, which means tooling won't detect a Go version. This needs to be fixed, for the next point.
  * For some reason, golang.org/x/tools/go/ssa doesn't seem to use new-style loop variables (see [this page](https://go.dev/wiki/LoopvarExperiment) for details). I need to investigate why this is.

I might fix those in a separate PR.

**Review by deadprogram — APPROVED** [review]
From my point of view, looks good to merge now and let people report any issues.

**Comment by aykevl** [comment]
Thanks! Merged it :shipit:

**Comment by aykevl** [comment]
New Go 1.22 loop variables support: https://github.com/tinygo-org/tinygo/pull/4092

**Pull request merged**
