### PR TITLE
add Fork and Exec libc hooks

### PR DESCRIPTION
**Pull request by leongross**
Add wrappers for fork and Exec so that #4323 can invoke these functionalities properly.

### CODE REVIEW

**Comment by deadprogram** [comment]
Seems fine to me @aykevl @dgryski @dkegel-fastly any comments?

**Review by dkegel-fastly — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thanks @leongross for the addition and to @dkegel-fastly for the review. Now merging.

**Comment by leongross** [comment]
Thanks for the fast response @deadprogram and the quick review @dkegel-fastly :)

**Pull request merged**
