### PR TITLE
fix some comments

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @cuishuang thanks for the code contribution.

I changed the base branch to `dev` as mentioned here: https://tinygo.org/docs/guides/contributing/#how-to-use-our-github-repository

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Now merging @cuishuang thanks!

**Comment by cuishuang** [comment]
> Now merging @cuishuang thanks!

My pleasure

**Pull request merged**
