### PR TITLE
builder,loader: link .syso files

### PR DESCRIPTION
**Pull request by eliasnaur**

### CODE REVIEW

**Review by aykevl — COMMENTED** [review]
This looks fine and I think it would work, but I'm a bit unsure we should do it like this. Because we have many targets (baremetal and wasi) that pretend to be something they are not, usually linux/arm. And I don't think we should link .syso files in these cases.
We could for example add `(compileopts.Config).IsRegularOS()` (name TBD) that checks for particular build tags, I think `wasi` and `baremetal` would be enough.
For normal OSes (linux, MacOS, Windows), linking them should be fine.

Another consideration: TinyGo (mostly) uses the C calling convention while Go uses a special calling convention. I'm not entirely sure how .syso files are normally used but if they are intended to be used directly from Go files, this calling convention mismatch would be a problem.

**Comment by eliasnaur** [comment]
My STM32F469 board is baremetal, right? If so, not linking .syso files for baremetal targets won't fix #2670 for me. I agree that linking linux/arm syso files are probably a bad idea: at the very least I'd like to discern `_arm.syso` files from, say, `_arm_thumb2.syso` files built for the target.

**Comment by dgryski** [comment]
I believe syso files use the standard C calling convention.

**Comment by aykevl** [comment]
> My STM32F469 board is baremetal, right? If so, not linking .syso files for baremetal targets won't fix #2670 for me.

Correct.
I'm not sure what the best solution is here. Linking _linux_arm.syso files would indeed be bad for existing code (like [gioui.org/shader/piet](https://git.sr.ht/~eliasnaur/gio-shader/tree/main/item/piet)). But then there is no way to link .syso files for baremetal systems: _linux_thumb2.go won't work as a build exclusion rule with the Go toolchain because `thumb2` isn't a recognized OS/arch name.

What about this: we just say that if users want to link object files in TinyGo on baremetal systems, they have to link .o (or .a) files directly using `#cgo LDFLAGS`. It seems to me that .syso files are normally used as a way to avoid CGo, which is a limitation that doesn't exist in TinyGo. It's perhaps a bit ugly, but I can't really think of a situation where it can't work (unless for some weird reason CGo stops working in TinyGo).

**Comment by eliasnaur** [comment]
Completely agree: automatic .syso linking is for avoiding Cgo and manually adding `#cgo LDFLAGS` is a small price to pay. Thank you for your thoughts.

**Pull request closed without merging**
