### PR TITLE
Allow Go 1.15

### PR DESCRIPTION
**Pull request by QuLogic**
This all seemed to magically work (`go test` and smoketests), but let's see how CI feels about it.

### CODE REVIEW

**Comment by QuLogic** [comment]
To clarify, it [works on 0.13.1](https://koji.fedoraproject.org/koji/taskinfo?taskID=48426761), but I guess new stuff on `dev` makes this not so simple.

**Comment by QuLogic** [comment]
Failure looks related to this re-organization: https://github.com/golang/go/commit/18a6fd44bb9de9399dba86a4c1ae1e56f967bcda

**Comment by deadprogram** [comment]
Same problem exists in the Go 1.15 release. Which now that it has been released, suddenly becomes a big priority. :smile_cat:

**Comment by deadprogram** [comment]
This commit gets all the tests to pass: https://github.com/tinygo-org/tinygo/commit/2abcd01e9c79adf3b48b6df32b2b011c2f490ca8

**Comment by deadprogram** [comment]
@aykevl what do you think?

**Comment by deadprogram** [comment]
I have a branch with the various changes needed for 1.15 here: https://github.com/tinygo-org/tinygo/pull/1293

Everything appears to be working on Linux, I also did manual testing on SAMD21.

However, Windows has a problem https://github.com/tinygo-org/tinygo/pull/1293#issuecomment-674375987

**Comment by deadprogram** [comment]
@QuLogic I created the PR #1293 to handle this, which has now been merged into `dev`. Thank you for starting up the work on this. Now closing this PR.

**Comment by QuLogic** [comment]
Thanks for finishing that up. I meant to get back to this on the weekend, but didn't find the time in the end.

**Pull request closed without merging**
