### PR TITLE
wasm: allow users to provide custom sections

### PR DESCRIPTION
**Pull request by mathetake**
This PR adds `wasm-custom-sections` flag for specifying WASM custom sections. Ref: https://reviews.llvm.org/D43097

### CODE REVIEW

**Comment by aykevl** [comment]
Can you give some context, and explain why this needs to be in TinyGo?
Alternatively, can you add those custom sections later to the generated WebAssembly file? I would assume there are tools that can do this.

**Comment by mathetake** [comment]
> Alternatively, can you add those custom sections later to the generated WebAssembly file? I would assume there are tools that can do this.

Yeah, that's true. closing.

**Comment by Mossaka** [comment]
> Can you give some context, and explain why this needs to be in TinyGo?

There is a need to add custom sections for "processed-by" field that describes the producer of the wasm module. See a discussion [here](https://github.com/bytecodealliance/wit-bindgen/issues/617).

**Comment by aykevl** [comment]
Is it possible to add these custom sections in C? If so, would it be possible to use CGo instead?
(Note that while CGo support in TinyGo is not as completely supported as upstream Go, it does not depend on external tools so it's much easier to use).

**Comment by Mossaka** [comment]
> Is it possible to add these custom sections in C?

Not sure, I will have to try it out

**Pull request closed without merging**
