### PR TITLE
Add tests for WebAssembly

### PR DESCRIPTION
**Pull request by aykevl**
Depends on #130. There are only 3 commits left after that PR gets merged.

### CODE REVIEW

**Comment by aykevl** [comment]
Now I remember why I didn't add WebAssembly tests: lld hangs for some reason on Travis.

**Comment by aykevl** [comment]
This PR should be tested (and rebased) again after #165, I hope that change fixes this PR.

**Comment by aykevl** [comment]
Still not working... will have to look at it another time.

**Comment by deadprogram** [comment]
This branch needs merge conflicts resolved, please.

**Comment by aykevl** [comment]
Fixed. Only a rebase was needed.

**Comment by deadprogram** [comment]
Now that this is working, seems time to merge. WASM support will surely improve more with it being part of the CI build.

**Comment by aykevl** [comment]
Oops, tests fail now because the OS X version of LLVM does not have WebAssembly enabled.

**Pull request merged**
