### PR TITLE
boards: Add MCH2022 badge

### PR DESCRIPTION
**Pull request by aykevl**
I haven't fully tested this badge because I don't have the physical hardware but I have followed the pinout from the website so I hope this will work.

### CODE REVIEW

**Comment by aykevl** [comment]
Looks like something went wrong with the TinyHCI tests?

**Comment by deadprogram** [comment]
I suggest rebase and let's see if it builds correctly this time.

**Comment by aykevl** [comment]
:+1: done

**Comment by deadprogram** [comment]
Merging! :name_badge:

**Pull request merged**
