### PR TITLE
reflect convert things to interfaces if needed

### PR DESCRIPTION
**Pull request by dgryski**

### CODE REVIEW

**Comment by aykevl** [comment]
Looks like this change depends on other changes.

**Comment by dgryski** [comment]
I'll figure out which one it depends on. There only a few candidates.

**Comment by dgryski** [comment]
Probably https://github.com/tinygo-org/tinygo/pull/3557 and https://github.com/tinygo-org/tinygo/pull/3555

**Comment by dgryski** [comment]
Commits added to https://github.com/tinygo-org/tinygo/pull/3557 .  Closing.

**Pull request closed without merging**
