### PR TITLE
feather-stm32f405: add support for Adafruit STM32F405 Feather Express

### PR DESCRIPTION
**Pull request by ardnew**
## Notes

The exact chip on this board is `STM32F405RG`. 

A similar chip (`STM32F407`) already has support, required for target board `stm32f4disco`. Instead of duplicating largely-identical implementations, the following files were renamed with changes made to support _**both**_ targets:

|Deleted (`STM32F407`-only)|Created (`STM32F405`+`STM32F407`)|
|:--------|:--------|
|`src/machine/machine_stm32f407.go`|`src/machine/machine_stm32f40x.go`|
|`src/runtime/runtime_stm32f407.go`|`src/runtime/runtime_stm32f40x.go`|
|`src/device/stm32/stm32f407xx-altfunc-bitfields.go`|`src/device/stm32/stm32f40x-altfunc-bitfields.go`|

Note that because the `STM32F407` implementation already includes basic support for UART and SPI, the same support was automatically inherited by the `STM32F405`. No effort was made to *remove* UART/SPI support for `feather-stm32f405` from this common `STM32F405/STM32F407` implementation. However, the multiple interfaces available for both of these peripherals — (6)×UART, (3)×SPI — on this board have **not** been implemented (their declarations have been included in `src/machine/board_feather-stm32f405.go` for future reference, but are commented out). Only the (1)×UART and (1)×SPI primary interfaces have been implemented and enabled.

I2C is *not* currently implemented for `stm32F4disco`, and was excluded via build tag in `src/machine/i2c.go`. Similarly, a build tag exclusion was added for `feather_stm32f405` to the same file.

#### Programming

Flashing this board using its DFU bootloader is a bit awkward/cumbersome (see Adafruit docs linked below), but it is possible — without requiring an external programmer — by pulling the `B0` pin high (you can use the board's 3.3V output pin) at bootup when connected to host PC via USB. This puts the device in bootloader mode.

Once in bootloader mode, I've verified the device can be programmed using either `STM32CubeProgrammer` (requires ***Oracle*** JDK 8) or the open-source tool `dfu-util` (available in most package manager repos, verified using Ubuntu 20.04).

> Alternatively, I've been using a J-Link Mini EDU SWD programmer connected to the header on the reverse side of the board without issue.

|Programmer|URL|
|:-------------:|:----|
|`STM32CubeProgrammer`|https://www.st.com/en/development-tools/stm32cubeprog.html|
|`dfu-util`|http://dfu-util.sourceforge.net/|

#### ST
|Title|URL|
|:----:|:----|
|Overview|https://www.st.com/content/st_com/en/products/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus/stm32-high-performance-mcus/stm32f4-series/stm32f405-415/stm32f405rg.html|
|Datasheet|https://www.st.com/resource/en/datasheet/stm32f405rg.pdf|
|UserManual|https://www.st.com/resource/en/reference_manual/dm00031020-stm32f405415-stm32f407417-stm32f427437-and-stm32f429439-advanced-armbased-32bit-mcus-stmicroelectronics.pdf|

#### Adafruit

|Title|URL|
|:----:|:----|
|Overview|https://learn.adafruit.com/adafruit-stm32f405-feather-express/overview|
|Bootloader|https://learn.adafruit.com/adafruit-stm32f405-feather-express/dfu-bootloader-details|
|Schematic|https://learn.adafruit.com/adafruit-stm32f405-feather-express/downloads|

#### STM32duino 

A lot of info was derived from these relevant chip/board-specific implementations in [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32)

|Title|URL|
|:----:|:----|
|Variant|https://github.com/stm32duino/Arduino_Core_STM32/tree/master/variants/FEATHER_F405|
|HAL|https://github.com/stm32duino/Arduino_Core_STM32/tree/master/system/STM32F4xx|

### CODE REVIEW

**Comment by sago35** [comment]
If you can rebase to dev branch again, the pull-request will be easier to read. @ardnew

**Comment by aykevl** [comment]
Yes, please rebase to make this reviewable.

Also, there are some duplicate definitions:

```
build/tinygo build -size short -o test.hex -target=stm32f4disco        examples/blinky1
# machine
/home/circleci/project/src/machine/machine_stm32f40x.go:15:2: PA0 redeclared in this block
/home/circleci/project/src/machine/board_stm32f4disco.go:11:2: 	other declaration of PA0
/home/circleci/project/src/machine/machine_stm32f40x.go:16:2: PA1 redeclared in this block
/home/circleci/project/src/machine/board_stm32f4disco.go:12:2: 	other declaration of PA1
/home/circleci/project/src/machine/machine_stm32f40x.go:17:2: PA2 redeclared in this block
/home/circleci/project/src/machine/board_stm32f4disco.go:13:2: 	other declaration of PA2
```

These should be in the machine_stm32f40x.go file (or alternatively in a new board_stm32f40x.go file).

**Comment by ardnew** [comment]
> Yes, please rebase to make this reviewable.

Sorry, still learning Git, will research how to rebase. 

> Also, there are some duplicate definitions:
> 
> These should be in the machine_stm32f40x.go file (or alternatively in a new board_stm32f40x.go file).

Thanks. I moved those defs from `board_feather-stm32f405.go` to `machine_stm32f40x.go`, and apparently forgot to *remove* them from `board_stm32f4disco.go`. 

Wonder why `make test` didn't catch this? Or, how did you catch it?

**Comment by aykevl** [comment]
> Wonder why `make test` didn't catch this? Or, how did you catch it?

`make test` is for compiler tests, basically to check whether generic Go code compiles and executes correctly on various architectures. You can use `make smoketest` to catch errors like this (as is done in CI).

**Pull request closed without merging**
