### PR TITLE
main: refactor compile/link part to a builder package

### PR DESCRIPTION
**Pull request by aykevl**
This is a large commit that moves all code directly related to
compiling/linking into a new driver package. This has a number of
advantages:

  * It cleanly separates the API between the command line and the full
    compilation (with a very small API surface).
  * When the compiler finally compiles one package at a time (instead of
    everything at once as it does now), something will have to invoke it
    once per package. This driver package will be the natural place to
    do that, and also be the place where the whole process can be
    parallelized.
  * It allows the TinyGo compiler to be used as a package. A client can
    simply import the driver package and compile code using it.

As part of this refactor, the following additional things changed:

  * Exported symbols have been made unexported when they weren't needed.
  * The compilation target has been moved into the compileopts.Options
    struct. This is done because the target really is just another
    compiler option, and the API is simplified by moving it in there.
  * The moveFile function has been duplicated. It does not really belong
    in the drivers API but is used both by the driver and the command
    line. Moving it into a separate package didn't seem useful either
    for what is essentially an utility function.
  * Some doc strings have been improved.

Some future changes/refactors I'd like to make after this commit:

  * Clean up the API between the driver and the compiler package.
  * Perhaps move the test files (in testdata/) into the driver package.

### CODE REVIEW

**Comment by jadr2ddude** [comment]
I like the premise of this PR, but I do not think that the name `driver` describes the purpose of this package in a meaningful way. Perhaps `build` would work better, as it mirrors `go build` and seems to describe the entire process.

**Comment by deadprogram** [comment]
That seems like good general feedback from @jadr2ddude and `build` seems to match other go package names.

**Comment by aykevl** [comment]
I've been thinking about the same: `driver` vs `build`. I picked `driver` because that is how it is usually called in C compilers. The command `gcc` and `clang` are really compiler drivers: they invoke lower-level tools like `cc1` (the actual C compiler), `as` or `cc1as` (the assembler), and `ld` (the linker).

Perhaps `build` would be better. However, note that the package [`"go/build"`](https://godoc.org/go/build) has a very different purpose (but it is nowadays largely replaced with [`"go/packages"`](https://godoc.org/golang.org/x/tools/go/packages)).

**Comment by deadprogram** [comment]
That is true about a somewhat different purpose in the Go packages. In our case however `build` seems like a satisfactory naming.

**Comment by aykevl** [comment]
Ok, will rename.

**Comment by aykevl** [comment]
Oops, there is already a directory named build, which is where `make` and `make release` will store the resulting build artifacts.
I think it would be reasonable to rename that directory, but can't think of a good name right now. Perhaps just `bin`? Any suggestions?

**Comment by deadprogram** [comment]
How about we name our package `builder` because it is very common to have `build` directory?

**Comment by aykevl** [comment]
Sounds good. Renamed the package.

**Comment by deadprogram** [comment]
OK, this looks good to me now. Merging.

**Pull request merged**
