### PR TITLE
LLVM 8

### PR DESCRIPTION
**Pull request by aykevl**
These are some changes necessary for LLVM 8 support. Not yet ready to be merged because tests don't pass in LLVM 8. It looks like this is because of LLVM bugs.

### CODE REVIEW

**Comment by aykevl** [comment]
The second commit should probably not be merged until LLVM 8 is released, but the first commit would be useful for people who want to experiment with LLVM 8. It should work just fine on LLVM 7.

**Comment by aykevl** [comment]
At the moment, the llvm-toolchain-stretch-8 build is broken, will have to wait until it works again.

**Comment by aykevl** [comment]
This PR is now ready to merge.

**Comment by deadprogram** [comment]
:8ball:

**Pull request merged**
