### PR TITLE
src/os: Add UserHomeDir() function to os package

### PR DESCRIPTION
**Pull request by ZauberNerd**
This commit adds the `UserHomeDir()` function to the `os` package.

### CODE REVIEW

**Comment by dkegel-fastly** [comment]
Please also port the corresponding test if possible, e.g. TestUserHomeDir()

**Comment by dkegel-fastly** [comment]
Looks like it failed "make tinygo-test-wasi-fast".

**Comment by ZauberNerd** [comment]
Ok, so it fails because `$HOME` is not defined: https://github.com/tinygo-org/tinygo/pull/2682/files#diff-9104369aad12ebcc262dc47f26321742fe4b10d31e30bc53832e869f4a7b3bceR277
And the [`t.SkipF()`](https://github.com/tinygo-org/tinygo/pull/2682/files#diff-ad834cc3078ff26b65749c4d2bf9bb98dc5f7069502c99aa21aa34275e770e1bR14) function didn't seem to do what I expected.

But this begs the question: Is it correct, that it returns an empty string / error on WASI (and possibly on baremetal too?)

The test failures on Windows are unrelated - the `MinoruSekine/setup-scoop@v1` fails.

**Comment by dkegel-fastly** [comment]
I suspect / would be a fine thing to return on WASI if HOME is not set (cf.https://github.com/WebAssembly/WASI/issues/771 ).

t.SkipF() is unfortunately broken for now on Tinygo, with no fix planned any time soon; you can use t.Log(("Skipping...") followed by return as a workaround.

**Comment by deadprogram** [comment]
Please rebase against the latest dev, so that the Windows tests can run correctly. Thanks!

**Review by dkegel-fastly — CHANGES_REQUESTED** [review]
upstream has the test in os_test.go rather than file_test.go, suggest moving it to end of os_anyos_test.go.  Otherwise this is identical to upstream and ready to go.

**Review by dkegel-fastly — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thank you @ZauberNerd and @dkegel-fastly now merging.

**Pull request merged**
