### PR TITLE
add struct size and field offsets to reflect data

### PR DESCRIPTION
**Pull request by dgryski**
An alternate solution to https://github.com/tinygo-org/tinygo/pull/3598

### CODE REVIEW

**Comment by dgryski** [comment]
I'll get some numbers on how this affects binary size.

**Comment by dgryski** [comment]
Huh.
```
5880 -rwxr-xr-x  1 dgryski  staff  3006641 18 Apr 09:28 service.dev*
5880 -rwxr-xr-x  1 dgryski  staff  3007882 18 Apr 09:33 service.struct-size*
8320 -rwxr-xr-x  1 dgryski  staff  3663752 18 Apr 10:30 service.offset-cache*
```

This is the same service, build with `dev`, this PR, and the offset cache one.  Clearly *something* is going on with the offset cache PR that causes a massive space blowup, at least on wasi.  I don't know what.  However, assuming I didn't totally fluff this PR the overhead of the extra fields in the binary seems minimal.

**Comment by dgryski** [comment]
This seems like a better approach than all the caching logic.

**Comment by dgryski** [comment]
The uint16s aren't big enough.  Need to be `uintptr` I guess.
```
2023/04/19 18:06:40 FAIL	golang.org/x/image/draw	0.000s
/Users/dgryski/go/src/go.googlesource.com/go/src/compress/flate/deflate.go:703:2: struct compress/flate size 656672 too big
/Users/dgryski/go/src/go.googlesource.com/go/src/compress/flate/deflate.go:82:2: struct compress/flate size 656648 too big
/Users/dgryski/go/src/go.googlesource.com/go/src/compress/flate/deflatefast.go:58:2: struct compress/flate size 131104 too big
/Users/dgryski/go/src/go.googlesource.com/go/src/compress/flate/deflatefast.go:59:2: struct field compress/flate field prev []byte (1) offset 131072 too big
/Users/dgryski/go/src/go.googlesource.com/go/src/compress/flate/deflatefast.go:60:2: struct field compress/flate field cur int32 (2) offset 131096 too big
```

**Review by deadprogram — APPROVED** [review]
Looks good to me!

**Comment by deadprogram** [comment]
Certainly superior to #3598 just by virtue of being fewer LoC changed, if nothing else.

**Comment by deadprogram** [comment]
@dgryski can you please resolve merge conflict here too?

**Comment by deadprogram** [comment]
Any comments before merge @aykevl ? After the branch is rebased, of course.

**Comment by aykevl** [comment]
This looks quite reasonable to me, and I'm going to assume it also doesn't have a big size increase.
Does it also fix the quadratic issues you were having?

**Comment by dgryski** [comment]
Yes. The quadratic runtime was from repeatedly looping over the entire structure for these two values. Turning them into straight lookups solves that.

**Comment by dgryski** [comment]
Rebased against `dev`.  PTAL.

**Comment by deadprogram** [comment]
Thank you very much for working on this @dgryski finally merging!

**Pull request merged**
