### PR TITLE
machine/stm32: correct Flash implementation

### PR DESCRIPTION
**Pull request by deadprogram**
This PR corrects the implementation for the Flash on STM32, based on changes/testing done as part of #3536 which has to be merged before this PR, which is why this one is draft.

### CODE REVIEW

**Comment by deadprogram** [comment]
Now that #3536 has been merged, this PR is ready for review.

**Comment by deadprogram** [comment]
@kenbell @bgould anyone else?

**Comment by bgould** [comment]
I have a stm32 coming that is supposed to be delivered today, so will try testing once it arrives

**Review by kenbell — APPROVED** [review]
lgtm

**Comment by deadprogram** [comment]
Thanks for reviews @kenbell and @bgould now merging.

**Pull request merged**
