### PR TITLE
 targets: add serial and serial-port key to JSON files for adafruit and seeed

### PR DESCRIPTION
**Pull request by sago35**
~Note: #1969 needs to be merged before this PR.~

In this PR, we will add the serial-port key that we added in #1956 for the Adafruit and Seeed boards.

### CODE REVIEW

**Comment by sago35** [comment]
The Adafruit board definition was generated from the following.
I've pasted the one generated by the perl script described below.

https://github.com/adafruit/ArduinoCore-samd/blob/master/boards.txt
https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/boards.txt

```
adafruit_blm_badge
    "serial": "usb",
    "serial-port": ["acm:239a:80bf", "acm:239a:00bf"],
adafruit_circuitplayground_m0
    "serial": "usb",
    "serial-port": ["acm:239a:8018", "acm:239a:0019"],
adafruit_crickit_m0
    "serial": "usb",
    "serial-port": ["acm:239a:802d", "acm:239a:002d", "acm:239a:802d"],
adafruit_feather_m0
    "serial": "usb",
    "serial-port": ["acm:239a:800b", "acm:239a:000b", "acm:239a:0015"],
adafruit_feather_m0_express
    "serial": "usb",
    "serial-port": ["acm:239a:801b", "acm:239a:001b"],
adafruit_feather_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8022", "acm:239a:0022"],
adafruit_feather_m4_can
    "serial": "usb",
    "serial-port": ["acm:239a:80cd", "acm:239a:00cd"],
adafruit_gemma_m0
    "serial": "usb",
    "serial-port": ["acm:239a:801c", "acm:239a:001c"],
adafruit_grandcentral_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8031", "acm:239a:0031", "acm:239a:0032"],
adafruit_hallowing
    "serial": "usb",
    "serial-port": ["acm:239a:dead", "acm:239a:d1ed", "acm:239a:b000"],
adafruit_hallowing_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8049", "acm:239a:0049", "acm:239a:804a"],
adafruit_itsybitsy_m0
    "serial": "usb",
    "serial-port": ["acm:239a:800f", "acm:239a:000f", "acm:239a:8012"],
adafruit_itsybitsy_m4
    "serial": "usb",
    "serial-port": ["acm:239a:802b", "acm:239a:002b"],
adafruit_matrixportal_m4
    "serial": "usb",
    "serial-port": ["acm:239a:80c9", "acm:239a:00c9", "acm:239a:80ca"],
adafruit_metro_m0
    "serial": "usb",
    "serial-port": ["acm:239a:8013", "acm:239a:0013"],
adafruit_metro_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8020", "acm:239a:0020"],
adafruit_metro_m4_airliftlite
    "serial": "usb",
    "serial-port": ["acm:239a:8037", "acm:239a:0037"],
adafruit_monster_m4sk
    "serial": "usb",
    "serial-port": ["acm:239a:8047", "acm:239a:0047", "acm:239a:8048"],
adafruit_neokeytrinkey_m0
    "serial": "usb",
    "serial-port": ["acm:239a:80ff", "acm:239a:00ff", "acm:239a:8100"],
adafruit_neotrinkey_m0
    "serial": "usb",
    "serial-port": ["acm:239a:80ef", "acm:239a:00ef", "acm:239a:80f0"],
adafruit_pirkey
    "serial": "usb",
    "serial-port": ["acm:239a:801e", "acm:239a:001e"],
adafruit_proxlighttrinkey_m0
    "serial": "usb",
    "serial-port": ["acm:239a:8103", "acm:239a:0103", "acm:239a:8104"],
adafruit_pybadge_airlift_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8043", "acm:239a:0033", "acm:239a:8043"],
adafruit_pybadge_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8033", "acm:239a:0033", "acm:239a:8033"],
adafruit_pygamer_advance_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8041", "acm:239a:0041", "acm:239a:8042"],
adafruit_pygamer_m4
    "serial": "usb",
    "serial-port": ["acm:239a:803d", "acm:239a:003d", "acm:239a:803e"],
adafruit_pyportal_m4
    "serial": "usb",
    "serial-port": ["acm:239a:8035", "acm:239a:0035"],
adafruit_pyportal_m4_titano
    "serial": "usb",
    "serial-port": ["acm:239a:8053", "acm:239a:8053"],
adafruit_qtpy_m0
    "serial": "usb",
    "serial-port": ["acm:239a:80cb", "acm:239a:00cb", "acm:239a:00cc"],
adafruit_rotarytrinkey_m0
    "serial": "usb",
    "serial-port": ["acm:239a:80fb", "acm:239a:00fb", "acm:239a:80fc"],
adafruit_slidetrinkey_m0
    "serial": "usb",
    "serial-port": ["acm:239a:8101", "acm:239a:0101", "acm:239a:8102"],
adafruit_trellis_m4
    "serial": "usb",
    "serial-port": ["acm:239a:802f", "acm:239a:002f", "acm:239a:0030"],
adafruit_trinket_m0
    "serial": "usb",
    "serial-port": ["acm:239a:801e", "acm:239a:001e"],
cluenrf52840
    "serial": "usb",
    "serial-port": ["acm:239a:8072", "acm:239a:0072", "acm:239a:0071", "acm:239a:8071"],
cplaynrf52840
    "serial": "usb",
    "serial-port": ["acm:239a:8045", "acm:239a:0045", "acm:239a:0046", "acm:239a:8046"],
feather52840
    "serial": "usb",
    "serial-port": ["acm:239a:8029", "acm:239a:0029", "acm:239a:002a", "acm:239a:802a"],
feather52840sense
    "serial": "usb",
    "serial-port": ["acm:239a:8087", "acm:239a:0087", "acm:239a:0088", "acm:239a:8088"],
itsybitsy52840
    "serial": "usb",
    "serial-port": ["acm:239a:8051", "acm:239a:0051", "acm:239a:0052", "acm:239a:8052"],
mdbt50qrx
    "serial": "usb",
    "serial-port": ["acm:239a:810b", "acm:239a:010b", "acm:239a:810c"],
metro52840
    "serial": "usb",
    "serial-port": ["acm:239a:803f", "acm:239a:003f", "acm:239a:0040", "acm:239a:8040"],
particle_xenon
    "serial": "usb",
    "serial-port": ["acm:239a:8029", "acm:239a:0029", "acm:239a:002a", "acm:239a:802a"],
```

It was generated by the following perl script.

```perl
use strict;
use warnings;
use utf8;

use Path::Tiny;

my $p1 = path("~/dev/src/github.com/adafruit/ArduinoCore-samd/boards.txt");
my $p2 = path("~/dev/src/github.com/adafruit/Adafruit_nRF52_Arduino/boards.txt");

my $info = {};
foreach my $line ($p1->lines({chomp => 1}), $p2->lines({chomp => 1})) {
    next if $line =~ /^\s*#/;
    if ($line =~ /^([^\.]+)\.([vp]id)\.(\d+)=(0x\w+)/) {
        if (not exists $info->{$1}) {
            $info->{$1}->{$2} = [];
        }
        push @{$info->{$1}->{$2}}, hex $4;

        #printf "%s\n", $line;
    }
}

use Data::Dumper;
if (0) {
    print Dumper $info;
}

foreach my $board (sort {$a cmp $b} keys %$info) {
    printf "%s\n", $board;
    my @vid_and_pids;

    for (my $i = 0; $i < scalar @{$info->{$board}->{vid}}; $i++) {
        push @vid_and_pids, sprintf "acm:%04x:%04x", $info->{$board}->{vid}->[$i], $info->{$board}->{pid}->[$i];
    }

    printf "    \"serial\": \"usb\",\n";
    printf "    \"serial-port\": [%s],\n", join ", ", map {qq'"$_"'} @vid_and_pids;
}
```

**Comment by sago35** [comment]
Seeed's board definitions were created by using dmesg to display the settings of his own board

**Comment by sago35** [comment]
I rebased and force-pushed.
Now ready for review.

**Comment by deadprogram** [comment]
Thanks for all this great research @sago35 now merging.

**Pull request merged**
