### PR TITLE
Fix macos CI builds - github runner python issues

### PR DESCRIPTION
**Pull request by kenbell**
See: https://github.com/actions/runner-images/issues/11545

### CODE REVIEW

**Comment by aykevl** [comment]
I wonder whether it makes sense to wait a bit, perhaps the CI image will soon be fixed? I can't imagine we're the only ones hitting this.

**Comment by kenbell** [comment]
It's been on-going since December 2022, so I'm not so sure it will be fixed soon.

**Comment by kenbell** [comment]
I suspect this will be one of those things that recurs when there's a new python release.  I think the 'fix' I have is (a) working and (b) fairly innocuous in terms of future maintenance.

**Comment by deadprogram** [comment]
@kenbell thanks for the fix. It is rather annoying to be sure, but seems like upstream is stalled.

**Pull request merged**
