### PR TITLE
Refactor transformation passes

### PR DESCRIPTION
**Pull request by aykevl**
Move transformation passes to a new package, and add unit tests.
This PR is just a first step. I hope to move most if not all passes to this new package, to make the compiler package simpler. This is part of the overall goal to refactor the compiler: #285.

The tests depend on a change in the go-llvm package so is not finished yet: https://reviews.llvm.org/D66379

### CODE REVIEW

**Comment by aykevl** [comment]
Pushed the changes needed to LLVM upstream and backported them to the go-llvm package. To use them here, I updated go.mod and go.sum. At the same time, I removed the leftover Gopkg files, because we're  not really using `dep` anymore and it's only a maintenance burden.

Additionally, I've added some more tests to the map optimizations.

**Comment by aykevl** [comment]
@deadprogram what's your opinion on the direction this PR goes into?

**Comment by deadprogram** [comment]
I think this is probably the way forward as far as separation of concerns.

I'd like to know what @jadr2ddude thinks. Feedback?

**Comment by jadr2ddude** [comment]
I am not quite sure I like the idea of all of these passes staying exported long-term. It might be better if we actually reduced the externally exported API instead. We could maybe push some of this into an internal package if we wanted to break it up.

**Comment by aykevl** [comment]
These passes could be unexported at some point in the future, when the `Optimize` call itself has also been moved over to this new package. That would leave just the `Optimize` function and nothing else. I don't think it's super useful (they're supposed to be runnable at any time, just like LLVM passes) but it could be useful to encapsulate.

As for the llvmutil package, I see your point. Perhaps some could be merged into the go-llvm package (such as `GetZeroValue`, which belongs there anyway). Others might just be copied around to each package.

**Comment by aykevl** [comment]
I removed the llvmutil package. With that, I think I've addressed all concerns.

**Comment by deadprogram** [comment]
I was looking over the changes while it was building on the CI. From my POV this is now ready to merge. Any other feedback from you @jadr2ddude on this?

**Comment by jadr2ddude** [comment]
So the actual code seems good, and I do not think that it needs any changes before merging.

However, the `circleci` configuration should be updated before merging. We should be running these new tests in CI. Additionally, some of our caching got broken after removing dep files.

So I guess this means I am finally going to be forced to turn on modules?

**Comment by aykevl** [comment]
I've now also updated BUILDING.md and the Dockerfile to reflect the switch to Go modules. I've started a build at Docker Hub to verify that the Dockerfile change is valid.

> We should be running these new tests in CI.

This is being done, see the changes to .circleci/config.yml and Makefile in the PR.

> Additionally, some of our caching got broken after removing dep files.

Which caching got broken?

> So I guess this means I am finally going to be forced to turn on modules?

I'm afraid so. Although, I still haven't enabled them (all dependencies are checked out in my GOPATH) - that will happen automatically with the upgrade to Go 1.13 somewhere in the future.

**Comment by aykevl** [comment]
I split off the `dep` changes in #552. That PR should ideally be merged first.

**Comment by aykevl** [comment]
Rebased and fixed conflicts. This PR is now ready.

**Comment by deadprogram** [comment]
:car: :robot: merging!

**Pull request merged**
