### PR TITLE
machine/hifive1: complete support for GPIO Get() interface

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds support for the HiFive1 GPIO Get() as well as preparing for several other upcoming additions.

It requires a newer version of the cmsis-svd with the e510x SVD file.

This PR needs #601 be merged fist, and then I will update the PR to remove that commit.

### CODE REVIEW

**Comment by aykevl** [comment]
I would like to wait a few days and see if https://github.com/posborne/cmsis-svd/pull/85 gets merged in that time (often, PRs seem to be merged in 1-10 days). If not, we can use our fork of cmsis-svd instead.

**Comment by deadprogram** [comment]
We are already using the TinyGo fork of cmsis-svd https://github.com/tinygo-org/tinygo/blob/master/.gitmodules#L12 which is the only reason our own build is not already breaking due to new files having been added to that repo. :skull: 

My PR #601 is ble to handle those changes, so we should update our own repo anyhow with those upstream changes.

**Comment by deadprogram** [comment]
The changes were merged into the upstream repo.

**Comment by deadprogram** [comment]
For all of this to work, we need PR #601 & PR #610 also merged along with this PR.

#601 has no dependencies so can be merged first.

Then either this one then #610 or vice-versa. Either way, the tests will not pass without the commits in both PRs at least at the moment.

**Pull request merged**
