### PR TITLE
sam: add support for pin change interrupts (samd5x)

### PR DESCRIPTION
**Pull request by sago35**
#1094
#1111 

I wrote the code for SAMD51J19A and SAMD51J20A.
I checked with feather-m4 and pyportal, and it seems to be working fine.

https://github.com/sago35/tinygo/tree/interrupts-pins-samd51

I'm struggling with how to write the following parts.
Is there a better way to do it?

1. `sam.EIC.CTRLA.Set(0)` or `sam.EIC.CTRLA.ClearBits(0x02)`
    * https://github.com/sago35/tinygo/blob/interrupts-pins-samd51/src/machine/machine_atsamd51.go#L352
2. Is it better to define it outside of SetInterrupt()?
    * https://github.com/sago35/tinygo/blob/interrupts-pins-samd51/src/machine/machine_atsamd51.go#L384
3. I'd like to write a little nicer, but interrupt.New() only accepts const values, so this is how it's implemented.
    * https://github.com/sago35/tinygo/blob/interrupts-pins-samd51/src/machine/machine_atsamd51.go#L393
4. ~~I want to make an example, but the feather-m4 I have doesn't have a button.
Creating an example for pybadge is one thing, but since there is no machine.Button, the other examples need to be modified.~~
    * Since wioterminal has a button, I'm going to make examples with #1124.

### CODE REVIEW

**Comment by sago35** [comment]
The SAMD51P19 has 128 pins, so there's a bit more code.
Also, since the 128 pin setting is not yet in machine_atsamd51.go, it would be better to change it in #1124.

**Comment by sago35** [comment]
@deadprogram 
I cherry-picked it.

**Comment by deadprogram** [comment]
Now merging, thanks for working on this @sago35

**Comment by deadprogram** [comment]
You might want to submit another PR to change `sam.EIC.CTRLA.ClearBits(0x02)` to `sam.EIC.CTRLA.ClearBits(sam.EIC_CTRLA_ENABLE)`

**Pull request merged**
