### PR TITLE
ci: add MacOS arm64 runner

### PR DESCRIPTION
**Pull request by aykevl**
See this post:
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

This is a work in progress.

### CODE REVIEW

**Comment by dgryski** [comment]
I thought TInyGo didn't work for native binaries on M1 ?

**Comment by deadprogram** [comment]
The problem is that the m1 runners are not available on free plans. :crying_cat_face:

**Comment by aykevl** [comment]
> I thought TInyGo didn't work for native binaries on M1 ?

It certainly does, that's how I've used it on MacOS.

**Comment by deadprogram** [comment]
Now that https://github.com/tinygo-org/tinygo/pull/4113 has been merged, I think we can close this one.

**Comment by aykevl** [comment]
Oh, I completely forgot about this PR.

**Pull request closed without merging**
