### PR TITLE
machine/nrf51: add ADC implementation

### PR DESCRIPTION
**Pull request by deadprogram**
This PR adds the ADC implementation for the `nrf51` for boards like the BBC:Microbit and MicrobitV2

### CODE REVIEW

**Comment by deadprogram** [comment]
Tested via https://github.com/tinygo-org/tinyhci/blob/4db55685e4607e47f036db95791e249c8ad717bc/microbit/main.go which is part of https://github.com/tinygo-org/tinyhci/pull/10 and worked as expected.

**Comment by deadprogram** [comment]
Here it is passing now! :smile_cat: 

https://github.com/tinygo-org/tinygo/pull/3315/checks?check_run_id=9720569604

**Comment by breml** [comment]
@deadprogram thanks for this PR.

I just successfully tested this code with a micro:bit V1.5 and an Octopus Analog Rotation Brick. Works like a charm.

The range that I observed is 64 to 65344. ~~So I wonder, if we could do better in extrapolating the 10bit value to 16bit.~~

**Comment by deadprogram** [comment]
Thanks for verifying @breml now merging.

**Pull request merged**
