### PR TITLE
flash: fix getDefaultPort() fails on Windows locales such as Japan

### LINKED ISSUE #1076: flash: getDefaultPort() fails on Windows locales such as Japan
TinyGo on Windows uses wmic in the following, but wmic can't get it well because it returns different strings by locale.
https://github.com/tinygo-org/tinygo/blob/master/main.go#L606.

In English, it probably returns a string like `USB Serial Device (COM7)`, but in Japanese, it returns a string like `USB シリアル デバイス (COM7)`.
I think the solution is as follows.

1. wmic PATH Win32_SerialPort where "Caption LIKE 'USB Serial%' OR Caption LIKE 'USB シリアル%'" GET DeviceID
2. wmic PATH Win32_SerialPort where "Caption LIKE 'USB % (COM%)'" GET DeviceID
3. wmic PATH Win32_SerialPort where "Caption LIKE 'USB %'" GET DeviceID
4. reg query HKLM\HARDWARE\DEVICEMAP\SERIALCOMM

1 needs to add a string condition, such as German or French.
2 and 3 may be written differently in German or French.
4 is a string that works correctly in my environment (windows10 pro) and is probably not affected by locale, but I don't know the details.

    $ reg query HKLM\HARDWARE\DEVICEMAP\SERIALCOMM

    HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\SERIALCOMM
        \frzeroDevice\frzeroUSBSER000 REG_SZ COM7

I think 2 is better, but I'm not sure it works properly in non-Japanese locales (even in English).

### PR DESCRIPTION
**Pull request by sago35**
Resolves #1076

### CODE REVIEW

**Comment by sago35** [comment]
I haven't been able to build the windows version of tinygo so far, so I'm only testing it with the following code.
How can I build windows version of tinygo?

```go
package main

import (
	"errors"
	"fmt"
	"path/filepath"
	"runtime"

	"go.bug.st/serial"
)

func main() {
	fmt.Println(getDefaultPort())
}

// getDefaultPort returns the default serial port depending on the operating system.
func getDefaultPort() (port string, err error) {
	var portPath string
	switch runtime.GOOS {
	case "darwin":
		portPath = "/dev/cu.usb*"
	case "linux":
		portPath = "/dev/ttyACM*"
	case "freebsd":
		portPath = "/dev/cuaU*"
	case "windows":
		ports, err := serial.GetPortsList()
		if err != nil {
			return "", err
		}

		if len(ports) == 0 {
			return "", errors.New("no serial ports available")
		} else if len(ports) > 1 {
			return "", errors.New("multiple serial ports available - use -port flag")
		}

		return ports[0], nil
	default:
		return "", errors.New("unable to search for a default USB device to be flashed on this OS")
	}

	d, err := filepath.Glob(portPath)
	if err != nil {
		return "", err
	}
	if d == nil {
		return "", errors.New("unable to locate a serial port")
	}

	return d[0], nil
}
```

**Comment by aykevl** [comment]
You can download the release as a zip file from the Azure CI build ("tinygo-CI"). It's called an artifact. See "All checks have passed" below.

**Comment by sago35** [comment]
I've tested it.
It is working as expected.
However, there is still a problem with #1077.

```
C:\tinygo-pr\tinygo_#1084_796bca6\tinygo>.\bin\tinygo.exe version
tinygo version 0.14.0-dev windows/amd64 (using go version go1.13.8 and LLVM version 10.0.0)

C:\tinygo-pr\tinygo_#1084_796bca6\tinygo>.\bin\tinygo.exe flash -target pyportal -size short ./src/examples/blinky1
   code    data     bss |   flash     ram
   7876       8    6360 |    7884    6368
```

The following is a test using both PyPortal and feather-m4.
It is working as expected.

```
C:\tinygo-pr\tinygo_#1084_796bca6\tinygo>.\bin\tinygo.exe flash -target pyportal -size short ./src/examples/blinky1
   code    data     bss |   flash     ram
   7876       8    6360 |    7884    6368
error: multiple serial ports available - use -port flag

C:\tinygo-pr\tinygo_#1084_796bca6\tinygo>.\bin\tinygo.exe flash -target pyportal -port COM7 -size short ./src/examples/blinky1
   code    data     bss |   flash     ram
   7876       8    6360 |    7884    6368
error: failed to reset port C:\Users\TAKASA~1.MAS\AppData\Local\Temp\tinygo134572339\main.uf2: opening port: Serial port not found

C:\tinygo-pr\tinygo_#1084_796bca6\tinygo>.\bin\tinygo.exe flash -target pyportal -port COM4 -size short ./src/examples/blinky1
   code    data     bss |   flash     ram
   7876       8    6360 |    7884    6368
```


Even when nothing is plugged in, it is as expected.

```
C:\tinygo-pr\tinygo_#1084_796bca6\tinygo>.\bin\tinygo.exe flash -target pyportal -size short ./src/examples/blinky1
   code    data     bss |   flash     ram
   7876       8    6360 |    7884    6368
error: no serial ports available
```

As of tinygo 0.13.0, getDefaultPort() fails as follows

```
c:\tinygo>.\bin\tinygo.exe version
tinygo version 0.13.0 windows/amd64 (using go version go1.13.8 and LLVM version 10.0.1)

c:\tinygo>.\bin\tinygo.exe flash -target pyportal -size short ./src/examples/blinky1
   code    data     bss |   flash     ram
   7860       8    6360 |    7868    6368
error: unable to locate a serial port
```

**Comment by aykevl** [comment]
I have written some documentation how you can build TinyGo on Windows: https://github.com/tinygo-org/tinygo-site/pull/84 (if you attempt to do this, please report back on any problems you encounter).

I hope to take a look at the PR later, or maybe @deadprogram will. On first glance it looks good.

**Comment by aykevl** [comment]
This looks good to me, thank you for the contribution! This should definitely make TinyGo a bit more accessible for those who don't have their computer set to English.

The other issue of resetting the device can be fixed separately.

**Pull request merged**
