### PR TITLE
Add SPI support for for the ESP32-C3 device.

### PR DESCRIPTION
**Pull request by inindev**
Signed-off-by: John Clark <inindev@gmail.com>

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @inindev thank you for working on this. Can you please run `go fmt` on your file so this part of the CI can pass? https://app.circleci.com/pipelines/github/tinygo-org/tinygo/8599/workflows/61271868-0ff8-439d-8b99-6afaf41b48e9/jobs/39336?invite=true#step-116-3

Thanks!

**Comment by inindev** [comment]
done & passed

I created a doc pull request to add this info to the contributing step. Let me know what you think:
https://github.com/tinygo-org/tinygo-site/pull/320

**Comment by inindev** [comment]
It looks like 3374 was successful, but the message below says: "11 successful and 1 failing checks"
https://app.circleci.com/pipelines/github/tinygo-org/tinygo?branch=pull%2F3374

**Comment by deadprogram** [comment]
Thank you very much for the enhancement @inindev now merging.

**Pull request merged**
