### PR TITLE
reflect: check for access in the Interface method call

### PR DESCRIPTION
**Pull request by aykevl**
This fixes a type system loophole. The following program would incorrectly run in TinyGo, while it would trigger a panic in Go:

    package main

    import "reflect"

    func main() {
        v := reflect.ValueOf(struct {
            x int
        }{})
        x := v.Field(0).Interface()
        println("x:", x.(int))
    }

Playground link: https://play.golang.org/p/nvvA18XFqFC

The panic in Go is the following:

    panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

I've shortened the message in TinyGo to save a little bit of space.

This change also required a change to the runtime package, which was relying on this (incorrect) behavior for map key hashing.

It is currently hard to test this change because there isn't really a practical way of testing panics (`recover` is unimplemented), but at least the existing tests should check for regressions.

---

Apparently this fails because `reflect.valueInterfaceUnsafe` is optimized out. I could fix it, but I know it works with the local branch that caches package builds. Maybe I can finish this PR after that change lands.

### CODE REVIEW

**Comment by aykevl** [comment]
It looks like the CI failures would be fixed by rebasing on top of #1612. There are other workarounds, but #1612 would be the simplest solution.

**Comment by aykevl** [comment]
Rebased, in the hope that CI tests now pass.

**Comment by deadprogram** [comment]
There is now a merge conflict to be resolved here, please.

**Comment by aykevl** [comment]
Rebased. Thank you for the reminder!

**Comment by deadprogram** [comment]
Definitely seems like a good idea to restrict this. Now merging, thanks @aykevl

**Pull request merged**
