### PR TITLE
Add net.Buffers

### PR DESCRIPTION
**Pull request by fgsch**
Should fix the remaining problem from https://github.com/mailru/easyjson/issues/335, for the most part.

### CODE REVIEW

**Comment by fgsch** [comment]
For completion, if we try to build or run the code in the linked issue under macos we get:

```
Undefined symbols for architecture x86_64:
  "_crypto/x509/internal/macos.x509_CFStringCreateWithBytes_trampoline", referenced from:
      _crypto/x509/internal/macos$pack in main.o
  "_internal/abi.FuncPCABI0", referenced from:
      _crypto/x509/internal/macos.StringToCFString in main.o
  "_crypto/ed25519/internal/edwards25519/field.feSquare", referenced from:
      _(*crypto/ed25519/internal/edwards25519/field.Element).Square in main.o
  "_crypto/ed25519/internal/edwards25519/field.feMul", referenced from:
      _(*crypto/ed25519/internal/edwards25519/field.Element).Multiply in main.o
  "_vendor/golang.org/x/sys/cpu.xgetbv", referenced from:
      _runtime.run$1$gowrapper in main.o
  "_crypto/x509/internal/macos.syscall", referenced from:
      _crypto/x509/internal/macos.StringToCFString in main.o
  "_vendor/golang.org/x/sys/cpu.darwinSupportsAVX512", referenced from:
      _runtime.run$1$gowrapper in main.o
  "_vendor/golang.org/x/sys/cpu.cpuid", referenced from:
      _runtime.run$1$gowrapper in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: failed to link /.../tinygo1105991511/main: exit status 1
```

This builds and runs fine under wasi, and at least builds in other platforms.

**Comment by dgryski** [comment]
This is because of the `net/http` import in easyjson's helpers.go.

**Review by dgryski — APPROVED** [review]
LGTM.  Are there net.Buffers tests from stdlib that should be moved over too?

**Comment by fgsch** [comment]
@dgryski there are some we can use. I will update this PR tomorrow.

**Comment by deadprogram** [comment]
@fgsch will you add the tests you mentioned to this PR? :smile_cat:

**Comment by fgsch** [comment]
@deadprogram Yeah, sorry. Been afk the last couple of days. I will get this done today.

**Comment by fgsch** [comment]
@deadprogram tests added.

**Comment by deadprogram** [comment]
Thank you @fgsch for working on this and thanks @dgryski for the review. Now merging.

**Pull request merged**
