### PR TITLE
cgo: add tests

### PR DESCRIPTION
**Pull request by aykevl**
Add tests to CGo processing. They should not only be useful for testing, but also for documentation: you can easily see what CGo generates.

The formatting is somewhat messy but that is (I think) because CGo doesn't output very precise location information. This might be improved in the future but is not very important (it's more of an implementation detail).

### CODE REVIEW

**Comment by deadprogram** [comment]
Regarding Windows, we should just skip these tests for now. CGo and Windows cross compiling is a bigger problem...

Regards the tests failing using Go 1.11, we should decide if we are going to continue supporting that version. The original reason which is supporting LTS version of Ubuntu can be addressed by installing newer Go versions via backports https://github.com/golang/go/wiki/Ubuntu

What do you think?

**Comment by aykevl** [comment]
I have pushed a fix for Go 1.11. I have also pushed a fix for what might cause the problem on Windows (line endings). Let's see what CI thinks of it.

**Comment by aykevl** [comment]
Tests pass!

**Comment by deadprogram** [comment]
OK, great! Now merging.

**Pull request merged**
