### PR TITLE
Makefile: using an alternative LLVM build dir now works

### PR DESCRIPTION
**Pull request by justinclift**
`LLVM_BUILDDIR` can be overridden by environment variable, so might as well adjust the rest of the Makefile to use it.

This now works:

```
$ make llvm-source
$ export LLVM_BUILDDIR=~/stuff
$ make ~/stuff  # instead of make llvm-build
$ make
```

The existing approach (`make llvm-build`) is unchanged by this PR.

### CODE REVIEW

**Comment by justinclift** [comment]
Hold off on this... am trying out a different variation atm.

**Comment by justinclift** [comment]
Should be good to go now. :smile:

**Comment by justinclift** [comment]
Just changed the commit and PR title to follow the format of other commits in the repo.

**Comment by aykevl** [comment]
Sorry for the long delay! I kind of forgot about this PR.
Pushed to the staging branch now to run CI tests.

**Comment by justinclift** [comment]
No worries. :smile:

**Pull request merged**
