### PR TITLE
machine/samd21: Initial implementation of I2S hardware interface

### PR DESCRIPTION
**Pull request by deadprogram**
This PR provides a very basic initial implementation for the I2S hardware interface tested on the Adafruit Circuit Playground Express. It is only known to work with the PDM microphone that is onboard the Circuit Playground Express, although it might work with other I2S devices.

### CODE REVIEW

**Comment by deadprogram** [comment]
Any feedback on this implementation?

**Comment by deadprogram** [comment]
:ok: or :no_entry: ?

**Comment by aykevl** [comment]
The PR in general looks good. What I'm mostly worried about is how buffering is done. Does the hardware provide some sort of buffer, or is there a way to transfer using DMA/interrupts? Unlike most other transports (SPI etc.), small delays will disrupt the signal.

**Comment by deadprogram** [comment]
Really, this is just a naive interface. A future PR may look into using DMA/buffering.

**Pull request merged**
