### PR TITLE
builder: simplify detection of Clang header paths

### PR DESCRIPTION
**Pull request by aykevl**
This detection mechanism should work on both Debian and Fedora, and hopefully other Linux distributions too.

By simplifying this it should be possible to more easily add exceptions for specific systems.

---

Note, this should be merged after the coming release to avoid potential disruption.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @QuLogic does this look like it will address some of the issues you have pointed out in Fedora?

**Comment by deadprogram** [comment]
@QuLogic did you happen to see this PR? What do you think?

**Comment by QuLogic** [comment]
I did not fully test this, but it seems okay, except that I don't think `Glob` is guaranteed to be in any order: golang/go#17153

**Comment by deadprogram** [comment]
Oops, somehow overlooked this PR. Is it still relevant/needed?

**Comment by aykevl** [comment]
> except that I don't think `Glob` is guaranteed to be in any order: [golang/go#17153](https://github.com/golang/go/issues/17153)

Fair enough. I've added a `sort.Strings` call to be sure.

> Is it still relevant/needed?

It's still a simplification and simplifying things is usually a good thing. So I'd say yes.

**Comment by deadprogram** [comment]
Just wondering if this still works as we expect?

**Comment by deadprogram** [comment]
@aykevl is this PR still going to be worked on, or should we close it?

**Comment by aykevl** [comment]
Similar changes have been done here: https://github.com/tinygo-org/tinygo/pull/3948

**Pull request closed without merging**
