### PR TITLE
runtime: linux: implement syscall.Getpagesize like upstream

### PR DESCRIPTION
**Pull request by dkegel-fastly**
Should fix https://github.com/tinygo-org/tinygo/issues/2856, once the code is actually called.

Filed the PR to ask about the linking problem.

### CODE REVIEW

**Comment by aykevl** [comment]
I think directly calling `getpagesize` would be a cleaner solution. You can add it to the musl build with this patch:

```diff
diff --git a/builder/musl.go b/builder/musl.go
index fa29496a..5dae0428 100644
--- a/builder/musl.go
+++ b/builder/musl.go
@@ -115,6 +115,7 @@ var Musl = Library{
                        "internal/libc.c",
                        "internal/syscall_ret.c",
                        "internal/vdso.c",
+                       "legacy/*.c",
                        "malloc/*.c",
                        "mman/*.c",
                        "signal/*.c",
```

**Comment by dkegel-fastly** [comment]
Ok, I'll give that a shot!

**Comment by aykevl** [comment]
And regarding the issue with os_linux.go: I would suggest splitting the file in two. One is `os_linux.go` but only for actual Linux (no baremetal or nintendoswitch), and one is `os_fakelinux.go` (name to be decided) which is only for the not-actually-Linux systems (baremetal, nintendoswitch, wasi) that just need to match an existing operating system for Go standard library compatibility.

**Comment by dkegel-fastly** [comment]
Good. I was using os_real_linux.go, but I prefer your idea.

**Comment by dkegel-fastly** [comment]
Closing in favor of https://github.com/tinygo-org/tinygo/pull/2899

**Pull request closed without merging**
